### ISSUE TITLE
ical.0.data.table leer

### ISSUE THREAD

**Issue by Moneybox76** [iobroker-community-adapters/ioBroker.ical#10]
Hallo,

nach dem Import der Google Kalenderdaten ist der Datenpunkt ical.0.data.table leer. Der Datenpunkt ical.0.data.html wird korrket gefüllt.

<img>http://i1253.photobucket.com/albums/hh582/dermichael01/ical1_zpsqfg4miyf.png</img>
<img>http://i1253.photobucket.com/albums/hh582/dermichael01/ical2_zpswe29hm5k.png</img>

Im iobroker Forum hat ein weiterer User das Problem bestätigt.

VG
Michael

**Comment by jens-maus** [comment]
Bitte hier mal das entsprechende ics file posten damit man es damit testen kann.

**Comment by Apollon77** [comment]
Ok, schliesse issue weil kein ics File da ist. Bitte neu öffnen mit beispiel
