### ISSUE TITLE
Monatsansicht 

### ISSUE THREAD

**Issue by der-eine** [iobroker-community-adapters/ioBroker.ical#100]
Hallo zusammen,

bin gerade dabei, eine Monatsansicht für die VIS-View zu erstellen. Um einen besseren Überblick zu bekommen an welchen Tagen noch nichts geplant ist, würde ich das ganz wie einen „Wandkalender“ erstellen. 

![A38EDAE1-EAE9-43EB-94EC-B7349532AF8C](https://user-images.githubusercontent.com/42468286/54349628-f47f8480-464b-11e9-8ec6-594f5732b279.jpeg)

In diesem Beitrag haben wir schon mal darüber geredet:

https://forum.iobroker.net/topic/20895/ical-monatsansicht-vis/13

Ist es möglich, für den Monat Januar z. B.  31 Tage in Objekten anzulegen um diese dann mit den Strings auf der View zu verbinden? Vor allem auch die Tage an denen kein Termin ist. Habt ihr eine Idee wie man das umsetzen kann? 

Danke für eure Hilfe

Gruß
der-eine

**Comment by pdmetze** [comment]
Monatsansicht für die VIS wäre klasse. Eventuell auch eine json Tabelle oder so, die man dann per CSS selbst formatieren kann?

**Comment by bug84** [comment]
Ich würde mir das auch wünschen
