### ISSUE TITLE
Falscher Output wenn ical nicht erreichbar - bug?

### ISSUE THREAD

**Issue by passuff** [iobroker-community-adapters/ioBroker.ical#101]
Hatte folgendes im log:

`2019-03-15 15:02:10.975  - [33mwarn[39m: ical.0 Error reading from URL "https://xyz": Error: connect ETIMEDOUT 88.99.00.11:443

2019-03-15 15:02:10.976  - [33mwarn[39m: ical.0 Error reading "https://xyz": Error: connect ETIMEDOUT 88.99.00.11:443

2019-03-15 15:02:10.981  - [32minfo[39m: ical.0 Set events.0.today.Fewo to false

2019-03-15 15:02:10.982  - [32minfo[39m: ical.0 Set events.0.now.Fewo to false

2019-03-15 15:02:10.982  - [32minfo[39m: ical.0 Set events.3.Fewo to false
`
Eigentlich sind die Werte beide true, aber da irgendwas nicht erreichbar ist, werden die Werte false gesetzt. Das darf nicht passieren. Meiner Meinung nach muss der letzte Zustand beibehalten werden, wenn es kein bestätigtes Update gab!

**Comment by twonky4** [comment]
Der Adapter funktioniert leider so, das er erst alles einliest und hinterher die states setzt. Wenn jemand mehrere Kalender benutzt und einer davon ist nicht erreichbar weiß ich nicht welches Event zu dem nicht erreichbaren Kalender gehört.

Das kann man umgehen indem man mit dem javascript Adapter den Kalender herrunter läd und ins Dateisystem legt. Wenn der Kalender dann mal nicht erreichbar ist, würde man die Datei nicht löschen. ical konfiguriert man dann auf die lokale Datei.

**Comment by passuff** [comment]
Nach wie vor bereitet mir das Ganze Probleme daher nehme ich mich nun endlich der Lösung an. Wo kann ich Details dazu finden, wie ich per Javascript Adapter den ical auf eine lokale Quelle kopieren kann?

**Comment by Apollon77** [comment]
Was genau meinst Du?

**Comment by passuff** [comment]
Ich meinte das hier:
> Das kann man umgehen indem man mit dem javascript Adapter den Kalender herrunter läd und ins Dateisystem legt. Wenn der Kalender dann mal nicht erreichbar ist, würde man die Datei nicht löschen. ical konfiguriert man dann auf die lokale Datei.

**Comment by Apollon77** [comment]
Aaaahhhhh ... Ich schlage vor dazu im Forum zu fragen. Da sidn einige Skripter die hier helfen können
