### ISSUE TITLE
appointments one hour too early

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.ical#102]
The appointments to be displayed one hour too early

**Comment by Apollon77** [comment]
Please provide more details like your timezone settings and the Ical entry of the appointment. I think there is a timezone issue in the definition of your appointment

**Comment by senger1985** [comment]
I've set the timezone in the terminal on 'Europe / Berlin'.
All times in my vis shows the correct time, only the appointments are wrong

**Comment by Apollon77** [comment]
please see first comment and deliver the ical entry (the text out of the ics file) please

**Comment by senger1985** [comment]
I forgot to restart the nuc, after I change the timezone.
Everything is fine.
Pleace close and forgot my unknowingness. ;-)
