### ISSUE TITLE
Today wird nicht mit Ergeinissen gefüllt

### ISSUE THREAD

**Issue by dirkhe** [iobroker-community-adapters/ioBroker.ical#103]
Hallo,

ich würde erwarten, dass unter events.0.today alle heutigen Termine angezeigt werden. Das werden Sie aber nicht, wenn das Terminende vor der Einlesezeit liegt. Daher denke ich, dass  die Zeile 450 in der main.js fongedermassen geändert werden müsste:
        if ((ev.start >= today && ev.start < endpreview && ev.end >= realnow) || (ev.end ....
zu
        if ((ev.start >= today && ev.start < endpreview && ev.end >= today) || (ev.end ....

Ich habe jetzt extra kein PR aufgemacht, da ich nicht so tief drin bin um zu beurteilen, ob es da sonst irgenwo knallt. Auf den ersten Blick sah es für mich gut aus

gruss
Dirk

**Comment by Apollon77** [comment]
Der iCal Adapter arbeitet aktuell immer "zukunftsorientiert". Bedeutet: Alles was abgelaufen ist vom Enddatum her wird per Absicht ausgeblendet. Also das "today" ist gefüllt BEVOR der termin abgelaufen ist. Also aktuell wäre es für mich ein "as designed"

**Comment by twonky4** [comment]
Genau, abgelaufen Termine werden garnicht berücksichtigt.

**Comment by dirkhe** [comment]
Aber es gibt ein Now und ein later, das würde bedeuten, dass in later immer genau dasselbe steht, wie in Today, warum braucht man dann Today?

**Comment by twonky4** [comment]
Ohne jetzt in den Code zu gucken, würde ich sagen das today beides aus now und later enthält.

**Comment by dirkhe** [comment]
Ja, aber wofür braucht man dann Today?
Ich benutze es halt so, dass ich an einer bestimmten Zeit schaue, ob heute ein Ereignis anliegt. Es handelt sich dabei um den müllkalender, d.h. ich habe keinen Einfluss auf die Erstellung der Termine. Ich würde zwar sagen  dass es blöd ist, wenn Start =end Zeit ist, aber das kann ich nicht ändern. 
Ich könnte zwar auch auf Now reagieren um dann zeitversetzt die Aktion auszuführen (Alexa soll das halt ausquatschen), aber schön finde ich das nicht wirklich.

**Comment by AlexanderSch90** [comment]
sehe es genau wie @dirkhe 

Warum "nullt" man die today-states nicht einfach um mitternacht. Today bedeutet doch für den User: Alle Events im laufe des Tages...

**Comment by Apollon77** [comment]
>Warum "nullt" man die today-states nicht einfach um mitternacht
Der Adapter läuft nach Schedule ... er kann also nichts um 0:00 machen wenn er nicht um 0:00 gestartet wird und wenn er das werden würde (weil man es so konfguriert hat) dann würde die Today alle durch die neuen Today ersetzt werden :-)

**Comment by dirkhe** [comment]
Also ich habe seit Ende März die Änderung so wie oben beschrieben drin und bei mir läuft es super. Ich habe auch noch andere Adapter, die auf den calendar zugreifen und da habe ich auch keine Probleme.
