### ISSUE TITLE
Datapoints for days 4 (index 3) and onwards not created equally

### ISSUE THREAD

**Issue by Xyolyp** [iobroker-community-adapters/ioBroker.ical#111]
The datapoints for day four (index 3) and onwards are not created as channels which results in them not properly inherit enums to the subsidiary datapoints. This leeds to the datapoints not being found by the $() function in js scripts even if no enum is used to filter.
This filter `$(channel[state.id=ical.0.events.*.*])` only outputs the ids for the datapoints of the first three days but I need to do some checks for more than a week worth of datapoints.
![image](https://user-images.githubusercontent.com/13995942/62820911-fbafad80-bb6b-11e9-9613-083d57fd749b.png)

**Comment by Apollon77** [comment]
Also not after reloading

**Comment by Xyolyp** [comment]
Yes reloading and rebooting doesn't change anything.

**Comment by Xyolyp** [comment]
The issue is still present
