### ISSUE TITLE
Crash for Google calendar

### ISSUE THREAD

**Issue by paveltsytovich** [iobroker-community-adapters/ioBroker.ical#113]
Crash for google calendar in rrule module:

> ical.0 | 2019-09-10 14:34:46.598 | error | Error: Unknown RRULE property 'RRULE'     at /opt/iobroker/node_modules/iobroker.ical/node_modules/rrule/dist/es5/rrule.js:1207:23     at Array.forEach (<anonymous>)     at parseRrule (/opt/iobroker/n
> -- | -- | -- | --
> ical.0 | 2019-09-10 14:34:46.596 | error | uncaught exception: Unknown RRULE property 'RRULE'

Thanks

**Comment by Apollon77** [comment]
Can you please also provide the iCal file?
