### ISSUE TITLE
Parsing Problems?

### ISSUE THREAD

**Issue by schuballaa** [iobroker-community-adapters/ioBroker.ical#114]
Hello i installed the i.cal Apapter but I get Noting in Events.
I think its an issue with the parse of the basic.ics (maybe google calendar Changed the ics file?).

On Youtube Videos i saw that the Feld HTML normaly include a List with Events and no html Tags and i Think the Folders with many numbers represens every calender entery.

**On Debug Log i see, its principial working:**
`2019-09-24 14:34:22.778  - [34mdebug[39m: ical.0 {"9":{"type":"VTIMEZONE","params":[],"tzid":"Europe/Berlin","LIC-LOCATION":"Europe/Berlin","a":{"type":"DAYLIGHT","params":[],"tzoffsetfrom":"+0100","tzoffsetto":"+0200","tzname":"CEST","start":"1970-03-29T01:00:00.000Z","datetype":"date-time","rrule":"RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU"},"da":{"type":"STANDARD","params":[],"tzoffsetfrom":"+0200","tzoffsetto":"+0100","tzname":"CET","start":"1970-10-25T02:00:00.000Z","datetype":"date-time","rrule":"RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU"}},"cg@google.com":{"type":"VEVENT","params":[],"start":"2019-09-28T15:00:00.000Z","datetype":"date-time","end":"2019-09-28T16:00:00.000Z","dtstamp":"2019-09-24T12:34:18.000Z","uid":"cg@google.com","created":"2019-09-23T21:53:36.000Z","description":"","lastmodified":"2019-09-23T21:53:36.000Z","location":"","sequence":"0","status":"CONFIRMED","summary":"Nina Geburtstag ","transparency":"OPAQUE"},"cg@google.com":{"type":"VEVENT","params":[],"start":"2019-09-26T20:00:00.000Z","datetype":"date-time","end":"2019-09-26T21:00:00.000Z","dtstamp":"2019-09-24T12:34:18.000Z","uid":"cg@google.com"`

**On the Feld HTML i get this:**
`<span style="font-weight: bold; color: red"><span class="icalWarn iCal-schuballaa">Noch 0 Stunden</span></span><span style="font-weight:normal;color:#000000"><span class='icalWarn2 iCal-schuballaa2'> Zweirad wellbrock anrufen</span></span><br/><span style="font-weight: bold; color: orange"><span class="icalPreWarn iCal-schuballaa">Morgen  </span></span><span style="font-weight: normal; color:#000000"><span class='icalPreWarn2 iCal-schuballaa2'> antwort erhalten?</span></span><br/><span style="font-weight: bold; color: orange"><span class="icalPreWarn iCal-schuballaa">Morgen 08:00-09:00</span></span><span style="font-weight: normal; color:#000000"><span class='icalPreWarn2 iCal-schuballaa2'> Neue brillengläser machen lassen</span></span><br/><span style="font-weight: bold; color: orange"><span class="icalPreWarn iCal-schuballaa">Morgen </span></span><span style="font-weight: normal; color:#000000"><span class='icalPreWarn2 iCal-schuballaa2'> FOLSÄURE NEHMEN</span></span><br/><span style="font-weight: bold; color: yellow"><span class="icalPrePreWarn iCal-schuballaa">Übermorgen 11:00-12:00</span></span><span style="font-weight: normal; color: #000000"><span class='icalPrePreWarn2 iCal-schuballaa2'> metrotexat rezept und info</span></span><br/><span style="font-weight: bold; color: yellow"><span class="icalPrePreWarn iCal-schuballaa">Übermorgen 22:00-23:00</span></span><span style="font-weight: normal; color: #000000"><span class='icalPrePreWarn2 iCal-schuballaa2'> Antwort erhalten? </span></span><br/><span style="font-weight: bold; color: white"><span class="icalNormal iCal-schuballaa">In 4 Tagen 17:00-18:00</span></span><span style="font-weight: normal; color: #000000"><span class='icalNormal2 iCal-schuballaa2'> Nina Geburtstag </span></span><br/><span style="font-weight: bold; color: white"><span class="icalNormal iCal-schuballaa">In 5 Tagen 10:00-11:00</span></span><span style="font-weight: normal; color: #000000"><span class='icalNormal2 iCal-schuballaa2'> Begegnungsstätte Kinder programm</span></span><br/><span style="font-weight: bold; color: white"><span class="icalNormal iCal-schuballaa">In 6 Tagen 17:30-18:00</span></span><span style="font-weight: normal; color: #000000"><span class='icalNormal2 iCal-schuballaa2'> Wüstenrot</span></span><br/><span style="font-weight: bold; color: white"><span class="icalNormal iCal-schuballaa">In 6 Tagen </span></span><span style="font-weight: normal; color: #000000"><span class='icalNormal2 iCal-schuballaa2'> MTX SPRITZE NEHMEN</span></span>`

**on JS iCal table i get This:**
`[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object}`

i think that is why i get olny the entery vacation in Every Folder.

Here is a screenshot:
https://s17.directupload.net/images/190924/93zgmdtl.png

Hope This get be Fixed soon.

**Comment by Cumulus7** [comment]
I have the same problem:
Standard Google Calender url -> only "vacation" entries in events.

![image](https://user-images.githubusercontent.com/45620107/66047114-7d4a0900-e527-11e9-9182-6c15c0a04916.png)

Any way i might help to solve this?

BTW: the html-object is filled correctly:
![image](https://user-images.githubusercontent.com/45620107/66047264-bf734a80-e527-11e9-8a67-5b78b9add523.png)
