### ISSUE TITLE
ical.data.html nicht richtig verschachtelt

### ISSUE THREAD

**Issue by SVallant** [iobroker-community-adapters/ioBroker.ical#12]
Die Termine werden in <span> gepackt, jedoch nicht untereinander sonder "ineinander", 
**es so müsste aussehen:**
```
<span>Termin1</span>
<span>Termin2</span>
<span>Termin3</span>
```
**es ist aber so:**
```
<span>Termin1
  <span>Termin2
    <span>Termin3</span>
  </span>
</span>
```

![grafik](https://cloud.githubusercontent.com/assets/3719598/22864203/4fbef61a-f14d-11e6-9f5d-2f74fa32431e.png)

**Comment by Apollon77** [comment]
Bitte 1.4.0 vom Github testen. Sollte jetzt gefixt sein ... Hoffe hat die ANzeige nicht zerstört ...

**Comment by Apollon77** [comment]
Es ist jetzt so das nur der Tag farblich ist und der Text immer weiss.
