### ISSUE TITLE
json Objekte

### ISSUE THREAD

**Issue by thomke67** [iobroker-community-adapters/ioBroker.ical#120]
Welche Objektnamen werden in der Tabelle genutzt? "location" habe ich gefunden, aber z.B. "description" nicht. Oder anders gefragt, welche Google Kalender Attribute werden unter welchem Objektnamen in die json Tabelle übernommen?

Gruß,
Thomas

**Comment by thomke67** [comment]
Problem noch nicht gelöst!

**Comment by Apollon77** [comment]
Kann es sein das die JSON elemente so aussehen?
https://github.com/iobroker-community-adapters/ioBroker.ical/blob/master/main.js#L478-L492
