### ISSUE TITLE
Wiederholendes Ereignis gelöscht, dennoch im ical 

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.ical#122]
Ein Ereignis, welches sich 4-wöchentlich wiederholt, wird trotz verschieben als Ereignis eingetragen:
Aktuell wurde der Abfuhrtermin Papier um drei Tage verschoben, ical erkennt nicht den händisch verschobenen Termin, das steht ja auch so in der Doku. Also habe ich für den verschobenen Termin einen neuen angelegt. Der wird brav erkannt; der gelöschte jedoch bleibt "im Hinterkopf" (23.12. originaler Termin, 21.12. neuer Termin):
![grafik](https://user-images.githubusercontent.com/34395245/71318072-de7cdb00-248b-11ea-8550-c61aff5efa1a.png)
![grafik](https://user-images.githubusercontent.com/34395245/71318084-ffddc700-248b-11ea-9938-31bc9235da1d.png)

**Comment by Apollon77** [comment]
Duplicate zu #108
