### ISSUE TITLE
Basic auth not working with (some buggy?) iCal Server

### ISSUE THREAD

**Issue by t0mcat1337** [iobroker-community-adapters/ioBroker.ical#126]
Hi everyone,

today I was wondering why ioBroker.ical couldn't receive any ics data from a Kopano Server (a Mail/Calendar/Contact Server) and its ical gateway.
I started debugging things and it came out, that Kopano always answers the ioBroker.ical HTTP Requests with a HTTP Code "401" - "Not Authorized", even I entered valid credentials in the ioBroker.ical Calendar Settings.

After researching have of a day I found the solution as a Basic-Auth issue with Kopano: 
When searching for the authorization header in the HTTP Request Kopano does it case SENSITIVE (and not as the HTTP RFCs mention case INsensitive). 

When building the auth options for the node.js request - module as done in main.js like this:

```
options.auth = {                                                                                                           
  user: user                                                                                                             
  pass: pass                                                                                                             
  sendImmediately: true                                                                                                  
};
```

the node.js request module generates the authorization header lowercase like this:

`authorization: Basic <base64EncodedString>`

In this case, Kopano doesn't find the auth infos, as it searches like this:

`Authorization: Basic <base64EncodedString>`

(Notice the capital "A").

As a quick and dirty Bugfix / Workaround I now create the auth header in main.js manually like this:

```
   if (user) {                                                                                                                    
           let buff = new Buffer.from(user+":"+pass);                                                                                  
           let credB64 = buff.toString('base64');                                                                                      
           options.headers = {                                                                                                         
                'Authorization': "Basic "+credB64                                                                                      
           }                                                                                                                           
                /*                                                                                                                     
            options.auth = {                                                                                                           
                user: user                                                                                                             
                pass: pass                                                                                                             
                sendImmediately: true                                                                                                  
            };*/                                                                                                                       
        }
```
Now ioBroker.ical receives the ics Data from Kopano, everything works again

Should something like this be added to ioBroker.ical ? I don't really know if there are other (buggy) ical/http servers out there...

**Comment by Apollon77** [comment]
Should that not be fixed in that server?! The main question is how many other servers require Lowercase (because maybe also not following standards)

**Comment by t0mcat1337** [comment]
Yes, I'm absolutly with you... this should of course be fixed in that server... but I can't really estimate how long it would take till the fix will be out. And perhaps this hits more than just Kopano...
What about sending both of these headers? One with upper, one with lower case (the latter perhaps generated by request - module the "auth"-way)? Ugly, I know, but - for me - it will technically work...

BTW: did you notice, that the request - module is marked as deprecated (see: https://www.npmjs.com/package/request) ?

**Comment by nils50122** [comment]
> Hi everyone,
> 
> today I was wondering why ioBroker.ical couldn't receive any ics data from a Kopano Server (a Mail/Calendar/Contact Server) and its ical gateway.
> I started debugging things and it came out, that Kopano always answers the ioBroker.ical HTTP Requests with a HTTP Code "401" - "Not Authorized", even I entered valid credentials in the ioBroker.ical Calendar Settings.
> 
> After researching have of a day I found the solution as a Basic-Auth issue with Kopano:
> When searching for the authorization header in the HTTP Request Kopano does it case SENSITIVE (and not as the HTTP RFCs mention case INsensitive).
> 
> When building the auth options for the node.js request - module as done in main.js like this:
> 
> ```
> options.auth = {                                                                                                           
>   user: user                                                                                                             
>   pass: pass                                                                                                             
>   sendImmediately: true                                                                                                  
> };
> ```
> 
> the node.js request module generates the authorization header lowercase like this:
> 
> `authorization: Basic <base64EncodedString>`
> 
> In this case, Kopano doesn't find the auth infos, as it searches like this:
> 
> `Authorization: Basic <base64EncodedString>`
> 
> (Notice the capital "A").
> 
> As a quick and dirty Bugfix / Workaround I now create the auth header in main.js manually like this:
> 
> ```
>    if (user) {                                                                                                                    
>            let buff = new Buffer.from(user+":"+pass);                                                                                  
>            let credB64 = buff.toString('base64');                                                                                      
>            options.headers = {                                                                                                         
>                 'Authorization': "Basic "+credB64                                                                                      
>            }                                                                                                                           
>                 /*                                                                                                                     
>             options.auth = {                                                                                                           
>                 user: user                                                                                                             
>                 pass: pass                                                                                                             
>                 sendImmediately: true                                                                                                  
>             };*/                                                                                                                       
>         }
> ```
> 
> Now ioBroker.ical receives the ics Data from Kopano, everything works again
> 
> Should something like this be added to ioBroker.ical ? I don't really know if there are other (buggy) ical/http servers out there...

I have the same problem.

Can i u tell me which files i need to edit? On the IOBroker Server or on the Kopano Server?
I have 5 instances from iCal-Adapter, 2 with icloud (works fine) + 1 with google calendar (works fine) and now i try to connect to my kopano.
Will the change in the file make the other instances faulty?

**Comment by t0mcat1337** [comment]
> > Hi everyone,
> > today I was wondering why ioBroker.ical couldn't receive any ics data from a Kopano Server (a Mail/Calendar/Contact Server) and its ical gateway.
> > I started debugging things and it came out, that Kopano always answers the ioBroker.ical HTTP Requests with a HTTP Code "401" - "Not Authorized", even I entered valid credentials in the ioBroker.ical Calendar Settings.
> > After researching have of a day I found the solution as a Basic-Auth issue with Kopano:
> > When searching for the authorization header in the HTTP Request Kopano does it case SENSITIVE (and not as the HTTP RFCs mention case INsensitive).
> > When building the auth options for the node.js request - module as done in main.js like this:
> > ```
> > options.auth = {                                                                                                           
> >   user: user                                                                                                             
> >   pass: pass                                                                                                             
> >   sendImmediately: true                                                                                                  
> > };
> > ```
> > 
> > 
> > the node.js request module generates the authorization header lowercase like this:
> > `authorization: Basic <base64EncodedString>`
> > In this case, Kopano doesn't find the auth infos, as it searches like this:
> > `Authorization: Basic <base64EncodedString>`
> > (Notice the capital "A").
> > As a quick and dirty Bugfix / Workaround I now create the auth header in main.js manually like this:
> > ```
> >    if (user) {                                                                                                                    
> >            let buff = new Buffer.from(user+":"+pass);                                                                                  
> >            let credB64 = buff.toString('base64');                                                                                      
> >            options.headers = {                                                                                                         
> >                 'Authorization': "Basic "+credB64                                                                                      
> >            }                                                                                                                           
> >                 /*                                                                                                                     
> >             options.auth = {                                                                                                           
> >                 user: user                                                                                                             
> >                 pass: pass                                                                                                             
> >                 sendImmediately: true                                                                                                  
> >             };*/                                                                                                                       
> >         }
> > ```
> > 
> > 
> > Now ioBroker.ical receives the ics Data from Kopano, everything works again
> > Should something like this be added to ioBroker.ical ? I don't really know if there are other (buggy) ical/http servers out there...
> 
> I have the same problem.
> 
> Can i u tell me which files i need to edit? On the IOBroker Server or on the Kopano Server?
> I have 5 instances from iCal-Adapter, 2 with icloud (works fine) + 1 with google calendar (works fine) and now i try to connect to my kopano.
> Will the change in the file make the other instances faulty?

You have to change the "main.js" of this ioBroker.ical module. As I said, this is just a quick and dirty workaround that technically just works with the buggy ical Gateway of Kopano.
In case google and icloud respect RFC according to the case (in)sensitiveness of the auth header (which I would assume) I don't think that this would break connections to them.

But notice the commit at Kopano GitHub ... if I understand correctly, this bug is resolved in Kopanocore 8.7.12

**Comment by nils50122** [comment]
> > > Hi everyone,
> > > today I was wondering why ioBroker.ical couldn't receive any ics data from a Kopano Server (a Mail/Calendar/Contact Server) and its ical gateway.
> > > I started debugging things and it came out, that Kopano always answers the ioBroker.ical HTTP Requests with a HTTP Code "401" - "Not Authorized", even I entered valid credentials in the ioBroker.ical Calendar Settings.
> > > After researching have of a day I found the solution as a Basic-Auth issue with Kopano:
> > > When searching for the authorization header in the HTTP Request Kopano does it case SENSITIVE (and not as the HTTP RFCs mention case INsensitive).
> > > When building the auth options for the node.js request - module as done in main.js like this:
> > > ```
> > > options.auth = {                                                                                                           
> > >   user: user                                                                                                             
> > >   pass: pass                                                                                                             
> > >   sendImmediately: true                                                                                                  
> > > };
> > > ```
> > > 
> > > 
> > > the node.js request module generates the authorization header lowercase like this:
> > > `authorization: Basic <base64EncodedString>`
> > > In this case, Kopano doesn't find the auth infos, as it searches like this:
> > > `Authorization: Basic <base64EncodedString>`
> > > (Notice the capital "A").
> > > As a quick and dirty Bugfix / Workaround I now create the auth header in main.js manually like this:
> > > ```
> > >    if (user) {                                                                                                                    
> > >            let buff = new Buffer.from(user+":"+pass);                                                                                  
> > >            let credB64 = buff.toString('base64');                                                                                      
> > >            options.headers = {                                                                                                         
> > >                 'Authorization': "Basic "+credB64                                                                                      
> > >            }                                                                                                                           
> > >                 /*                                                                                                                     
> > >             options.auth = {                                                                                                           
> > >                 user: user                                                                                                             
> > >                 pass: pass                                                                                                             
> > >                 sendImmediately: true                                                                                                  
> > >             };*/                                                                                                                       
> > >         }
> > > ```
> > > 
> > > 
> > > Now ioBroker.ical receives the ics Data from Kopano, everything works again
> > > Should something like this be added to ioBroker.ical ? I don't really know if there are other (buggy) ical/http servers out there...
> > 
> > 
> > I have the same problem.
> > Can i u tell me which files i need to edit? On the IOBroker Server or on the Kopano Server?
> > I have 5 instances from iCal-Adapter, 2 with icloud (works fine) + 1 with google calendar (works fine) and now i try to connect to my kopano.
> > Will the change in the file make the other instances faulty?
> 
> You have to change the "main.js" of this ioBroker.ical module. As I said, this is just a quick and dirty workaround that technically just works with the buggy ical Gateway of Kopano.
> In case google and icloud respect RFC according to the case (in)sensitiveness of the auth header (which I would assume) I don't think that this would break connections to them.
> 
> But notice the commit at Kopano GitHub ... if I understand correctly, this bug is resolved in Kopanocore 8.7.12

Can you tell me where i can find the file?

**Comment by nils50122** [comment]
?

**Comment by t0mcat1337** [comment]
`<iobrokerInstallDir>/node_modules/iobroker.ical/main.js`
is the file...

But when the Adapter gets updated, the changes are gone, then u have to do them again.
