### ISSUE TITLE
ical.0.data.trigger  Commands to iCal keine Funktion

### ISSUE THREAD

**Issue by jogicom** [iobroker-community-adapters/ioBroker.ical#13]
Kommandos ueber den state `ical.0.data.trigger`  funktionieren nicht .

iCal Adapter zeigt keine Reaktion auf `read,start,stop,check`

**Comment by Apollon77** [comment]
Implementiert ist aktuell nur "read" und "check". Was sagt das Log (loglevel "info") wenn "read" oder "check" versucht wird?
