### ISSUE TITLE
ical. 1.7.0 fehlerhafte Terminanzeige

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.ical#132]
Bei Serienterminen, werden die zukünftigen Termine, die gelöscht wurden, weiterhin angezeigt.

**Comment by Apollon77** [comment]
Bitte das file bzw relevanten Termin hier bereitstellen.

**Comment by buanet** [comment]
So wie in issue #108?

**Comment by senger1985** [comment]
Ja, wie in #108 
"data"->"count" steht aber auch auf "0" und unter "events" ist der Termin auch nicht auffindbar.

**Comment by Hans-Zwiesel** [comment]
> 
> 
> Bei Serienterminen, werden die zukünftigen Termine, die gelöscht wurden, weiterhin angezeigt.

Ist bei mir auch der Fall:
ical 1.7.0
Im Google Termin einen Serientermin von 09:00 bis 17:00 angelegt, für Di, Do, Sa., jede Woche
von April bis Oktober.
Dann für heute (nur heute) den Termin von 09:00 bis 10:00 geändert.
Das Objekt  "ical.0.events.0.now.Robo_Max"  bleibt aber um 11:00 immer noch auf true.

Den heutigen Termin im Google TP gelöscht, abe im ical ist der weiterhin vorhanden.
Einen neuen Termin für heute von 09:00-10:00 angelegt, aber im ical imer noch 09:00 bis 17:00

@Apollon77 
Brauchst Du noch weitere Infos?
Ich habe ical jetzt erst entdeckt, wenn der funktioniert ist das ein Super Terminplan.
VG

**Comment by steffenj87** [comment]
> Bei Serienterminen, werden die zukünftigen Termine, die gelöscht wurden, weiterhin angezeigt.

Da klinke ich mich doch gleich mit ein. Habe ebenfalls das Problem bei all meinen Google Kalendern, dass sobald ein Termin einer Serie gelöscht, verschoben oder geändert wird, die Änderungen nicht greifen. Es bleiben die alten Termine so bestehen wie nie etwas geändert worden wäre.

Grüße Steffen

**Comment by gidhap** [comment]
Hallo, ich nutze iCal für Abfall und Private Termine, beides sind Nextcloud Kalender. Funktioniert grundsätzlich sehr gut - DANKE für die Arbeit! 
Leider werden jedoch Termine von 0:00 - 0:00 (Geburtstage) am jeweiligenTag nicht mehr angezeigt, nur bis zum Tag vor dem Ereignis. Habe gerade gesehen dass das keine Serientermine sind sondern von Thunderbird wohl als Einzeltermine angelegt werden.

Gestern stand z.B. im Kalender: 
**Morgen 00:00 Geburtstag von Mike, Alter 49"
Morgen 20:15-23:00 Autokino**
Heute steht nur noch drin
**Heute 20:15-23:00 Autokino**
Ich habe dann den Geburtstag mal auf 00:001-02:00 geändert, diese Änderung bekommt er auch nicht mit.
Gruss Karl-Heinz

Nachtrag 7.7.2020 Aktualisierung läuft mittlerweile. Hatte die  URLs nochmal gelöscht, neu angelegt und auch den Broker mal neu gestartet, nicht nur die Instanz. Alles OK

**Comment by Tomscloud** [comment]
Hi @gidhap 
Wie hast du das zum laufen bekommen? Ich versuche das schon seit Tagen, aber die Termine sind in den Obejekten immer leer, bzw auf dem Status flase...

**Comment by wendy2702** [comment]
Hänge ich mich auch mal dran mit Verweis auf das Forum:

https://forum.iobroker.net/topic/35658/ical-liest-termin-der-nicht-mehr-existiert

Habe aktuell wieder einen Termin der in meinem Nextcloud Kalender nicht mehr existiert, auf keinem Gerät angezeigt wird das mit dem Kalender Synchronisiert aber in ICAL steht er immer noch drin.
