### ISSUE TITLE
...filtered out, because does not belongs to specified time interval

### ISSUE THREAD

**Issue by mdn-united** [iobroker-community-adapters/ioBroker.ical#135]
Hi, iCal stopped displaying calendar entries a few days ago. When I increase the log level I see that events are read in, but behind each line is: "...filtered out, because does not belongs to specified time interval". That happens to old and upcoming dates. 
Any idea hot to fix that?

**Comment by mdn-united** [comment]
The last two lines in the log are:
ical.0 (1977) displaying dates because of callback
ical.0 (1977) Terminated (NO_ERROR): Without reason

**Comment by Bernd58** [comment]
Installed today the iCal adapter, connected to gmail-calendar for the trash. Connection from ioBroker to gmail-calendar is successfully and starts reading data. Could see this in log file in debug-mode. Breaks with error message "does not belongs to specified time interval". 
Seems to be same problem as user mdn-united has. Can somebody help with this?

**Comment by funboxbolzer** [comment]
Hello, same issue in my system.
First start works fine and then: (14585) Terminated (NO_ERROR): Without reason

**Comment by Cumulus7** [comment]
Hi,

same problem here: Trash-Calendar with "whole-day" events: all events are filtered out. 

![image](https://user-images.githubusercontent.com/45620107/85532096-b1aea980-b60f-11ea-9621-f86f2ec50e55.png)
