### ISSUE TITLE
Pfeil bei aktuellem Termin

### ISSUE THREAD

**Issue by hail0** [iobroker-community-adapters/ioBroker.ical#138]
Hallo zusammen,

besteht die Möglichkeit, den Pfeil bei einem gerade aktuellen Termin zu entfernen (siehe Anhang)?
![grafik](https://user-images.githubusercontent.com/26676301/80941467-c8d8d400-8de2-11ea-8b65-a2bc0542550b.png)

Ich würde gerne immer die komplette Start- und Endzeit sehen.

Grüße Daniel

**Comment by klein0r** [comment]
Habe dafür einen Pullrequest erstellt und eine neue Option hinzugefügt, welche den Pfeil optional macht
