### ISSUE TITLE
Prozess auf SLAVE wird nicht gestoppt

### ISSUE THREAD

**Issue by LJSven** [iobroker-community-adapters/ioBroker.ical#139]
Ich habe ein Multihost-System (Tinkerboard als Master / Raspberry Pi als Slave) - auf dem Slave läuft die iCal Instanz. 

Manchmal wird diese nicht ordentlich gestoppt ->

![Bildschirmfoto 2020-05-11 um 07 37 19](https://user-images.githubusercontent.com/8560588/81527421-7eaf9f80-935a-11ea-9b60-98b79012978f.png)

Node: 12.16.3
Nodejs: 12.16.3
js-controller: 3.0.20

Ich habe den Eindruck, daß es seit der 3er js-controller Version ist / kann aber auch an Node liegen.

**Comment by LJSven** [comment]
Nach wie vor habe ich das Problem, daß nach einer Zeit der Prozess nicht gestoppt wird. Gibt es vielleicht ein Workaround? Es betrifft mittlerweile nicht mehr den SLAVE - sonder jetzt ist es auf dem Master installiert. Arbeitspeicher ist noch bei 500 MB - da sollte das Problem auch nicht liegen. 

![Bildschirmfoto 2020-06-15 um 09 20 05](https://user-images.githubusercontent.com/8560588/84628747-81695b80-aee9-11ea-9835-ead500831fd4.png)

**Comment by Apollon77** [comment]
Ok, dann schauen wir es doch mal genau an. Bitte instanz im Admin beenden. Dann kommandozeile gehen ins iobroker verzeichnis
Dort
```
node node_modules/iobroker.ical/main.js --debug
```

Und dann mal die Ausgabe hier posten.

**Comment by LJSven** [comment]
Jetzt sofort? Oder
erst wenn das Problem
wieder auftritt? Es kommt
halt nur alle
paar Tage. Kann ich dir das Log
auch anders schicken? Es stehen Daten drin, die nicht für jedermann sind.

**Comment by Apollon77** [comment]
Hm ... ich hatte gedacht das es immer auftritt ... Du kannst manimal regelmäsig starten und ein Log seden wenn er nicht an der Kommandozeile fertig wird.

Senden (es interessieren nur runs die nicht fertig werden!) gern auch per email an iobroker@fischer-ka.de

**Comment by LJSven** [comment]
Wie kann ich sehen, ob ein RUN nicht fertig wird. Also dann wenn er doppelt versucht zu starten, korrekt?

**Comment by Apollon77** [comment]
Naja manuell an der Shell läuft wankend ist dann fertig. Da wird nichts doppelt gestartet. 

Dein Problem ist ja das der Prozess manchmal hängen bleibt oder?!

**Comment by LJSven** [comment]
@Apollon77 Heute war es wieder soweit - ich habe dir die Datei gerade geschickt.
