### ISSUE TITLE
zu viele Einträge im Log

### ISSUE THREAD

**Issue by Hans-Zwiesel** [iobroker-community-adapters/ioBroker.ical#145]
ical Vers. 1.7.0

Es stehen im Log so viele Einträge von iCal mit Quelle "host.raspi4 - Info", so dass das Log total
unübersichtlich wird.
iCal ist mit Log-Stufe "warn" eingestellt.

Bitte, bitte die Log Ausgaben so ändern (info) und als Quelle auch "iCal", damit man sie im Log mit (warn) unterdrücken kann, denn so wird das Log absolut unübersichtlich, die wesentlichen Einträge gehen darin unter.

Vielen Dank!!!

host.raspi4 | 2020-05-14 08:35:25.142 | info | instance _**system.adapter.ical.**_0 terminated with code 0 (NO_ERROR)
host.raspi4 | 2020-05-14 08:35:15.446 | info | instance system.adapter.ical.0 started with pid 19630
host.raspi4 | 2020-05-14 08:35:15.430 | info | instance scheduled system.adapter.ical.0 1,16,31,46 * * * *
host.raspi4 | 2020-05-14 08:35:12.425 | info | stopInstance canceled schedule system.adapter.ical.0
host.raspi4 | 2020-05-14 08:35:12.424 | info | stopInstance system.adapter.ical.0 (force=false, process=false)
host.raspi4 | 2020-05-14 08:08:06.895 | info | instance system.adapter.ical.0 terminated with code 0 (NO_ERROR)
host.raspi4 | 2020-05-14 08:07:57.309 | info | instance system.adapter.ical.0 started with pid 17568
host.raspi4 | 2020-05-14 08:07:57.278 | info | instance scheduled system.adapter.ical.0 * 5,16 * * *
host.raspi4 | 2020-05-14 08:07:54.270 | info | stopInstance canceled schedule system.adapter.ical.0
host.raspi4 | 2020-05-14 08:07:54.269 | info | stopInstance system.adapter.ical.0 (force=false, process=false)
host.raspi4 | 2020-05-14 08:07:51.232 | info | instance system.adapter.ical.0 terminated with code 0 (NO_ERROR)

**Comment by Apollon77** [comment]
Diese Ausgaben kommen vom js-controller und sind daher nicht änderbar. Es ist möglich das Loglevel des js-controller zu ändern
