### ISSUE TITLE
Vergangenheit auswerten

### ISSUE THREAD

**Issue by passuff** [iobroker-community-adapters/ioBroker.ical#152]
Ich nutze den ical Adapter um den Belegnungskalender meiner FeWo auszuwerten. Ein Element was in Abhängigkeit der Belegung gesteuert wird ist der Handtuchwärmer (elektr.). Am Abreisetag ist die Belegung = false aber der Handtuchwärmer sollte dennoch brennen. Mir ist klar, dass man dies auch mit einem Counter in einem zusätzlichen Skript lösen könnte, aber ich würde es dennoch begrüßen, wenn man mit ical auch die Vergangenheit auswerten könnte. Zumindest "Gestern" würde mir sehr weiterhelfen.

**Comment by Baenker** [comment]
@Apollon77 kannst Du hier zu machen? Man kann mittlerweile die Vergangenheit auswerten. Siehe auch 

Merge pull request #185 from klein0r/master
