### ISSUE TITLE
Terminserien Ausnahmen

### ISSUE THREAD

**Issue by ghost** [iobroker-community-adapters/ioBroker.ical#153]
Hallo,

beim Löschen eines Termins aus einer Terminserie wird dieser weiterhin über den Adapter ausgegeben. Lässt sich das ändern?

Viele Grüße
Max

**Comment by Apollon77** [comment]
am besten bitte mal ein minimales ICS File bereitstellen mit so einem Fall, das hier hochladen und am besten auch ein Debug Log vdavon es zu verarbeiten im Adapter

**Comment by ghost** [comment]
> am besten bitte mal ein minimales ICS File bereitstellen mit so einem Fall, das hier hochladen und am besten auch ein Debug Log vdavon es zu verarbeiten im Adapter

Der Debug-Log ist unauffällig. Die Instanz arbeitet die Input-URL einfach ab.

ICS eines gelöschten Termins aus einer Terminserie:

`BEGIN:VALARM
ACTION:NONE
TRIGGER;VALUE=DATE-TIME:19760401T005545Z
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20200530T110000
DTEND;TZID=Europe/Berlin:20200530T120000
EXDATE;TZID=Europe/Berlin:20200620T110000
RRULE:FREQ=WEEKLY
DTSTAMP:20200620T174258Z
UID:8ABAB34B-9F83-4147-B929-98E044982FEE
URL:.....
CREATED:20200529T154159Z
DESCRIPTION:01749447678\n
LAST-MODIFIED:20200620T073557Z
LOCATION:.....
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Tennis
TRANSP:OPAQUE
X-APPLE-STRUCTURED-LOCATION;VALUE=URI;X-APPLE-MAPKIT-HANDLE=.....`

Ich vermute, es hat mit "Sequence:1" zu tun, denn dieser Wert steht bei Terminen einer Serie, die nicht abgesagt/gelöscht wurden, auf "Sequence:0".

**Comment by ldittmar81** [comment]
Hab genau den gleichen Fehler.... Wenn ich ein wiederkehrenden Termin habe, der zum Beispiel jeden Tag ausgeführt wird und ich lösche aus dem Kalender einem der erstellten Termine, so wird es trotzdem ausgeführt. Ich habe hier ein Beispiel für meine Poolpumpe:

```
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20200707T180000
DTEND;TZID=Europe/Berlin:20200707T190000
RRULE:FREQ=DAILY
EXDATE;TZID=Europe/Berlin:20200715T180000
DTSTAMP:20200630T154243Z
UID:xxxxxxxxxxxxxxxxxxxxxxxxxxxx@google.com
CREATED:20200630T154158Z
DESCRIPTION:
LAST-MODIFIED:20200630T154158Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Test Termin
TRANSP:OPAQUE
END:VEVENT

BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20200722T153000
DTEND;TZID=Europe/Berlin:20200722T163000
DTSTAMP:20200630T154243Z
UID:xxxxxxxxxxxxxxxxxxxxxxxxxxxx@google.com
RECURRENCE-ID;TZID=Europe/Berlin:20200722T180000
CREATED:20200630T154158Z
DESCRIPTION:
LAST-MODIFIED:20200630T154225Z
LOCATION:
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Test Termin
TRANSP:OPAQUE
END:VEVENT
```

Hier ist EXDATE im ersten Termin zu beachten... das wäre ein Tag, wo ich den Termin gelöscht habe.

Dann zum zweiten Termin hier... er hat die SEQUENCE 1 und die gleiche UID wie das erste Termin. Das passiert, wenn ich die Uhrzeit eines einzelnen Termins ändere.

**Comment by marios774** [comment]
Hallo,

Ich habe ein ähnliches Problem mit einer Terminserie.
Wenn ich einzelne Termine verschiebe, so bleiben trotzdem die ursprünglichen bestehen.

Beispiel Müllkalender:
Abholung, alle 2 Wochen am Freitag. Bei Feiertagen ggf. Do. oder Sa.
Beim Verschieben (Apple) wird gefragt - nur den Aktuellen oder alle künftigen.

Die Termine werden nur richtig im iCal Adapter verschoben wenn ich alle künftigen auswähle, ansonsten bleiben die auf den ursprünglichen Terminen der Serie bestehen.

**Comment by Apollon77** [comment]
Bitte mit 1.10.3 verifizieren ob noch da oder gelöst

**Comment by Apollon77** [comment]
No answer, Closed
