### ISSUE TITLE
Bekomme ical tasks nicht ans laufen

### ISSUE THREAD

**Issue by gidhap** [iobroker-community-adapters/ioBroker.ical#156]
Hallo, zuerst DANKE für die klasse arbeit mit dem Adapter. Meine Kalender (Nextcloud auf eigenem Server) laufen problemlos per caldav.
Nun möchte ich auch tasks aus meiner nextcloud abgreifen. Ich kann an URL eintragen was ich will, habe eben mangels info verschiedene URLs versucht, es kommen keine Daten der Tasks im iobroker an.
Kann es sein dass der Adapter keine Tasks kann ? (Vielleicht noch keine ;o) ? )

**Comment by jens-maus** [comment]
Klar kann der keine Tasks, steht ja auch nirgends das er welche können muss oder supportet. Insofern ist das momentan eben so...
