### ISSUE TITLE
terminated with code 1 - es werden keine Daten gelesen

### ISSUE THREAD

**Issue by Shadow605** [iobroker-community-adapters/ioBroker.ical#160]
Hallo,

Kann mir jemand diese Fehlermeldung übersetzen?

instance system.adapter.ical.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

Danke

**Comment by Apollon77** [comment]
Hast du mehr log? Starte mal im debug Modus.

**Comment by Shadow605** [comment]
host.raspberrypi | 2020-08-25 19:34:51.487 | error | instance system.adapter.ical.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.raspberrypi | 2020-08-25 19:34:51.005 | info | instance system.adapter.ical.0 started with pid 14601
host.raspberrypi | 2020-08-25 19:34:50.991 | info | instance scheduled system.adapter.ical.0 0,30 * * * *
host.raspberrypi | 2020-08-25 19:34:47.976 | info | stopInstance canceled schedule system.adapter.ical.0
host.raspberrypi | 2020-08-25 19:34:47.973 | info | stopInstance system.adapter.ical.0 (force=false, process=false)

--------------------------------
Mehr steht im Log nicht der Rest ist von anderen Modulen.

Da ich mich erst seit drei Tage mit IoBroker auf dem Raspi4b beschäftige bin ich da noch nicht so fit.

Wo finde ich den debug Modus?

Danke für die schnelle Antwort.

**Comment by Apollon77** [comment]
Debug : Instanzen - expertenmodus - Spalte logstufe

**Comment by Apollon77** [comment]
ical ist am Ende ein schedules Adapter der zu den genannten Zeiten läuft.

**Comment by Shadow605** [comment]
Danke, hatte es schon gefunden...

aber es kommen keine anderen Log einträge


host.raspberrypi | 2020-08-25 20:30:00.555 | error | instance system.adapter.ical.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.raspberrypi | 2020-08-25 20:30:00.045 | info | instance system.adapter.ical.0 started with pid 20954


Sieht für mich so aus als wenn der Adapter garnicht richtig startet.

Hab schon diverse Module deaktiviert / deinstalliert und das Modul neu Installiert.
Und auch andere Kalender ICal Links getestet. Ich möchte gerne Google Kalender zum laufen bringen. Habe aber auch öffentliche ICal getestet mit Schulferien.org läuft aber auch nicht.

**Comment by Apollon77** [comment]
Ok. Orte mal manuell an kommandozeile starten 

iobroker debug ical 

Was kommt als Ausgabe?

**Comment by Apollon77** [comment]
Der Grund scheint eine kaputte dep zu sein ... https://github.com/jakubroztocil/rrule/issues/416

Wir releasen später heute eine fix Version ...

**Comment by Apollon77** [comment]
1.7.3 fixt das. die kommt im laufe des Tages im Admin. Oder Github installieren

**Comment by Apollon77** [comment]
1.7.4 finally fixes it

**Comment by zaphod2** [comment]
Hey,
ich habe hier seid gestern "instance system.adapter.yr.0 terminated with code 1 (JS_CONTROLLER_STOPPED)" und ich bekomme es einfach nicht gelöst.
IoB läuft auf einer Proxmox CT alle Adapter sich auf dem neuesten Stand.

**Comment by Apollon77** [comment]
DieenmAsugabe heisst da ser fertig iost .... also was genau ist das issue? (und ein posting in einem über 1 Jahr geschossenen IOssue ist nicht sonderlich sinnvoll oder?!) Debug Log bitte aktivieren dann siehst Du was er verarbeitet. Sonst neues issue bitte
