### ISSUE TITLE
Version 1.7.3 ließt den Kalender 9x

### ISSUE THREAD

**Issue by moelski** [iobroker-community-adapters/ioBroker.ical#164]
Moin !
Habe gerade auf 1.7.3 ein Update gemacht. Leider ließt der Adapter den Kalender jetzt 9x. 
Das führt zu ziemlich unbrauchbaren Auswertungen ...
![firefox_N89fnYAvhf](https://user-images.githubusercontent.com/17078960/91295386-4d3cd180-e79b-11ea-976f-26b8f8ef111c.png)

![firefox_plL3gJ8Ys4](https://user-images.githubusercontent.com/17078960/91295423-5af25700-e79b-11ea-885a-388fece8b1f9.png)

Hoffe ihr könnt das fixen. Sonst droht die Regierung wieder mit Vergeltung :)

Hier noch der Link zu meinem Forumsbeitrag zu dem Thema: 
https://forum.iobroker.net/topic/36261/ical-terminated-with-code-1-js_controller_stopped

Grüße

**Comment by DutchmanNL** [comment]
Functionality broken between 1.7.0 and 1.7.3, end-users on stable repo don't have this issue and today we pushed a forced update from 1.7.0 to 1.7.3 https://github.com/iobroker-community-adapters/ioBroker.ical/commit/d5e123a4c2eae3bc2d0e08577cc986621a280cfb

By that all current installation are effected, internal message send to Core Team

Related to https://github.com/iobroker-community-adapters/ioBroker.ical/issues/129

**Comment by foxriver76** [comment]
Debug log would be helpful

**Comment by Apollon77** [comment]
1.7.4
