### ISSUE TITLE
Datenpunkte in der Zusammenfassung bleiben leer

### ISSUE THREAD

**Issue by Siggi0904** [iobroker-community-adapters/ioBroker.ical#165]
Die Datenpunkte unter ical.0.data.* bleiben leer.
Ich habe für Hute z.B. das Event Urlaub auf true.

Dies betrifft die Datenpunkte:
- ical.0.data.count
- ical.0.data.countTomorrow
- ical.0.data.html
- ical.0.data.table
- ical.0.data.text

Des Weiteren sind immer alle Datenpunkte im Ordner ical.0.events.0.later auf false.
Bei now, today und den folgenden Tagen passt alles.

Ich nutze im IOBroker die aktuelle stable 1.7.4.

**Comment by klein0r** [comment]
Hast Du bei dem Event "Urlaub" dann auch den Haken "anzeigen" gesetzt? Ansonsten werden treffende Events gefitert.

**Comment by Siggi0904** [comment]
Hi,
ach dafür ist die Einstellung. Ich wusste nicht, was "anzeigen" bedeutet.
Deshallb hatte ich es leer gelassen.
Dann mach ich hier wieder zu.

Großen Dank.
