### ISSUE TITLE
Durcheinander bei Geburtstagen / vergangene Termine werden angezeigt

### ISSUE THREAD

**Issue by little0tiger** [iobroker-community-adapters/ioBroker.ical#175]
Hallo,

ich habe seit einiger Zeit das Problem, dass zurückliegende Geburtstage als zukünftige Termine angezeigt werden.
Ich nutze Google als Kalendergrundlage. Für den 01.10. wird mir bspw. ein Geburtstag vom 01.05. angezeigt.
Es handelt sich um ganztägige Serientermine.
Ich habe aber auch diese Serie testweise auf eine Uhrzeit von 10-10 Uhr angelegt.
Auch dann wird dieser Termin am 01.10. angezeigt, allerdings mit 8.00 Uhr.

Ich habe den Kalender schon exportiert und einen neuen angelegt und die Daten dort importiert. Das Ergebnis  bleibt gleich.
Was kann ich zur Fehleridentifizierung noch beitragen?

Gruß
Patrick

**Comment by Apollon77** [comment]
Bitte wenns geht ein ICS File mal attachen oder posten mit einem beispiel woes schieff geht

**Comment by PrinzEisenherz1** [comment]
Hi Apollon, Ich habe das selbe Problem das die Geburstage in den Versionen ab 1.8.x nicht mehr passen.
Ich hänge hier mal einen export vom Geburstagskalender mit an. Vielleicht hilft das.

Gruß
Johnny
[Geburtstagskalender@group.calendar.google.com.ics.zip](https://github.com/iobroker-community-adapters/ioBroker.ical/files/5769927/Geburtstagskalender%40group.calendar.google.com.ics.zip)

P.S. Bei Version 1.7.4 ist alles i.O.

**Comment by PeddaBO** [comment]
Hänge  mich mal in diesem Thema mit an.

Seit der Version 1.8.2. werden bei der Auswertung der Vergangenen Termine nur noch Ganztägige Termine angezeigt. 
Beim Downgrade auf Version 1.8.1 werden dann sofort wieder vergangene Termine mit Uhrzeit mit Angezeigt. 

Wäre schön das bei einer Kommenden Version, wieder angezeigt wird oder dieses Einstellbar ist.
