### ISSUE TITLE
Termine Dopelt falscher Tag

### ISSUE THREAD

**Issue by Henny4184** [iobroker-community-adapters/ioBroker.ical#179]
Woran kann es liegen wenn im Kalender Heute Frühschicht steht der auch morgen drin. Steht heute Nachtschicht steht auch morgen nachtschicht drin. Obwohl frei ist. Wieso Termin von heute auch Frühschicht Termin morgen. Dieses Problem hatte ich sonst nie da lief es ohne Probleme. Hat jemand ähnliche Probleme und kann helfen?

**Comment by klein0r** [comment]
Bitte die iCal-Datei mit hochladen

**Comment by Henny4184** [comment]
Scheint als gelöst muss mit der  Zeitumstellung zu tun gehabt haben. 1-2 Tage später ging es wieder normal.
