### ISSUE TITLE
Seit heute Fehlermeldungen im Log

### ISSUE THREAD

**Issue by mediaDS** [iobroker-community-adapters/ioBroker.ical#183]
**Describe the bug**  

Seit heute Fehlermeldungen im Log.

**Screenshots & Logfiles**  
Alle 30 Minuten (per CRON eingestellt

`2020-11-06 09:00:13.382 | error | instance system.adapter.ical.0 terminated with code 1 (JS_CONTROLLER_STOPPED)`

Bei manuellem Neustart:

```
host.Casper | 2020-11-06 09:43:18.582 | error | instance system.adapter.ical.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.Casper | 2020-11-06 09:43:17.760 | info | instance system.adapter.ical.0 started with pid 22510
host.Casper | 2020-11-06 09:43:17.640 | info | instance scheduled system.adapter.ical.0 0,30 * * * *
host.Casper | 2020-11-06 09:43:14.572 | info | stopInstance canceled schedule system.adapter.ical.0
host.Casper | 2020-11-06 09:43:14.551 | info | stopInstance system.adapter.ical.0 (force=false, process=false)

```

**Versions:**  
 - Adapter version: 1.7.4
 - JS-Controller version: 3.1.6
 - Node version:  12.19.0
 - Operating system: Linux Arm64

**Comment by Apollon77** [comment]
DIe sind schon immer so die Logs

**Comment by mediaDS** [comment]
Tolle Antwort. Hilft ungemein. Aber warum ein fettes rotes "error" im log, wenn doch alles in Ordnung ist?

**Comment by Apollon77** [comment]
Dieser Fehler kann passierenwenn die Schedule geändert wird weil der Adapter dann gestoppt wird und das vom Js.controller. Sollte nur einmalig gekommen sein oder? Wenn dauerhaft dann bitte mal log erweitern.

**Comment by mediaDS** [comment]
> Dieser Fehler kann passierenwenn die Schedule geändert wird weil der Adapter dann gestoppt wird und das vom Js.controller. Sollte nur einmalig gekommen sein oder? Wenn dauerhaft dann bitte mal log erweitern.

Es wurde nichts verändert - die Fehlermeldung kamen im Log **alle 30 Minuten** "aus blauem Himmel", wie man so schön sagt. Nach dem Update des Admin Adapters auf 4.1.10 heute morgen hörten die Fehlermeldungen auf. Ich bin leider kein Programmierer, so das ich da über Wechselwirkungen der Adapter nichts sagen kann. So wie es aussieht, ist der Fehler durch die Aktualisierung behoben. Ich werde es weiter beobachten. Es handelt sich übrigens um den Abfallkalender mit regelmäßigen Terminen bis Januar.

**Comment by Apollon77** [comment]
Ok, irgendetwas hat das Objekt geändert ... Das ist der einzige Grund warum der Schedule neu gesetzt wird. Sehr strange. AN sich ändert nichts an Objekten rum :-)
