### ISSUE TITLE
V1.7.5  Termine bekommen eine Uhrzeit und einen Pfeil

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.ical#186]
Kalendereintrag: 
![grafik](https://user-images.githubusercontent.com/34395245/98580456-47e22400-22c0-11eb-96b7-44f4552e7e1f.png)

Der Pfeil wird vorangestellt und Uhrzeiten hinterlegt, obwohl im Google-Kalender keine Uhrzeit hinterlegt ist
Version 1.7.5:

&#8594; 09.11.2020 00:00 Restmüll 
16.11.2020   Biomüll 
23.11.2020 01:00-00:00 Papier 
30.11.2020   Biomüll 
03.12.2020   Gelbe Tonne 
07.12.2020 01:00-00:00 Restmüll 
14.12.2020   Biomüll 
21.12.2020 01:00-00:00 Papier 
28.12.2020   Biomüll 
31.12.2020   Gelbe Tonne 
04.01.2021 01:00-00:00 Restmüll 

Version 1.7.4:

09.11.2020   Restmüll 
16.11.2020   Biomüll 
23.11.2020   Papier 
30.11.2020   Biomüll 
03.12.2020   Gelbe Tonne 
07.12.2020   Restmüll 
14.12.2020   Biomüll 
21.12.2020   Papier 
28.12.2020   Biomüll 
31.12.2020   Gelbe Tonne 
04.01.2021   Restmüll

**Comment by jens-maus** [comment]
Bitte entsprechde Auszüge der .ics/.ical Dateien hier unterlegen um das Problem besser debuggen zu können.

**Comment by guergen1** [comment]
> 
> 
> Bitte entsprechde Auszüge der .ics/.ical Dateien hier unterlegen um das Problem besser debuggen zu können.

Jetzt schreibst Du böhmische Dörfer.... Was genau möchtest Du; bzw. wie komme ich da dran :-)
Brauchst Du die öffentliche Kalenderadresse?
https://calendar.google.com/calendar/ical/pb49l4pp5dbnaf5cm1gvd8svoc%40group.calendar.google.com/public/basic.ics
https://calendar.google.com/calendar/embed?src=pb49l4pp5dbnaf5cm1gvd8svoc%40group.calendar.google.com&ctz=Europe%2FBerlin
