### ISSUE TITLE
Update vom 14.11.

### ISSUE THREAD

**Issue by Dragon0501** [iobroker-community-adapters/ioBroker.ical#187]
Im Rahmen dieses Updates ist die Möglichkeit entstanden auch vergangene Termine anzuzeigen. Bitte baut eine Möglichkeit ein, dieses abzustellen. Ich möchte nur laufende und zukünftige Termine sehen. So wie es in der 1.7.5 war. Dankeschön!

**Comment by Apollon77** [comment]
Der Defaut wert für die Vergangenheit ist "0", also keine ... tut das etwa nicht?

**Comment by Feuer-sturm** [comment]
@Apollon77 Ich glaub es gibt noch einen kleinen Bug.

Der Wert für "Vergangene Tage" ist bei mir auch mit 0 eingestellt.

Wenn ich für gestern einen ganztägigen Termin anlege, welcher jährlich wiederholt wird, dann wird der Termin fälschlicherweise mit dem heutigen statt gestrigen Datum angezeigt und es wird auch der Datenpunkt gesetzt, dass gestern ein Termin stattgefunden hat.

Aufgefallen ist dies bei mir im Geburtstagskalender, dass mir heute ein Geburtstag angezeigt wurde, der gestern war.

![grafik](https://user-images.githubusercontent.com/25422320/99197009-e58d9580-278f-11eb-8589-3e5e1a0c5891.png)
![grafik](https://user-images.githubusercontent.com/25422320/99197019-f807cf00-278f-11eb-8b10-f6bd669d8ccf.png)

ical.1.data.text: 
`&#8594; 15.11.2020 00:00 test müll 19.11.2020   Restmüll .....`

**Comment by Apollon77** [comment]
@klein0r  Any idea?

**Comment by Dragon0501** [comment]
Die abgelaufenen Termine des aktuellen Tages werden mit negativen Stundenzahlen angezeigt.

**Comment by Feuer-sturm** [comment]
Das konnte ich bei mir noch nicht beobachten. Hast du das Verhalten bei allen Terminen oder bei welchen Terminen tritt das auf @Dragon0501 ?

**Comment by Dragon0501** [comment]
Was meinst du mit welchen Terminen? Habe Schichtdienst. Hatte Sonntag Frühdienst und nachmittags stand dort Frühdienst und -9std

**Comment by Dragon0501** [comment]
Das hier bekomme ich mit Anzahl Tage 0
![Screenshot 2020-11-16 at 13 55 15](https://user-images.githubusercontent.com/59663011/99255242-eff17300-2813-11eb-89d5-7ecaae5f40c3.png)

**Comment by Dragon0501** [comment]
Mein Frühdienst ist seit ner Stunde vorbei...

**Comment by klein0r** [comment]
Wo ist denn nun genau der Fehler? Werden Termine von gestern auch angezeigt? Oder nur bereits beendete Termine von heute?

**Comment by jens-maus** [comment]
@klein0r Bei mir passiert genau das selbe: Der Fehler ist doch deutlich zu sehen, da steht "Noch **-1** Stunden". Aber sobald man <0 erreicht sollte der Termin komplett aus der Anzeige natürlich verschwinden. So war das in der Tat vorher der Fall.

**Comment by Dragon0501** [comment]
Wie jens-maus sagte. Termine von heute werden angezeigt obwohl sie bereits abgelaufen sind.

**Comment by klein0r** [comment]
Ok, also konnte das Verhalten von @Feuer-sturm sonst niemand nachvollziehen?
Gut, dann schaue ich mir das heute Abend mal an.

**Comment by gitbreiti** [comment]
Bei mir werden jährliche Termine plötzlich auch falsch angezeigt. Wenn heute: "Morgen Max Mustermann" ausgegeben wird, bekomme ich am nächsten Tag: "Noch 1 Tag Max Mustermann" angezeigt. 

Edit:

Also "falsch" stimmt so nicht. Allerdings finde ich es so verwirrend. Vorher wurde "Heute Max Mustermann" angezeigt, fand ich besser so. Oder kann man das wieder so einstellen?

**Comment by PrinzEisenherz1** [comment]
Ich habe das selbe Problem. Heute sollte ein Geburtstag gemeldet werden aber im Datenpunkt steht "Noch 2 Tage Mustermann hat Geburstag".
Wenn ich auf Version 1.7.4 zurückgehe dann ist alles i.O.

**Comment by gitbreiti** [comment]
Jup, heute steht bei mir auch "Noch 1 Tag Max Mustermann" drin. Der Geburtstag war gestern.
Bin jetzt auch zu Version 1.7.4 zurück.

**Comment by klein0r** [comment]
So, mit dem neuen Pull-Request sollte alles funktionieren. Hier mein Test-Kalender:

![Screenshot 2020-11-20 at 16 54 08](https://user-images.githubusercontent.com/1959049/99820420-0ae42000-2b51-11eb-9d6b-8174feeb2669.png)

Daraus folgt diese HTML-Ansicht:

![Screenshot 2020-11-20 at 16 54 54](https://user-images.githubusercontent.com/1959049/99820567-3ff07280-2b51-11eb-8c94-288f00ecbf71.png)

Mit pastDays 2 dann diese:

![Screenshot 2020-11-20 at 16 56 37](https://user-images.githubusercontent.com/1959049/99820672-5e566e00-2b51-11eb-9960-d18727e9a4a1.png)

Jetzt könnte man noch überlegen, ob man für "gestern" und "vorgestern" noch Worte verwendet (falls Option aktiv)

**Comment by Apollon77** [comment]
checke und release ich heute abend ! Danke

**Comment by klein0r** [comment]
@Apollon77 Wie fit bist Du in Unit tests mit nodejs? Würde das gerne mal umsetzen - das Beispiel hier ist ja prädestiniert dafür

**Comment by Apollon77** [comment]
Der ical Adapter hat schon sehr viel testing ... haben da eher "integration testing" gemacht ... schau mal in die test Folder.

problem ... irgendein change hat die kaputt gemacht und bisher hatte noch keiner Zeit zu schauen warum und fixen. Aber dann wäre da deins mit dabei bzw machbar

**Comment by Apollon77** [comment]
1.8.1 coming soon

**Comment by klein0r** [comment]
Thanks a lot

**Comment by Feuer-sturm** [comment]
@klein0r : Das Verhalten, dass mir ein jährlicher Termin der gestern fällig war auch heute noch angezeigt wird obwohl "Vergangene Tage" auf 0 steht hab ich auch noch in der Version 1.8.1.
Ich würde hierfür nochmal ein neues Ticket aufmachen.

**Comment by gitbreiti** [comment]
Ist bei mir genauso wie bei @klein0r

**Comment by gitbreiti** [comment]
Ist bei mir genauso wie bei @Feuer-sturm

**Comment by Feuer-sturm** [comment]
Ich hab hier https://github.com/iobroker-community-adapters/ioBroker.ical/issues/191 ein neues Ticket angelegt.

**Comment by klein0r** [comment]
Ok, dann bitte hier schließen @Apollon77 
Den anderen Punkt schaue ich mir an
