### ISSUE TITLE
 Abfallkalender wird seit eingen Tagen nicht mehr importiert

### ISSUE THREAD

**Issue by svenp** [iobroker-community-adapters/ioBroker.ical#189]
Hallo, mein Abfallkalender wird seit einigen Tagen nicht mehr direkt von der Website des Entsorgers  importiert. 

Fehlermeldung 
2020-11-16 14:06:32.314  - warn: ical.0 (28164) Error reading from URL "https://www.esg-soest.de/abfallkalender/geseke/Westmauer/herunterladen": null
2020-11-16 14:06:32.314  - warn: ical.0 (28164) Error reading "https://www.esg-soest.de/abfallkalender/geseke/Westmauer/herunterladen": Cannot read URL: "https://www.esg-soest.de/abfallkalender/geseke/Westmauer/herunterladen"

Ein herunterladen der Datei per wget und dann einfügen in ical mit dem absoluten Pfad funktioniert hingegen.

wget  "https://www.esg-soest.de/abfallkalender/geseke/Westmauer/herunterladen"

Erzeugt eine Datei mit dem Namen herunterladen

Diese kann dann dann im ical mit /home/iobroker/herunterladen ohne Fehler importiert werden.

Es wäre schön wenn es wieder ohne diesen shell script Umweg funktionieren würde.

**Comment by klein0r** [comment]
Kann es sein, dass die Seite Aussetzer hat? Hatte gerade auch einen HTTP-Status 500 zurückbekommen und jetzt geht es wieder. Eventuell wurde dadurch auch der Eintrag generiert?

**Comment by svenp** [comment]
Kann sein das es "mal" vorkommt, bei mir ist das eben so das der Fehler ständig vom ical apapter beim abrufen bzw. restart der instanz angezeigt wird. Der wget Abruf funktioniert dann aber. Auch der Import der Datei über den Pfad funktioniert, wber eben nicht direkt aus dem Web.

**Comment by klein0r** [comment]
Scheinbar nutzt der Webserver schon HTTP/2. Eventuell kommt das Request-Modul damit durcheinander.

```
curl -I -X GET https://www.esg-soest.de/abfallkalender/geseke/Westmauer/herunterladen

HTTP/2 200 
date: Sun, 22 Nov 2020 12:28:18 GMT
server: Apache
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
content-disposition: attachment; filename="Abfallkalender_2020.ics"
set-cookie: PHPSESSID=niqv2m4hp10qq24udupeueg349; path=/
content-type: text/calendar;charset=UTF-8
```

**Comment by svenp** [comment]
Warum auch immer, das Problem ist nicht mehr vorhanden.
Der import funktioniert wieder normal direkt von der Webseite
