### ISSUE TITLE
Vergangene sich wiederholende Kalendereinträge werden fälschlicherweise angezeigt

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.ical#191]
Seit der Version 1.8.0 hab ich das verhalten, das zurückliegende Einträge, welche sich wiederholen (z.B. jährlich oder monatlich) fälschlicherweise mit angezeigt werden, obwohl der Wert "Vergangene Tage" auf 0 steht.
Auffällig ist auch, dass auch ein falsches Datum ausgegeben wird wie z.B. der 22.11 für einen Eintrag der am 20.11 eingetragen ist. Im Datenpunkt ical.4.data.table sind bei der 1.8.1 die Datumsstempel korrekt.

Meine Testeinträge im Google Kalender: 
Kalender
![image](https://user-images.githubusercontent.com/25422320/99882310-be1b4a80-2c1f-11eb-8361-d0500c17c25b.png)

**Inhalte der Datenpunkte mit ICAL 1.8.1**

ical.4.data.text
22.11.   test 20.11 wiederholend monatlich am dritten Freitag 
22.11.   test 20.11 jährliche Wiederholung 
21.11.   test 21.11 ganztägig einmalig 

ical.4.data.html
<span style="font-weight: bold; color: white"><span class="icalNormal iCal-Geburtstage_cwp">22.11.  </span> test 20.11 wiederholend monatlich am dritten Freitag</span><br/>

<span style="font-weight: bold; color: white"><span class="icalNormal iCal-Geburtstage_Kontakte cwp">22.11.  </span> test 20.11 jährliche Wiederholung</span><br/>

<span style="font-weight: bold; color: white"><span class="icalNormal iCal-Geburtstage_cwp">21.11.  </span> test 21.11 ganztägig einmalig</span><br/>

ical.4.data.table
javascript.0	2020-11-21 17:17:06.039	info	(488) script.js.Skripte.ical_4_ToHtmlTable: ical4: Heute--test 21.11 ganztägig einmalig
javascript.0	2020-11-21 17:17:06.038	info	(488) script.js.Skripte.ical_4_ToHtmlTable: ical4: 20.11.--test 20.11 jährliche Wiederholung
javascript.0	2020-11-21 17:17:06.037	info	(488) script.js.Skripte.ical_4_ToHtmlTable: ical4: 20.11.--test 20.11 wiederholend monatlich am dritten Freitag

**Inhalte der Datenpunkte mit ICAL 1.7.4**

ical.4.data.text
21.11.   test 21.11 ganztägig einmalig 

ical.4.data.table
javascript.0	2020-11-21 17:27:39.718	info	(488) script.js.Skripte.ical_4_ToHtmlTable: ical4: Heute--test 21.11 ganztägig einmalig
javascript.0	2020-11-21 17:27:39.694	info	(488) Start javascript script.js.Skripte.ical_4_ToHtmlTable
javascript.0	2020-11-21 17:27:38.482	info	(488) Stop script script.js.Skripte.ical_4_ToHtmlTable

ical.4.data.html
<span style="font-weight: bold; color: white"><span class="icalNormal iCal-Geburtstage_cwp">21.11.  </span> test 21.11 ganztägig einmalig</span><br/>

**Comment by Feuer-sturm** [comment]
Auch mit der Version 1.8.2 hab ich das von mir oben beschriebene Fehlerbild

@klein0r Siehst du diese Verhalten auch bei dir auch?

"Vergangene Tage" steht auf 0

![grafik](https://user-images.githubusercontent.com/25422320/100670149-c16caf80-335e-11eb-9db5-08d58c4d0bf7.png)


ical.4.data.text
01.12.   Test 29.11 ganztägig jährlich  <=== ist im Google Kalender am 29.11 eingetragen 
01.12.   S. hat Geburtstag  <=== ist im Google Kalender am 29.11 eingetragen 
01.12.   G. hat Geburtstag <=== ist im Google Kalender am 29.11 eingetragen 
02.12.   Test 30.11 ganztägig jährlich  <=== ist im Google Kalender am 30.11 eingetragen 
01.12.   J. hat Geburtstag <=== ist korrekt


ical.4.data.table
ical4: 01.12.  --J. hat Geburtstag
ical4: 02.12.  --Test 30.11 ganztägig jährlich
ical4: 01.12.  --G. hat Geburtstag
ical4: 01.12.  --S. hat Geburtstag
ical4: 01.12.  --Test 29.11 ganztägig jährlich

**Comment by bergjet** [comment]
Gibt es eine Alternative zu ical? Sieht nicht so aus, als ob der Entwickler hier mitliest.

**Comment by jens-maus** [comment]
@bergjet Klar lesen *die* Entwickler hier mit. Aber du kannst das die selber gerne auch anschauen und reparieren wenn du offensichtlich mehr zeit hast...

**Comment by klein0r** [comment]
Wenn ich Zeit finde, kann ich das gerne mal reproduzieren.

@bergjet Gerne mitentwickeln

**Comment by bergjet** [comment]
@klein0r Mitentwickeln würde niemand hier Freude bereiten. Ich dachte nur, denn in manchen Adapter Foren sieht man da so ein rotes bug Zeichen, da ist man sich dann sicher selbst nichts falsch gemacht zu haben.

**Comment by Feuer-sturm** [comment]
@bergjet Siehst du bei dir das gleiche Fehlerbild?

Der ical Adapter wird ja regelmäßig aktualisiert, was man an den Releases in 2020 sieht aber gerade in der Weihnachtszeit gibt es eher andere Prioritäten 👨‍👩‍👧‍👦🌲🌟 🍪

**Comment by bergjet** [comment]
> @bergjet Siehst du bei dir das gleiche Fehlerbild?
> 
> Der ical Adapter wird ja regelmäßig aktualisiert, was man an den Releases in 2020 sieht aber gerade in der Weihnachtszeit gibt es eher andere Prioritäten 👨‍👩‍👧‍👦🌲🌟 🍪

https://github.com/iobroker-community-adapters/ioBroker.ical/issues/195#issue-752876848
So ist das bei mir.

**Comment by bergjet** [comment]
Der Geburtstag ist heute.
![IMG_0744](https://user-images.githubusercontent.com/4241968/101374732-d1c8e100-38ae-11eb-9f9f-d6c935fee6fd.jpeg)

**Comment by PrinzEisenherz1** [comment]
Bei mir besteht das gleiche Problem. Auch bei der 1.9.0 ist der Bug noch vorhanden.
Siehe [https://forum.iobroker.net/topic/40854/ical-1-9-0-termine-stimmen-nicht?_=1610877825443](url)

Gruß
Johnny

**Comment by christofkac** [comment]
Hi,
ich kann eine Beobachtung hinzufügen:
Bei mir wird ein gestriger Geburtstag heute nur angezeigt, wenn die Einstellung "Start-Endzeiten verbergen" in den Settings aktiv ist.
Wenn diese Option aus ist, sind meine ical Objekte leer (wie es auch sein soll, da aktuell nichts ansteht)
Bis dann
Christof

**Comment by Feuer-sturm** [comment]
Problem ist in der 1.9.3 immer noch vorhanden.

**Comment by bergjet** [comment]
1.9.3 Probleme weiterhin da.

**Comment by nhet** [comment]
Kann ich ebenfalls bestätigen. Bug ist in 1.9.3 weiterhin reproduzierbar.
Termine die gestern (24.5.) ganztägig und jährlich wiederholt werden bleiben nun in der Ansicht stehen und haben nun ein neues Datum (26.5.) bekommen. Auch in diesem Fall ist die Checkbox "Start-Endzeiten verbergen" aktiviert.

**Comment by Feuer-sturm** [comment]
Ich hab heute einmal versucht den Fehler etwas weiter einzugrenzen.
Mit der Version 1.7.4 ist bei mir alles in Ordnung.  Mit der Version 1.7.5 tritt der Fehler zum ersten Mal auf.

Beispiel:
Im Google Kalender welcher von ical 1.7.4 und danach von 1.7.5 eingelesen wird stehen folgende ganztägige Termine welche sich jährlich wiederholen:
21.07.2021 - "Test 2 21.07"
22.07.2021 - Person A hat Geburtstag
24.07.2021 - Person S hat Geburtstag

ical 1.7.4 - i.O.
ical.4.data.count = 1
ical.4.data.countTomorrow =  0
ical.4.data.text = 
22.07.   Person A hat Geburtstag 
24.07.    Person S hat Geburtstag

ical 1.7.5 - n.i.O.
ical.4.data.count = 2
ical.4.data.countTomorrow =  1
ical.4.data.text = 
&#8594; 23.07.   "Test 2 21.07"  -> n.i.O
&#8594; 24.07.   "Person A hat Geburtstag" -> n.i.O
24.07.   "Person S hat Geburtstag"  -> n.i.O

Ich gehe davon aus, dass das Problem in der main.js zu suchen ist. Ich werde mal schauen, welche Änderungen zwischen der 1.7.4 und 1.7.5 gemacht wurden und schauen ob ich den Fehler noch weiter eingrenzen kann.

**Comment by Apollon77** [comment]
Then these should be mainly the changes from @klein0r on 7.11.20 ... I also checked all commits it are:
* node-ical and rrule updates
* https://github.com/iobroker-community-adapters/ioBroker.ical/commit/990faca9eba88d9f7ce8da95baf9b325e12e99b5 (no, only config changes)
* https://github.com/iobroker-community-adapters/ioBroker.ical/commit/490f3edf6d0485077ab4147f83b689901a9a2765 (mainly changes if an arrow is displayed or not)
* https://github.com/iobroker-community-adapters/ioBroker.ical/commit/24a0a47ae72a4d3c11f77e852080c663758d793c (allow to also check past events ... maybe error came in there?)
* https://github.com/iobroker-community-adapters/ioBroker.ical/commit/d23ea0749c801d8271462348e9975fe83d67e6e0 (allow to also check past events part two ... maybe error came in there?)

(and one crash fix from me https://github.com/iobroker-community-adapters/ioBroker.ical/commit/63c3712722f371b957a23fbf03b366f3d7265d7f , but this should it not be)

**Comment by Apollon77** [comment]
@jens-maus It seems that no code change in adapter is the reason but node.ical 0.11 -> 0.12 ... @Feuer-sturm is currently digging it down more exactkly

**Comment by Apollon77** [comment]
So in fact it should be somewhere from

https://github.com/jens-maus/node-ical/pull/18
https://github.com/jens-maus/node-ical/pull/19
https://github.com/jens-maus/node-ical/pull/21

Maybe @jens-maus or @sdetweil have ideas?!

It seems we get cases where dates are wrong by 2 days ... someother by 2h ... @

**Comment by Feuer-sturm** [comment]
I installed ical Adapter 1.7.5 and modified package.json and executed for testing an npm install in /opt/iobroker/node_modules/iobroker.ical

With     "node-ical": "^0.11.3" and "node-ical": "^0.11.4" the above mentioned problem is not there. Withe node-ical >= 0.12.1 there is the mentioned problem.

ical 1.7.5 - with node-ical 0.11.4 - ok
ical.4.data.count = 1
ical.4.data.countTomorrow = 0
ical.4.data.text =
22.07. Person A hat Geburtstag
24.07. Person S hat Geburtstag

ical 1.7.5 - with node-ical 0.12.1 - not ok
ical.4.data.count = 2
ical.4.data.countTomorrow = 1
ical.4.data.text =
→ 23.07. "Test 2 21.07" -> not ok (correct date would be 21.07)
→ 24.07. "Person A hat Geburtstag" -> not ok (correct date would be 22.07)
24.07. "Person S hat Geburtstag" -> ok

**Comment by sdetweil** [comment]
can I see the actual ICS data.. the only place in those 3 commits that time is changed  is the case where the timezone is an offset only and the time is reported as local time. (#18)  I attempt to find a timezone that matches cause the rest of the code is really dependent on having a tz value.. 

```
  // Timezone not confirmed yet
        if (found === '') {
          // Lookup tz
          found = moment.tz.names().filter(zone => {
            return zone === tz;
          })[0];
        }
        // Timezone confirmed or forced to offset
        if (found) {
          newDate = moment.tz(val, 'YYYYMMDDTHHmmss' + offset, tz).toDate();    // <-  here is the change
```

**Comment by Feuer-sturm** [comment]
@sdetweil Hopefully this is what you need.
This is part of an export of the current mentioned birthdays of the google calender. If this is not enough I can create a test calender and add some entrys for testing. Perhaps there is a difference if a calendar entry is made on the phone or in the browser or in the calender of thunderbird


```
SUMMARY:Test 2 21.07
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
DESCRIPTION:This is an event reminder
TRIGGER:-P0DT7H0M0S
END:VALARM
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20210721T080000
DTEND;TZID=Europe/Berlin:20210721T090000
RRULE:FREQ=YEARLY;BYMONTH=7;BYMONTHDAY=21
DTSTAMP:20210722T214222Z
UID:cxxxx68@google.com
CREATED:20210722T130358Z
DESCRIPTION:
LAST-MODIFIED:20210722T181926Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED


DESCRIPTION:A. hat Geburtstag!
LAST-MODIFIED:20191212T213223Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:A. hat Geburtstag
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;VALUE=DATE:20190605
DTEND;VALUE=DATE:20190606
DTSTAMP:20210722T214222Z
UID:2xxxxb@google.com
URL:https://www.gxxxx
CLASS:PUBLIC
CREATED:20191206T020301Z

DESCRIPTION:S. hat Geburtstag!
LAST-MODIFIED:20191212T213223Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:S. hat Geburtstag
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;VALUE=DATE:20190606
DTEND;VALUE=DATE:20190607
DTSTAMP:20210722T214222Z
UID:20xxxx@google.com
URL:https://www.gxxxx
CLASS:PUBLIC
CREATED:20150409T161930Z
```

**Comment by Feuer-sturm** [comment]
@sdetweil I just created a new google calender with the following entries:

![grafik](https://user-images.githubusercontent.com/25422320/126717327-21d86e58-305a-49d2-9097-04e9f24db7b1.png)

I added the dates via webbrowser. This is the ics
[ioBrokerTesting.zip](https://github.com/iobroker-community-adapters/ioBroker.ical/files/6865543/ioBrokerTesting.zip)

This is how it looks like with ical 1.10.1 and     "node-ical": "^0.13.0",
![grafik](https://user-images.githubusercontent.com/25422320/126717621-c99a6e3d-293a-4430-930c-e8414b7d5bbe.png)

This is how it looks like with ical 1.10.1 and     "node-ical": "^0.11.4",
![grafik](https://user-images.githubusercontent.com/25422320/126717888-b578b627-47e9-43c3-8198-98c78a3a4cdd.png)
@klein0r In this case, I don't know why, the arrow is not there for the entrys which are today. The option is activated in ical.5 instance.

**Comment by sdetweil** [comment]
thanks..

i used this little app to parse the ics. 
```
var ical = require('./node-ical.js');
var file = 'ioBrokerTesting.ics';
var info = ical.parseFile(file);
console.log(JSON.stringify(info,null,2));
```
you can run it from the git cloned/npm installed node-ical folder
run like 
```
node testparse.js >somefile
```
with my TZ set to Amsterdam I see 
```
{
  "4mtkkkhi3p0i6ifle9qkph2k20@google.com": {
    "type": "VEVENT",
    "params": [],
    "start": "2021-07-24T00:00:00.000Z",
    "datetype": "date",
    "end": "2021-07-24T22:00:00.000Z",
    "rrule": {
      "_cache": {
        "all": false,
        "before": [],
        "after": [],
        "between": []
      },
      "origOptions": {
        "dtstart": "2021-07-24T00:00:00.000Z",
        "freq": 0
      },
      "options": {
        "freq": 0,
        "dtstart": "2021-07-24T00:00:00.000Z",
        "interval": 1,
        "wkst": 0,
        "count": null,
        "until": null,
        "bysetpos": null,
        "bymonth": [
          7
        ],
        "bymonthday": [
          24
        ],
        "bynmonthday": [],
        "byyearday": null,
        "byweekno": null,
        "byweekday": null,
        "bynweekday": null,
        "byhour": [
          0
        ],
        "byminute": [
          0
        ],
        "bysecond": [
          0
        ],
        "byeaster": null
      }
    },
    "dtstamp": "2021-07-22T22:30:45.000Z",
    "uid": "4mtkkkhi3p0i6ifle9qkph2k20@google.com",
    "created": "2021-07-22T22:20:17.000Z",
    "description": "",
    "lastmodified": "2021-07-22T22:20:17.000Z",
    "location": "",
    "sequence": "0",
    "status": "CONFIRMED",
    "summary": "B-Day P2 24.07",
    "transparency": "TRANSPARENT",
    "method": "PUBLISH"
  },
  "7vsvljkfja32hl6e7lls6i698l@google.com": {
    "type": "VEVENT",
    "params": [],
    "start": "2021-07-22T00:00:00.000Z",
    "datetype": "date",
    "end": "2021-07-22T22:00:00.000Z",
    "rrule": {
      "_cache": {
        "all": false,
        "before": [],
        "after": [],
        "between": []
      },
      "origOptions": {
        "dtstart": "2021-07-22T00:00:00.000Z",
        "freq": 0
      },
      "options": {
        "freq": 0,
        "dtstart": "2021-07-22T00:00:00.000Z",
        "interval": 1,
        "wkst": 0,
        "count": null,
        "until": null,
        "bysetpos": null,
        "bymonth": [
          7
        ],
        "bymonthday": [
          22
        ],
        "bynmonthday": [],
        "byyearday": null,
        "byweekno": null,
        "byweekday": null,
        "bynweekday": null,
        "byhour": [
          0
        ],
        "byminute": [
          0
        ],
        "bysecond": [
          0
        ],
        "byeaster": null
      }
    },
    "dtstamp": "2021-07-22T22:30:45.000Z",
    "uid": "7vsvljkfja32hl6e7lls6i698l@google.com",
    "created": "2021-07-22T22:20:44.000Z",
    "description": "",
    "lastmodified": "2021-07-22T22:26:08.000Z",
    "location": "",
    "sequence": "0",
    "status": "CONFIRMED",
    "summary": "B-Day P0  22.07",
    "transparency": "TRANSPARENT",
    "method": "PUBLISH"
  },
  "3ko9qe4co18qq3omugppqg70v7@google.com": {
    "type": "VEVENT",
    "params": [],
    "start": "2021-07-23T00:00:00.000Z",
    "datetype": "date",
    "end": "2021-07-23T22:00:00.000Z",
    "rrule": {
      "_cache": {
        "all": false,
        "before": [],
        "after": [],
        "between": []
      },
      "origOptions": {
        "dtstart": "2021-07-23T00:00:00.000Z",
        "freq": 0
      },
      "options": {
        "freq": 0,
        "dtstart": "2021-07-23T00:00:00.000Z",
        "interval": 1,
        "wkst": 0,
        "count": null,
        "until": null,
        "bysetpos": null,
        "bymonth": [
          7
        ],
        "bymonthday": [
          23
        ],
        "bynmonthday": [],
        "byyearday": null,
        "byweekno": null,
        "byweekday": null,
        "bynweekday": null,
        "byhour": [
          0
        ],
        "byminute": [
          0
        ],
        "bysecond": [
          0
        ],
        "byeaster": null
      }
    },
    "dtstamp": "2021-07-22T22:30:45.000Z",
    "uid": "3ko9qe4co18qq3omugppqg70v7@google.com",
    "created": "2021-07-22T22:19:55.000Z",
    "description": "",
    "lastmodified": "2021-07-22T22:26:44.000Z",
    "location": "",
    "sequence": "1",
    "status": "CONFIRMED",
    "summary": "B-Day P1  23.07",
    "transparency": "OPAQUE",
    "method": "PUBLISH"
  },
  "1a00iaj3d4gvgk6ot6ghn61pjp@google.com": {
    "type": "VEVENT",
    "params": [],
    "start": "2021-07-23T00:00:00.000Z",
    "datetype": "date",
    "end": "2021-07-23T22:00:00.000Z",
    "rrule": {
      "_cache": {
        "all": false,
        "before": [],
        "after": [],
        "between": []
      },
      "origOptions": {
        "dtstart": "2021-07-23T00:00:00.000Z",
        "freq": 0
      },
      "options": {
        "freq": 0,
        "dtstart": "2021-07-23T00:00:00.000Z",
        "interval": 1,
        "wkst": 0,
        "count": null,
        "until": null,
        "bysetpos": null,
        "bymonth": [
          7
        ],
        "bymonthday": [
          23
        ],
        "bynmonthday": [],
        "byyearday": null,
        "byweekno": null,
        "byweekday": null,
        "bynweekday": null,
        "byhour": [
          0
        ],
        "byminute": [
          0
        ],
        "bysecond": [
          0
        ],
        "byeaster": null
      }
    },
    "dtstamp": "2021-07-22T22:30:45.000Z",
    "uid": "1a00iaj3d4gvgk6ot6ghn61pjp@google.com",
    "created": "2021-07-22T22:27:20.000Z",
    "description": "",
    "lastmodified": "2021-07-22T22:27:36.000Z",
    "location": "",
    "sequence": "0",
    "status": "CONFIRMED",
    "summary": "B-Day P3 23.07",
    "transparency": "TRANSPARENT",
    "method": "PUBLISH"
  }
}
```
all the start dates are correct and match the event labels. 

they are in UTC time now, but that is the same time as local time. 
I agree that end time is incorrect (22:00, not 23:59) , but that shouldn't affect it

**Comment by Apollon77** [comment]
@sdetweil hm ... ok,... got it ... interesting ... then I really need to check the code here that processes this

**Comment by Apollon77** [comment]
Ok, I think with the new parsing we need to kill this conversion ... https://github.com/iobroker-community-adapters/ioBroker.ical/blob/ffdd3d7e01219d6269ed8331929b21da892653f5/main.js#L289-L293 ... and in  https://github.com/iobroker-community-adapters/ioBroker.ical/blob/ffdd3d7e01219d6269ed8331929b21da892653f5/main.js#L324-L331 we need to convert it to local time still ... maybe https://github.com/iobroker-community-adapters/ioBroker.ical/blob/ffdd3d7e01219d6269ed8331929b21da892653f5/main.js#L250-L261 still does the job ?

just collecting ideas here right now :-)

**Comment by sdetweil** [comment]
where is it 2 days off
for the event with uid 4mtkkkhi3p0i6ifle9qkph2k20@google.com
```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20210724
DTEND;VALUE=DATE:20210725
RRULE:FREQ=YEARLY
DTSTAMP:20210722T223045Z
UID:4mtkkkhi3p0i6ifle9qkph2k20@google.com
CREATED:20210722T222017Z
DESCRIPTION:
LAST-MODIFIED:20210722T222017Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:B-Day P2 24.07
TRANSP:TRANSPARENT
END:VEVENT
```
start is 
```
DTSTART;VALUE=DATE:20210724
```
and the parsed date is 
```
  "start": "2021-07-24T00:00:00.000Z",
```

which I actually think is 2 hours off... as I didn't check Amsterdam tz, which is UTC+2
so this should have been 
```
"start": "2021-07-23T22:00:00.000Z",
```
but its only 2 hours,  the client/user of node-ical should still have come up with the correct date (and 02:00 as the time)
the end time is actually correct

**Comment by sdetweil** [comment]
and one other point, in the parsed output is says 
```
 "datetype": "date",
```
so the time is irrelevant

so for 
```
"end": "2021-07-23T22:00:00.000Z",
```
its technically correct, as when its 22:00 the same day, in Amsterdam, it has become day+1 '00:00', and the event is over
starts and ends on the same day

**Comment by Apollon77** [comment]
Bitte mit 1.10.3 verifizieren ob noch da oder gelöst

**Comment by Feuer-sturm** [comment]
Problem ist gelöst mit 1.11.0
