### ISSUE TITLE
Termine werden falsch ausgewertet V1.81

### ISSUE THREAD

**Issue by Baenker** [iobroker-community-adapters/ioBroker.ical#192]
Habe gestern auf die 1.81 ein update gemacht. 

Im google Kalender ist für nächste Woche ein Termin von Mo-Fr ohne Uhrzeit eingetragen.

Ical macht daraus unter events.0.today ein true. Das ist natürlich falsch. Unter event.1-5 steht ebenfalls ein true was richtig ist und unter event.6 ein false was auch passt. Diesen Fehler gab es mit der alten Version nicht. Dort standen ebenfalls die wöchentlichen Termine drin, die richtig umgesetzt werden. Vergangene Termine nutze ich nicht.

Unter data.counts steht ein 0 und count.tomorrow ein true. Was auch passt. Auch unter data.text steht nur ein "Morgen   Homeoffice (Thomas)" was ebenfalls passt.

**Comment by joergeli** [comment]
Ich hänge mich hier mal dran, da ebenfalls ein Problem nach Update von V1.8.0 auf V1.8.1:

Unsere Mülltermine sind im Google-Kalender als **ganztägige einmalige Termine** eingetragen.
Heute ist Abholung von Bio-Müll, morgen Papier.
In der HTML-Tabelle wird es korrekt eingetragen, aber nicht unter ical.1.events.0 (s. Screenshot):
![ical](https://user-images.githubusercontent.com/62521927/99993299-c4dcc580-2db7-11eb-9f28-8291e6f193fb.jpg)
Dort wird bei **ical.1.events.0.later.Papier** und **ical.1.events.0.today.Papier** ebenfalls "true" eingetragen, obwohl der Papier-Termin erst morgen ist, also "false" sein müsste.
Das wird für morgen unter ical.1.events.1.Papier auch korrekt eingetragen.

Wie gesagt, mit der V1.8.0 war es noch in Ordnung.

P.S.
**ical.1.data.count** und **ical.1.data.countTomorrow** werden ebenfalls mit mit jeweils "1" korrekt eingetragen
![ical2](https://user-images.githubusercontent.com/62521927/99995316-78df5000-2dba-11eb-88ad-7831711a3c2e.jpg)

**Comment by Baenker** [comment]
ja genau der Fehler. Anscheinend werden alle Termine Morgen auch schon heute true.

**Comment by paeppi88** [comment]
Genau den gleichen Fehler hab ich auch. Habe fälschlicherweise heute schon die Biotonne rausgestellt. Die Nachbarn waren sehr verunsichert ;) War aber lustig.

**Comment by firepower28** [comment]
Jepp, dem kann ich mich anschliessen.

Genau das gleiche Problem, eigentlich ist Freitag erst die Gelbe Tonne dran. Laut vis soll ich die Tonne heute schon rausstellen :-)

**Comment by bergjet** [comment]
Gibt es dazu schon eine Lösung? Habe auch das Problem. Bin zurück auf 1.7.5, das Problem bleibt aber.

**Comment by Baenker** [comment]
Das Problem tritt nur bei 1.81 auf. Bei allen Vorversionen hatte ich keine Probleme. Bin auf die 1.80 und bei mir passt es wieder

**Comment by bergjet** [comment]
Bei mir betrifft es den Geburtstagskalender deren Daten über Google Kalender kommen. Ich habe das Ereignis für heute auf true, aber der Text sagt mir den Termin für morgen an.

<img width="1538" alt="Bildschirmfoto 2020-11-27 um 10 39 07" src="https://user-images.githubusercontent.com/4241968/100434729-39a44e00-309d-11eb-96b2-d1bcb899dfd7.png">

**Comment by Baenker** [comment]
Das muss dann ein anderes Problem sein!? Mit welcher Version war es denn vorher ok? Was passiert wenn diese installiert wird?

**Comment by bergjet** [comment]
Ob es mit 1.8.1 funktioniert hat kann ich nicht sagen. Da gab es keinen Geburtstag am aktuellen Tag. Habe dann ein ioBroker Backup eingespielt (vom selben Tag, ohne Änderung) und nun wird es falsch angezeigt. Im Google Kalender steht es richtig drinnen. Ein Geburtstag der übermorgen stattfindet stimmt in der Anzeige.

**Comment by klein0r** [comment]
Nur zur Sicherheit: Also sind die Berechnungen und Darstellungen überall korrekt?
Das Problem betrifft nur Events/Ereignisse - soweit richtig?

@bergjet 1.8.2 ? Gibts es doch noch gar nicht?

**Comment by Baenker** [comment]
@klein0r Bei mir zumindest ja. counts usw passt. Lediglich der Datenpunkt events.0.today.xxxx wird bei mir einen Tag vor dem Termin schon mit true befüllt. Endetermin passt.

**Comment by bergjet** [comment]
@klein0r 1.8.2 gibt es noch nicht, habe es korrigiert.
Ich lese nur data/html aus und dort ist das Datum falsch. Dort wo steht "Noch 1 Tag zu Geburtstag" sollte eigentlich heute Geburtstag stehen.

**Comment by Baenker** [comment]
@bergjet das ist aber ein komplett anderer Fehler wie er hier beschrieben wird. Du solltest dazu dann ggf. ein eigene Issue aufmachen. Damit es übersichtlicher wird für die Entwickler... Außer der Fehler kommt aus der gleichen Ecke. Hört sich für mich aber nicht unbedingt so an, da bei mir data.html immer korrekt angezeigt wurde...

**Comment by bergjet** [comment]
> Du solltest dazu dann ggf. ein eigene Issue aufmachen.
Ich werde noch einige Tage abwarten.

**Comment by bergjet** [comment]
> Du solltest dazu dann ggf. ein eigene Issue aufmachen.
Werde ich machen.

**Comment by bergjet** [comment]
> @bergjet das ist aber ein komplett anderer Fehler wie er hier beschrieben wird. Du solltest dazu dann ggf. ein eigene Issue aufmachen. Damit es übersichtlicher wird für die Entwickler... Außer der Fehler kommt aus der gleichen Ecke. Hört sich für mich aber nicht unbedingt so an, da bei mir data.html immer korrekt angezeigt wurde...

Werde ich machen.

**Comment by bergjet** [comment]
Zur Info. Habe die Instanz des Google Kalender gelöscht und neu angelegt, jetzt ist alles richtig mit der 1.8.1

**Comment by firepower28** [comment]
> Jepp, dem kann ich mich anschliessen.
> 
> Genau das gleiche Problem, eigentlich ist Freitag erst die Gelbe Tonne dran. Laut vis soll ich die Tonne heute schon rausstellen :-)


Habe vorher auch mal versucht die alte Instanz zu entfernen und neu einzulesen mit dem gleichen Fehler.
Bin jetzt zur 1.8.0 zurück, da besteht der Fehler nicht.

**Comment by yogiflop** [comment]
Hallo,
gleiche Problematik auch bei mir.
habe mich gerade gewundert, warum Alexa mir einen Tag zu früh sagt, das morgen Müllabfuhr ist. Nach einigen suchen, habe ich bemerkt, das im iCal ein Tag zu früh der entsprechende Wert auf "true" gesetzt wird.
Es handelt sich grundsätzlich um ganztägige Termine. Nach einigem hin- und herinstallieren, habe ich festgestellt, das der Fehler erst in der Version 1.8.1 auftritt. Wenn ich zurück auf die 1.8.0 gehe, funktioniert es wieder.


Version 1.8.0
![](https://forum.iobroker.net/assets/uploads/files/1606234140835-bildschirmfoto-2020-11-24-um-17.08.07-resized.png)

Version 1.8.1
![](https://forum.iobroker.net/assets/uploads/files/1606234240552-bildschirmfoto-2020-11-24-um-17.10.23-resized.png)

Es geht um die "Biotonne" und "Restabfallbehälter".
Die Werte in 1.8.1 Position "today" und "2" sind einen Tag zu früh auf true.

bis denne
Marc

**Comment by klein0r** [comment]
Sollte in der nächsten Version hoffentlich nun endlich alles wieder zuvor laufen. Ich musste mich in den Adapter erstmal einarbeiten - gibt ganz schön viele Datums-Berechnungen 😄  Entschuldigt die Verwirrung.

**Comment by Apollon77** [comment]
1.8.2 goes to npm

**Comment by Apollon77** [comment]
Danke @klein0r !

**Comment by klein0r** [comment]
Wer es kaputt macht, muss es ja auch reparieren, oder? 😭

**Comment by Apollon77** [comment]
:-))))
