### ISSUE TITLE
Wunsch: Events nicht ausschließlich durch Substring-Suche

### ISSUE THREAD

**Issue by BillyRay83** [iobroker-community-adapters/ioBroker.ical#194]
Aktuell wird bei Events nach Substrings gesucht. Könnte man eine Option (Häkchen) pro Event einbauen, ggf. nicht nach einem Substring sondern genau nach diesem String zu suchen?

Vielen Dank

**Comment by klein0r** [comment]
Also so wie im Trashschedule Adapter?

**Comment by BillyRay83** [comment]
Ganz genau. Hier ein kurzes Beispiel:

Über Einträge in ical steuere ich u.a. meine Heizung. Dazu lese ich meinen Firmenkalender aus und steuere z.B. über den ganztägigen Eintrag 'Urlaub', dass die Heizung am entsprechenden Tag erst später anspringt. Gibt es jetzt aber an einem anderen Tag beispielsweise den Termin ‚Urlaubsplanung 2021‘, führt dies dazu, dass die Heizung auch erst später anspringt, da in dem Wort Urlaubsplanung nun mal auch das Event ‚Urlaub‘ steckt.

Die Suche nach Teilstrings mag in bestimmten Situationen durchaus Sinn machen, manchmal ist sie aber nicht zielführend. Deshalb mein Wunsch, eine Möglichkeit zu haben, für jedes Event angeben zu können (z.B. mittels Häkchen), ob nun nur genau dieser String oder halt auch jeder Teilstring das Event auslösen soll (so wie in Trashscheduler).

**Comment by Bart1909** [comment]
+1 für die Idee.
Habe etwas ähnliches gerade.
Ich reagiere auch auf "Urlaub" im Kalender. Nun möchte ich aber auch auf "Urlaub Tobi" abfragen und dann ggf. anders steuern. Wäre also gut, wenn man entweder ausschalten kann, dass ein Substring gesucht wird oder ggf. sogar so bauen, dass man RegEx angeben kann. Das wäre vermutlich noch variabler

**Comment by Apollon77** [comment]
@Bart1909 Dann mach mak ein Thumbs up im ersten Post bitte

**Comment by christofkac** [comment]
Ich hätte hier noch einen kleinen Wunsch, wenn man eh an das Thema rangeht.
Kann man auch eine Option hinzufügen, um die Groß-/Kleinschreibung zu ignorieren?
Ich hatte letztens den Fall, dass ich im Kalender Urlaub_abwesend eingetragen hatte, mein Schlüsselwort aber Urlaub_Abwesend ist. Somit wurde der Event nicht gesetzt.

**Comment by BillyRay83** [comment]
Meines Erachtens besteht der Wunsch noch und es wäre schade, wenn das Problem geschlossen würde.
