### ISSUE TITLE
HTML Anzeige stimmt nicht

### ISSUE THREAD

**Issue by bergjet** [iobroker-community-adapters/ioBroker.ical#195]
ical Adapter 1.8.1
Heute am 29.11. zeigt der Count 1 an, das ist richtig, es gibt heute einen Geburtstag.
Im HTML Datenpunkt wird aber der Geburtstags Termin für den 30.11. angezeigt.

**Comment by Parodontitis** [comment]
Ist in der 1.8.2 Version immer noch so.
`&#8594; 06.12.   John  &#8594; 07.12.   Heike 06.12.   Claus 09.12.   Mama`

wobei Heike schon am 05.12. Geburtstag hatte.

**Comment by bergjet** [comment]
Hat sich nicht geändert.

**Comment by Parodontitis** [comment]
Still buggy here.

**Comment by PrinzEisenherz1** [comment]
Bug besteht auch in 1.9.3 immer noch

Gruß
Johnny

**Comment by bergjet** [comment]
Auch bei mir. Schade.

**Comment by Parodontitis** [comment]
Fehler immer noch vorhanden.

Bug still exists.

**Comment by Apollon77** [comment]
Bitte mit 1.10.3 verifizieren ob noch da oder gelöst

**Comment by Parodontitis** [comment]
Im Moment sieht es gut aus. Allerdings muss tritt das Problem erst einen Tag **nach** einem abgelaufenen Termin. Da ich aber gestern einen Termin hatte und der Fehler heute nicht angezeigt wird, gehe ich vorerst davon aus, dass das Problem behoben ist.

Ich bin ab heute Abend im Urlaub und werde erst nach dem Urlaub genauer berichten können. 

P.S. Danke!

**Comment by Apollon77** [comment]
No answer, Closed
