### ISSUE TITLE
Termine über 0 Uhr lösen kein Event aus

### ISSUE THREAD

**Issue by pjo12345** [iobroker-community-adapters/ioBroker.ical#20]
Wenn ein Termin z.B.: von 20:00 Uhr bis 1:00 Uhr am nächsten Tag geht, wird dieser Termin zwar bei den Objekten unter ical/data angezeigt aber kein Event wird "ausgelöst". 
Anbei ein paar Screenshots (Event: Test):
Bild 1: Termin von 20-22 Uhr
Bild 2: Termin bei Objekten
Bild 3: Termin geändert auf 20 bis 1 Uhr (nächster Tag) 
Bild 4: geänderter Termin bei Objekten -- jetzt steht da nur noch 20:00 Uhr Test (kein bis Zeit???)
Dieser Termin löst auch das Event nicht aus.

**## EDIT: Nach nochmaligen Testen sieh es jetzt so aus, dass Termin von vor 0 Uhr bis nach 0 Uhr (18 bis 1 Uhr)  funktionieren. Aber Termine bis genau 0 Uhr (18 bis 0 Uhr) nicht.**

Bild 1
![1](https://user-images.githubusercontent.com/31406990/30874142-cee0ae9e-a2ef-11e7-8a3b-48f4be424736.JPG)

Bild 2
![2](https://user-images.githubusercontent.com/31406990/30874144-cee3c0c0-a2ef-11e7-86dd-e675f302d9d8.JPG)

Bild 3
![3](https://user-images.githubusercontent.com/31406990/30874143-cee1a20e-a2ef-11e7-9456-cbdd9c168b2f.JPG)

Bild 4
![4](https://user-images.githubusercontent.com/31406990/30874145-cee4e310-a2ef-11e7-9ede-c5618d5734db.JPG)

**Comment by eric2905** [comment]
Gleiches Bild.

Bei mehrtägigen Einträgen (z.B. über 10 Tage wegen Urlaub) geht der Event um Mitternacht auf false (und bleibt auch so).

**Comment by Apollon77** [comment]
@pjo12345 Geht es Dir um das "event" oder um die Anzeige bei Events über Mitternacht?
An dem Thema das die Events richtig kommen versuche ich mich gerade ... 

Ich habe in deinen Screenshots aber auch gesehen das in der Tabelle aus "20:00-22:00" ein "20:00" wird wenn das Ende am nächsten Tag ist. Das bringt mich zu der Frage wie man das anzeigen sollte? Wenn es am nächsten tag endet ist das nicht das Thema und ein "20:00-01:00" versteht jeder auch wenn es in der "Today"-Farbe angezeigt wird, oder ?!
Aber was ist wenn das Ende übermorgen 01:00 ist?
Alternativ könnte man bei Events die in den Folgetag gehen ein "ab 20:00" schreiben und das Ende weglassen. Meinungen?

**Comment by pjo12345** [comment]
Moin!
Die Kennzeichnung könnte man machen wie auf dem Flugticket. Wenn die Zeit
für den nächsten Tag gilt dann ein +1 dahinter, eventuell in Klammern oder
so ähnlich.

Am 19.12.2017 6:30 nachm. schrieb "Ingo Fischer" <notifications@github.com>:

**Comment by jens-maus** [comment]
@Apollon77 Ich denke schon das das mit "+1" verständlich wäre. D.h. ich würde das vermutlich dann so darstellen:

```
20:00 – 22:00+1 Text
```

**Comment by Apollon77** [comment]
Ok, dann baue ich das mal so ein. Ich schraube gerade rum am Adapter ... :-)

**Comment by jens-maus** [comment]
Mach nichts kaputt, das ding hat nicht gerade einen sauberen Programmierstil ;)

**Comment by Apollon77** [comment]
:-) Ja ich fürchte schon das das Testen über "Freiwillige im Forum/GitHub" laufen wird.

**Comment by Apollon77** [comment]
So, testing habe ich auch erweitert ... Bitte mal 1.4.0 vom Github testen!

**Comment by pjo12345** [comment]
Habe jetzt mal einen Termin vom 27.12. 8:30 bis 28.12. 1:30 erstellt. Bei den Objekten wird er angezeigt als: Morgen 8:30-1:30+3
Warum +3? müsste das nicht +1 für den nächsten Tag sein?
![image](https://user-images.githubusercontent.com/31406990/34366192-d40a2d78-ea98-11e7-8f99-7009c672f438.png)

**Comment by Apollon77** [comment]
Ja das ist manchmal noch was komisch. Da bin ich gerade dran ... (wird aber denke morgen :-) )

**Comment by Apollon77** [comment]
Bitte neu testen

**Comment by Apollon77** [comment]
ne klappt noch nicht

**Comment by Apollon77** [comment]
So, denke (hoffe) habs jetzt. Bitte neu vom Github nehmen und schauen ...

**Comment by eric2905** [comment]
Sehr viele Daten/Infos im Log. Debug-Level steht auf „Info“

![38778dea-dfee-42bc-ab7f-8e0bb1efafa4](https://user-images.githubusercontent.com/18639287/34396523-7ffd53ca-eb6c-11e7-8828-bd5363d25d4e.jpeg)

**Comment by eric2905** [comment]
Sieht aber gut aus (siehe auch Forum)

**Comment by Apollon77** [comment]
Äääähm ... ja logging drehe ich morgen noch runter. :-))

**Comment by Apollon77** [comment]
Und: http://forum.iobroker.net/viewtopic.php?t=9981&start=20 checken „noch -1 Stunden“

**Comment by eric2905** [comment]
Jetzt sind es -2 Stunden.
Anscheinend wird bei Heute die verstrichene Zeit seit Mitternacht gezählt (siehe auch Forum)

**Comment by Apollon77** [comment]
Schaue heute Abend. Problemloser ja das der Termin gar nicht gestartet ist und daher die Restzeit gar nicht angezeigt werden sollte

**Comment by pjo12345** [comment]
Jetzt scheint die Anzeige OK zu sein.
![image](https://user-images.githubusercontent.com/31406990/34413137-b690ddc4-ebe1-11e7-90e1-9360eed49b07.png)

**Comment by pjo12345** [comment]
Wenn ich für morgen einen Termin bis 0:00 Uhr eintrage sieht es so aus:
![image](https://user-images.githubusercontent.com/31406990/34413229-46b61f7c-ebe2-11e7-81cb-905c90cdd6d3.png)

Mal sehen, ob das Event ausgelöst wird.

**Comment by Apollon77** [comment]
Danke fürs testen. An der eventlogik hab ich an Sicht nichts groß geändert. Das meiste war anzeigekram ;-)

**Comment by Apollon77** [comment]
@eric2905 Ich kann das Problem mit den "- Stunden" nicht nachvollziehen :-(

**Comment by pjo12345** [comment]
> Mal sehen, ob das Event ausgelöst wird.

Hat alles funktioniert. Von meiner Seite aus ist alles OK.

Danke für die Arbeit.
