### ISSUE TITLE
Heute im Ical

### ISSUE THREAD

**Issue by michihorni** [iobroker-community-adapters/ioBroker.ical#200]
Hallo ich nutze die aktuelle Version 1.8.2. Heute haben wir einen Geburtstag im Kalender, ICal zeigt allerdings "Noch 1 Tag ...."
Kann man für "Noch 1 Tag" durch Heute ersetzen?
Gruß
Michael

**Comment by Feuer-sturm** [comment]
Hi, schau dir mal diese Diskussion hier an: https://forum.iobroker.net/topic/26782/ical-kalender-farben-anpassen/
Aber wenn der Geburstag in "Noch 1 Tag" ist, müsste doch eher ein "Morgen" ausgegeben werden.

Aber mit dem dort diskutierten Skript kannst du die verbleibenden Tage in Heute, Morgen, Übermorgen ausgeben lassen:
![grafik](https://user-images.githubusercontent.com/25422320/101687264-89562280-3a6a-11eb-8a0b-02330c3d9dbd.png)

**Comment by bergjet** [comment]
Ich habe den Fehler auch.
Hier steht "Noch 1 Tag Alfred Geburtstag", der Geburtstag ist aber heute.
![Ohne Titel](https://user-images.githubusercontent.com/4241968/102685640-77028400-41e2-11eb-99f7-38469b3d23c0.jpg)

**Comment by Apollon77** [comment]
Naj "Noch 1 Tage" bedeutet "Termin läuft und endet in einem Tag" ... weil 1 tage die kleinste einheit ist

**Comment by bergjet** [comment]
Früher ist hier gestanden „Heute“

**Comment by Joerg82** [comment]
Den Fehler habe ich auch! Der Termin geht NICHT noch einen Tag sondern wird vom Adapter falsch aufbereitet. 
![grafik](https://user-images.githubusercontent.com/77452006/104694536-9de1a680-570b-11eb-9bf9-94d66221b99b.png)

Kann man das korrigieren?

**Comment by bergjet** [comment]
Der Fehler besteht noch immer. Der Geburtstag ist heute, angezeigt wird "noch 1 Tag"
![IMG_0798](https://user-images.githubusercontent.com/4241968/104889149-1051c100-596e-11eb-9093-ede624cdddf3.jpeg)

**Comment by bergjet** [comment]
Der Fehler tritt auf, wenn man "Wiederhole jedes Jahr" ankreuzt.

**Comment by Baenker** [comment]
Ich bitte zu Bedenken das manche Leute nicht Geburtstage nutzen sondern andere Sachen. Für mich und meine Termine passt die Anzeige von Noch x Tage. Meine Termine sind nicht Wiederholende Termine. Z. B. Urlaub.

**Comment by bergjet** [comment]
Ich benutze das nicht nur für Geburtstag. Wiederkehrende Termine z. B.  Arzttermin, Autoservice, Gesunden Untersuchung. Ein Kalender hat vielfältige Aufgaben.

**Comment by Joerg82** [comment]
@Baenker  Ja, kann ja sein. Trotzdem liegt hier ein Fehler vor. Und ich hätte gerne alle Termine richtig angezeigt, wenn das möglich ist.
Es geht ja nicht darum, die akteulle Anzeigeninhalte bei den anderen Terminen zu ändern, sondern, dass Serientermine, die jährlich am gelichen Tag stattfinden, richtig angezeigt werden.

**Comment by bergjet** [comment]
Bei mir 1.9.3 besteht der Fehler noch immer. Wie sieht dies bei euch aus?

**Comment by PrinzEisenherz1** [comment]
Bei mir besteht das Problem auch noch. Nach Version 1.7.4 werden ganztägige (jährlich wiederholende Termine) Falsch angezeigt.
Es betrifft wohl nur Termine die sich wiederholen.
Bei Version 1.7.4 ist noch alles i.O.
Gruß
Johnny

**Comment by bergjet** [comment]
Fehler besteht weiterhin.

**Comment by basty2** [comment]
Hallo, leider besteht der Fehler weiterhin in der Version 1.10.0. 
Bei mir werden Regeltermine die heute sind auf in 2 Tage verschoben. D.h. heute am 22.7. ist ein Termin, und in der Abfrage steht dieser auf den 24.7. 
zurück in der v. 1.7.4 funktioniert es wie gewohnt, der Termin bleibt auf dem 22.7.

**Comment by Feuer-sturm** [comment]
Es sieht so aus, als ob diese issue mit diesem hier im Zusammenhang steht: https://github.com/iobroker-community-adapters/ioBroker.ical/issues/191#issuecomment-885241496

ical 1.10.1 mit node-ical 0.11.4 
![grafik](https://user-images.githubusercontent.com/25422320/126712385-9643743b-b678-4b36-8c59-fe628db323be.png)

ical 1.10.1 mit node-ical 0.13.0 
![grafik](https://user-images.githubusercontent.com/25422320/126712931-84a47290-e7cf-415d-9cb3-ab0e742d9b00.png)

**Comment by Apollon77** [comment]
Bitte mit 1.10.3 verifizieren ob noch da oder gelöst

**Comment by Joerg82** [comment]
@Apollon77 

1.11.2:

Bei mir keine Änderung. Jetzt wird bei ganztägigen Terminen 02:00Uhr als Starttermin angezeigt und geht über in den nächsten Tag:
![grafik](https://user-images.githubusercontent.com/77452006/128205740-0e41cc89-7692-4435-a214-6bcd06c9b041.png)
so sieht das ganze in Google-Calendar aus:
![grafik](https://user-images.githubusercontent.com/77452006/128205880-4b3a5ce2-88b7-4422-9db5-1cac5d44898a.png)

**Comment by jens-maus** [comment]
@Joerg82 Bitte mal die 1.11.3 aus dem GitHub direkt installieren, dann sollte das hoffentlich seit heute auch behoben sein.

**Comment by Joerg82** [comment]
@jens-maus 

Hallo,

selbes Verhalten.

Kann es evtl. mit dem Script von @Scrounger  zusammenhängen?

` if (startTime.format('HH:mm') === '00:00' && endTime.format('HH:mm') === '00:00') {

                        // is full-day event

                        if (endTime.diff(startTime, 'hours') === 24) {

                            // full-day event, one day

                            start = startTime.format("YYYY-MM-DD");

                            end = startTime.format("YYYY-MM-DD");

                        } else {

                            // full-day event, multiple days

                            start = startTime.format("YYYY-MM-DD");

                            end = endTime.format("YYYY-MM-DD");

                        }

                    }`

Das Problem tritt "nur" bei Geburtstagen auf; also wiederkehrenden, ganztägigen Terminen.

Beste Grüße!

**Comment by Apollon77** [comment]
@jens-maus any idea?

**Comment by jens-maus** [comment]
Um hier helfen zu können würde ich die ics datei benötigen, bzw das entsprechende `VEVENT` im ics.

**Comment by Joerg82** [comment]
@jens-maus 

In der verwendeten ical-Instanz wird nicht nach Events gefiltert, da die Einträge ja ständig  wechselnde Namen sind.

Im table ist alles korrekt, in der calendar-widget Geschichte aber eben das gezeigte Verhalten.

Beste Grüße

**Comment by Apollon77** [comment]
> Im table ist alles korrekt, in der calendar-widget Geschichte aber eben das gezeigte Verhalten.

Ok,dann bitte zum Widget gehen. Der Adapter kann sich nur um seine eigenen Daten kümmern!

**Comment by Joerg82** [comment]
@Apollon77 

Alles klar, danke!
