### ISSUE TITLE
can't update with js-controller 3.2.6-0

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.ical#208]
can't update error message popup:
![grafik](https://user-images.githubusercontent.com/36229898/104271215-9cf60e00-549a-11eb-9e8f-5146366678b2.png)

![grafik](https://user-images.githubusercontent.com/36229898/104271241-ae3f1a80-549a-11eb-99c8-c55eb803f3cd.png)

Admin 4.2.0, Node 14.15.1, Debian 10

**Comment by Apollon77** [comment]
Please update manually on command line. there it should work. Admin seems to also need the update check. Reason is the 3.2.6-0 of controller

**Comment by Apollon77** [comment]
I will prepare an updated admin version

**Comment by Ilovegym66** [comment]
already done :-)
