### ISSUE TITLE
Downloadzeitplan und Auswertungszeitplan getrennt angeben

### ISSUE THREAD

**Issue by MarkStephan89** [iobroker-community-adapters/ioBroker.ical#209]
Hallo zusammen, 
Kalender wird über die Zeitplanung im IoBorker z.B. alle 30 Minuten ausgeführt und erhält somit neue Kalendereinträge. 

Wenn ein Kalendereintrag synchronisiert wurde, dann wird die Auswertung und das Aktualisieren der Datenpunkte auch nur alle 30 Minuten gestartet. 

Beispiel: 
Kalendereintrag "heizung" von 06:00 Uhr bis 06:45 Uhr. 
Datenpunkt ical.0.events.0.now.heizung wird um 06:00 Uhr auf true gesetzt. 
Aber erst um 07:00 Uhr wieder auf false, da nur alle 30 Minuten geprüft wird.

Eine Lösung wäre Zeitplanung auf z.B. 1 Minute zu setzten, damit man 1 minütig genaue Auswertungen hat. 
Dabei wird aber immer der Kalender neu runtergeladen. 
(Eventuell gibt es ja Anbieter, die ein Download Limit pro Zeit haben?)

Deshalb die Überlegung beide Zeiten zu trennen. 

Workaround wäre eventuell: .ical Datei local ablegen und den Download z.B. über Blockly zu regeln. 

Gruß
Mark

**Comment by Apollon77** [comment]
Also wenn man so ein Caching braucht dann ist ggf sinnvoller eine definierbare "Caching time" zu haben und ggf ein state was man setzen kann um ein "nächster run lädt neu" zu haben

**Comment by Diginix** [comment]
Bisher läuft der Adapter nur exakt zum Zeitpunkt des Abrufes, parst das ICS, setzt die states entsprechend und beendet sich wieder.
Für derartige Dynamik mit <=60 Sek Zeiten ist ein Kalender vllt nicht das richtige. Dafür gibt es Crons, Timer und den Javascript Adapter.
Es gibt auch ein Zeitplan Adapter von Carlo Pittini: https://github.com/Pittini/iobroker-Timer

Aber klar man könnte den Kalender lokal persistieren und öfter parsen als man ihn per Download aktualisiert.

**Comment by MarkStephan89** [comment]
starte ihn nun alle 5 Minuten. 
Solange Google nicht irgendwann dicht macht, würden in meinem Fall nun 5 Minuten reichen.

**Comment by Cabohne** [comment]
Hallo zusammen,
den Ansatz von @MarkStephan89 würde ich ebenfalls sehr begrüßen.

> 
> Deshalb die Überlegung beide Zeiten zu trennen.
> 

Die Tatsache, dass die Log-Einträge sich sehr anhäufen, wenn ich den Adapter bspw. alle 5 Minuten starte stört mich nämlich etwas.
Klar, könnte man die Log-Stufe der Instanz von "info" auf "warn" umstellen. Aber wirklich optimal ist diese Lösung auch nicht, da dann auch wieder Informationen im Log verloren gehen.

Um auf das Beispiel "Heizung" zurück zu kommen ... die Planung & Kalendereinträge stehen hierfür üblicherweise langfristig. D.h. es würde genügen die Kalenderdaten bspw. täglich um 01:00 Uhr abzurufen.
Wäre dann das setzen der Datenpunkte in einem separaten Zeitplan, hätte ich nur zu den tatsächlichen Schaltzeitpunkten wieder einen einzelnen Log-Eintrag. So würde ich mir das zumindest vorstellen.

Würde mich sehr freuen, wenn sich jemand der Thematik annimmt und vielleicht ein Update programmiert. Für Tests etc. stehe ich gerne zur Verfügung.

MfG
