### ISSUE TITLE
Documentation: ICal path of calendar (ics) file

### ISSUE THREAD

**Issue by JensMatic** [iobroker-community-adapters/ioBroker.ical#21]
The options are to specify a URL or a file name for the ics file. The question is where to drop the file on the IOBroker machine? I tried /opt/iobroker/node_modules/iobroker.ical as well as the iobroker-data directory. Didn´t work at any of those places.

Thanks, Jens

**Comment by Apollon77** [comment]
Best is to put the absolute path in the field. So put the file wherever you want and then add that path
