### ISSUE TITLE
Einlesen *.isc schlägt mit "getHours is not a function" fehl

### ISSUE THREAD

**Issue by etad4e5** [iobroker-community-adapters/ioBroker.ical#210]
Hallo,

ich habe den Adapter installiert und versuche nun von meinem Entsorgungsunternehmen das Abfallkalender einzulesen.
Dieses sieht so aus

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Sabre//Sabre VObject 3.1.2//EN
CALSCALE:GREGORIAN
BEGIN:VEVENT
UID:707209@mymuell.de
SUMMARY:Restmüll - Gustavstr. 13
DTSTAMP:20210116T214742Z
DTSTART:20201201
DTEND:20201202
END:VEVENT
BEGIN:VEVENT
UID:303697@mymuell.de
SUMMARY:Gelber Sack - Gustavstr. 13
DTSTAMP:20210116T214742Z
DTSTART:20201203

Nun scheint das Format nicht passend zu sein und es kommt dauerhaft zu folgenden Fehlern:

ical.0 | 2021-01-16 22:07:45.468 | error | at processImmediate (internal/timers.js:461:21)
-- | -- | -- | --
ical.0 | 2021-01-16 22:07:45.468 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.ical/main.js:228:25)
ical.0 | 2021-01-16 22:07:45.468 | error | at processData (/opt/iobroker/node_modules/iobroker.ical/main.js:358:17)
ical.0 | 2021-01-16 22:07:45.468 | error | at checkDates (/opt/iobroker/node_modules/iobroker.ical/main.js:399:19)
ical.0 | 2021-01-16 22:07:45.468 | error | (29717) TypeError: ev.start.getHours is not a function
ical.0 | 2021-01-16 22:07:45.468 | error | (29717) uncaught exception: ev.start.getHours is not a function
ical.0 | 2021-01-16 22:07:45.464 | info | (29717) processing URL: Abfallkalender http://192.168.178.33/Abfallkalender.ics

Beim Google habe ich aus dem Jahr 2016 ein vergleichbares Verhalten gefunden, jedoch ohne eine passende Lösung

**Versions:**  
 - Adapter version: 1.7.4
 - JS-Controller version: 3.1.6
 - Node version: 12.20.0
 - Operating system: linux

Danke schon mal im Voraus
 Eugen

**Comment by Apollon77** [comment]
Bitte die Version aus Latest nutzen. Ist es dort weg? Sollte

**Comment by etad4e5** [comment]
mit der Version 1.9.0 sind die Fehler weg. Das z.B. Gmail-Kalender funktioniert auch. Jedoch das Kalender aus der ics-Datei nach wie vor nicht verfügbar. Falsches Format?
Import der ics-Datei bei z.B. google verläuft einwandfrei
