### ISSUE TITLE
Tagesvorschau wird ab v1.8.0 ignoriert

### ISSUE THREAD

**Issue by th4git** [iobroker-community-adapters/ioBroker.ical#212]
Servus zusammen,

nutze den ical iobroker-Adapter seit mehr als 1 Jahr problemlos - mein Dank dafür geht an alle engagierten Entwickler!

Vor wenigen Tagen habe ich dann mal von v1.7.4 auf Version v1.9.0 aktualisiert. Erst einige Tage später bemerkte ich, dass einige Termine nicht mehr angezeigt werden. (node: v12.20.0, js-controller: 3.1.6)

Gestern kreiste ich die Ursache wie folgt ein:
Bis v1.7.5 läuft alles prima wie zuvor. Ab Version v1.8.0 und allen Nachfolgern wird für die anstehenden Termine (Quelle: caldav auf Synology) offenbar die Einstellung für **"Tagesvorschau" (hier =1)** ignoriert. Im Debug-Output wird beim Parsing  folgendes ausgegeben:

```
2021-01-17 22:00:09.124  - debug: ical.0 (11056) ev:{"type":"VEVENT","params":[],"dtstamp":"2020-12-31T20:20:50.000Z","uid":"411015","sequence":"1","summary":"Calendar/Test","location":"anywhere","description":"Calendar/Test at anywhere","start":"2021-01-17T23:00:00.000Z","datetype":"date","end":"2021-01-18T23:00:00.000Z","class":"PUBLIC","status":"CONFIRMED","transparency":"TRANSPARENT","e2fcfeb5-e2ca-4ccf-844b-abcaad7a345e":{"type":"VALARM","params":[],"trigger":"-PT6H","action":"DISPLAY","description":"Calendar/Test"}}
2021-01-17 22:00:09.124  - debug: ical.0 (11056) Event (full day) processing. Start: Mon Jan **18 2021 00:00:00** GMT+0100 (GMT+01:00) End: Tue Jan 19 2021 00:00:00 GMT+0100 (GMT+01:00)
2021-01-17 22:00:09.125  - debug: ical.0 (11056) Event (full day) " " Calendar/Test at Mon Jan 18 2021 00:00:00 GMT+0100 (GMT+01:00) filtered out, does not belong to specified time interval
```

Also wird der vorhandene Termin trotz anderer Vorgabe für Tagesvorschau herausgefiltert. Am Datum des Termins wird er korrekt als für heute anstehend angezeigt.

Wäre klasse, wenn das gefixt würde. Bis dahin betreibe ich einfach v1.7.5 weiter.

**Comment by Baenker** [comment]
Also zumindest für die V1.90 kann ich mit Tagesvorschau 7 sagen das es mit einem google Kalender funktioniert.

Die Frage wäre also was passiert wenn Du die Tagesvorschau mal auf 7 stellst. Passt es dann? Und was genau heißt nicht mehr angezeigt? Was steht den in denn unter data count Tomorrow?

**Comment by th4git** [comment]
Ergänzender Test:
Basis ist ein Kalender, der für heute und morgen jeweils zwei Termine (_ohne Wiederholungen_) enthält:
einer an fester Uhrzeit , einen als Ganztagstermin.
Wichtig zu wissen: Ein Termin mit Uhrzeit am nächsten Tag wird nur von einer Tagesvorschau erfasst, wenn er **innerhalb der nächsten 24h nach der aktuellen Uhrzeit beginnt**.

Test mit v1.9.0 ergibt  folgendes Bild:
Tagesvorschau=0 -> Beide Termine von Heute (OK)
Tagesvorschau=1 -> Beide Termine von Heute (OK); Keine Termine von morgen. (Not OK)
Tagesvorschau=2+ -> Beide Termine von Heute (OK); Von morgen Termin mit Uhrzeit (OK), Ganztagstermin nicht (Not OK).

Test mit v1.7.5 ergibt folgendes Bild:
Tagesvorschau=0 -> Beide Termine von Heute (OK)
Tagesvorschau=1 -> Beide Termine von Heute (OK); Beide Termine von morgen. (OK)
Tagesvorschau=2+ -> Beide Termine von Heute (OK); Beide Termine von morgen. (OK)

**Comment by Baenker** [comment]
Meine Ganztagestermine werden angezeigt mit der 1.90. 
Was sind das für Ganztagestermine? Einmaliger Termin oder wiederholende Termine.

Ich hoffe wiederholende denn dann hätte dieser Fehler mit einen anderen Fehler zu tun.

**Comment by th4git** [comment]
Die Testtermine von oben waren einmalig (keine Wiederholung). Es wurde nur ein einziger Kalender im ical-Adapter als Quelle hinterlegt (caldav-Server auf lokaler Synolgy via öffentlich erreichbarer Domain).

```
BEGIN:VEVENT
CREATED:20210123T140126
LAST-MODIFIED:20210123T140126
DTSTAMP:20210123T140126
UID:20210123T140126-ef7fa39d@172.17.0.1
SEQUENCE:2
SUMMARY:Test morgen Uhrzeit
TRANSP:TRANSPARENT
DTSTART;TZID=Europe/Berlin:20210124T120000
DTEND;TZID=Europe/Berlin:20210124T130000
DESCRIPTION:
LOCATION:
END:VEVENT

BEGIN:VEVENT
CREATED:20210123T140057
LAST-MODIFIED:20210123T140057
DTSTAMP:20210123T140057
UID:20210123T140057-b6b36a07@172.17.0.1
SEQUENCE:2
SUMMARY:Test morgen ganztags
TRANSP:TRANSPARENT
DTSTART;VALUE=DATE:20210124
DTEND;VALUE=DATE:20210125
DESCRIPTION:
LOCATION:
END:VEVENT
```

**Comment by th4git** [comment]
Hat niemend ein vergleichbares Problem, bzw kann niemand obige Beobachtung nachvollziehen?

**Comment by BassT23** [comment]
Doch ich,
ich bekommen auch nur noch Termine von Heute ausgewertet.
Alles andere (nach heute) wird nicht mehr angezeigt :(

**Comment by BassT23** [comment]
OK, ich sollte etwas genauer werden;
Ich nutze zwei ical instanzen
1. Instanz - Normaler Kalender ohne Ereignis Filter. Läuft alles bestens.
2. Instanz - Abfallkalender. Hier erstelle ich Ereignisse Gelber Sack, Restmüll, Papiertonne

Die Kalender werden per Google Privatadressen abgerufen.

Problem:
Für den Abfallkalender werden Ereignisse nur erstellt, wenn sie heute sind. Alles darüber hinaus wird nicht mehr ausgewertet, ...

**Comment by th4git** [comment]
> 2. Instanz - Abfallkalender. Hier erstelle ich Ereignisse Gelber Sack, Restmüll, Papiertonne
> 
> Die Kalender werden per Google Privatadressen abgerufen.
> 
> Problem:
> Für den Abfallkalender werden Ereignisse nur erstellt, wenn sie heute sind. Alles darüber hinaus wird nicht mehr ausgewertet, ...

Das deckt sich also mit meiner Beobachtung - nur, dass ich die eingebundenen Kalender lokal betreibe (Synology WebDAV).

Da das Thema schon ein halbes Jahr alt ist erlaube ich mir die Frage: Könnte es eventuell einen Fix geben (@Apollon77 , @jens-maus , ...?) oder kann man als Nutzer einfach etwas anders machen?

**Comment by BassT23** [comment]
Ich habe den Fehler gefunden;
Check mal die Einstellungen der Instanz.
Unter Haipteinstellung -> Vergangene Tage
Das Feld war bei mir leer. Habe dort eine 0 eingetragen.
Jetzt läuft es wieder.

**Comment by Apollon77** [comment]
Bitte mit 1.10.4 verifizieren ob noch da oder gelöst
