### ISSUE TITLE
get state Error: Connection is closed. / get state Error: DB closed

### ISSUE THREAD

**Issue by Diginix** [iobroker-community-adapters/ioBroker.ical#214]
Since JS-Controller 3.2 I get log warnings that the ical adapter tries to use the database after the instance is deemed to be ended/stopped officially. The adapter runs every 5 min and sometimes I get this on every run, but not always.

`ical.0	2021-01-26 04:50:18.001	warn	(594407) get state Error: Connection is closed.`
`ical.0	2021-01-26 04:50:18.005	warn	(594407) get state Error: DB closed`
`ical.0	2021-01-26 05:10:15.089	warn	(596992) get state Error: Connection is closed.`
`ical.0	2021-01-26 05:10:15.102	warn	(596992) get state Error: DB closed`
`ical.0	2021-01-26 05:40:19.980	warn	(601403) get state Error: Connection is closed.`
`ical.0	2021-01-26 05:40:19.988	warn	(601403) get state Error: DB closed`
`ical.0	2021-01-26 05:45:27.024	warn	(602032) get state Error: Connection is closed.`
`ical.0	2021-01-26 05:45:27.029	warn	(602032) get state Error: DB closed`
`ical.0	2021-01-26 06:20:18.047	warn	(606662) get state Error: Connection is closed.`
`ical.0	2021-01-26 06:20:18.051	warn	(606662) get state Error: DB closed`
`ical.0	2021-01-26 06:25:33.210	warn	(607307) get state Error: Connection is closed.`
`ical.0	2021-01-26 06:25:33.215	warn	(607307) get state Error: DB closed`
`ical.0	2021-01-26 06:30:12.673	warn	(607883) get state Error: Connection is closed.`
`ical.0	2021-01-26 06:30:12.676	warn	(607883) get state Error: DB closed`
`ical.0	2021-01-26 06:40:19.755	warn	(609173) get state Error: Connection is closed.`
`ical.0	2021-01-26 06:40:19.759	warn	(609173) get state Error: DB closed`
`ical.0	2021-01-26 06:50:14.985	warn	(610425) get state Error: Connection is closed.`
`ical.0	2021-01-26 06:50:14.989	warn	(610425) get state Error: DB closed`

JS-Controller 3.2.11
ical 1.9.0
nodejs 12.20.1

**Comment by Apollon77** [comment]
Please try github version ... better with this? (version is same)

**Comment by Diginix** [comment]
No warning log entries with the GIT version. Looks good so far. As soon as something abnormal happens, I will mention it here.

**Comment by Apollon77** [comment]
Cool, then I release that tomorrow

**Comment by Diginix** [comment]
Today I got again 2 times the log warnings with GIT 1.9.0:
> ical.0 | 2021-01-28 10:35:20.510 | warn | (194578) get state error: Connection is closed.
> ical.0 | 2021-01-28 10:35:20.513 | warn | (194578) get state error: DB closed
> ical.0 | 2021-01-28 11:05:20.061 | warn | (199334) get state error: Connection is closed.
> ical.0 | 2021-01-28 11:05:20.067 | warn | (199334) get state error: DB closed

**Comment by SurfGargano** [comment]
Hab die gleiche Warnung mit 1.91

ical.0 | 2021-02-07 10:00:16.465 | warn | (31755) get state error: DB closed
-- | -- | -- | --
ical.0 | 2021-02-07 10:00:16.464 | warn | (31755) get state error: Connection is closed.

**Comment by Apollon77** [comment]
A debug log would be interesting ... (but yes big)

**Comment by SurfGargano** [comment]
Mit JS- Controller 3.2.16 hab ich die Meldung jetzt nicht mehr gesehen.

**Comment by BenAhrdt** [comment]
i still have this issue on my system

**Comment by jens-maus** [comment]
Please don't bring up old, closed issue tickets again, thus not hijacking them. Instead open a new one with new updated information and technical details and refer to the closed ones instead.
