### ISSUE TITLE
iCal cannot read Nextcloud Calendar

### ISSUE THREAD

**Issue by Tomscloud** [iobroker-community-adapters/ioBroker.ical#215]
Hi

I have ioBorker running with latest, all updates installed, but all i'm testing there is no result in the iCal Objects.
Nextcloud is running 20.0.4

I test the connection wich privat key -> no result
I tested: https://myhome.at/remote.php/dav/ -> no result
I tested https://myhome.at/remote.php/dav/calendars/tom/familie/ -> no result
I tested https://myhome.at/remote.php/dav/calendars/tom/familie/?export -> no result

With "https://myhome.at/remote.php/dav/calendars/tom/familie/?export" i'm able to directly download .ics file

The only thing what is working is to read the .ics direct from the host.

Node.js
    v12.20.1
NPM
    6.14.10
JS-Controller
   3.2.11
iCal
   1.9.0

**Comment by techducks** [comment]
Hey,
same here.

**Comment by ghost** [comment]
@Tomscloud 
Can you please post your debug log?

Maybe it is an authentication problem? Have you activated 2 factor authentication on nextcloud ... then you need to generate an "app password" in useres profile.
