### ISSUE TITLE
Verbindungsfehler resettet Event

### ISSUE THREAD

**Issue by eric2905** [iobroker-community-adapters/ioBroker.ical#227]
Kommt es bei einem Kalender (Google Kalender, iCloud-Kalender, usw.) zu einem Verbindungsproblem und der Kalender kann nicht abgerufen werden, kommt es dazu, das Events auf einen Default-Wert (false?) zurückgesetzt werden.

Die führt zu blöden Fehlern … z.B. wird eine Steckdose ausgeschaltet, usw.

Es wäre gut, wenn kein Reset des Events stattfindet, sondern der aktuelle Wert einfach gesetzt bleibt.

iCal v1.9.1

**Comment by Apollon77** [comment]
Hast Du ein Log wo man sieht wa da passiert?

**Comment by buehlisiobroker** [comment]
Ich habe das mit dem Kalender auch leider so, wenn ich ein Kalender von Outlook abrufen und der kann danach nicht mehr abgerufen werden. Dann sind alle meine Termine für eine bestimmte Zeit wieder gelöscht. Also alle weg, und sobald der Abgleich wieder funktioniert, dann sind auch alle meine Termine mal wieder kurzzeitig auch wieder da.  Danke für ein Tipp oder Hilfe.

**Comment by eric2905** [comment]
> Hast Du ein Log wo man sieht wa da passiert?

Leider nein …. ist mir nur aufgefallen weil plötzlich Aktionen ausgeführt wurden, während ich im im Bett war (also nachts). Plötzlich wird die Haustür aufgeschlossen (nicht geöffnet). Etwas später wird sie dann wieder abgeschlossen. Im Nuki-Log sehe ich diese Aktion mit Auslöser über die Bridge. 
Über ein sep. Script habe ich mir die Veränderung des Datenpunktes per Telegram zuschicken lassen … passte mit den verschiedenen Aktionen

**Comment by buehlisiobroker** [comment]
Er kommt bei mir immer bis zum diesem Punkt. dann anschließend sind die Events/Termine wieder weg.
2021-03-18 06:50:09.662 - debug: ical.3 (4233) Plugin sentry destroyed
2021-03-18 06:50:09.663 - info: ical.3 (4233) Terminated (NO_ERROR): Without reason
2021-03-18 06:50:10.228 - info: host.raspberrypi instance system.adapter.ical.3 terminated with code 0 (NO_ERROR)

**Comment by eric2905** [comment]
> Er kommt bei mir immer bis zum diesem Punkt. dann anschließend sind die Events/Termine wieder weg.
> 2021-03-18 06:50:09.662 - debug: ical.3 (4233) Plugin sentry destroyed
> 2021-03-18 06:50:09.663 - info: ical.3 (4233) Terminated (NO_ERROR): Without reason
> 2021-03-18 06:50:10.228 - info: host.raspberrypi instance system.adapter.ical.3 terminated with code 0 (NO_ERROR)

Heute (gerade eben) wieder das gleiche Verhalten.
Die States alle auf false, obwohl im Kalender der Event vorhanden ist und der Event somit auf True stehen müsste. Erst beim nächsten Durchlauf wird es dann wieder richtig gesetzt.

**Comment by Baenker** [comment]
Den Wert zu belassen kann aber auch gefährlich werden. Ich lasse ical nur einmal Nachts laufen. Das heißt angenommen Montag um 0:10 Uhr ist Inernet verfügbar und der Wert aus den Kalender wird auf true gesetzt. Am Dienstag ist der Termin nicht. Wenn nun Dienstag um 0:10 das Internet nicht da wäre stände dort der Wert von Montag also weiterhin true. Das wäre auch nicht schön.

Es sollte ein Feld geben Letzter Abruf ical erfolgreich mit true oder false. Ganz schön wäre folgende Lösung:

Zusatzabfrage ob der gleiche Tag ist wenn nicht dann soll er einfach die Objekte von events.1 nach events.0 eintragen.
Wenn Abfrage ical innerhalb der gleichen Tages dann soll er die Werte belassen.

**Comment by Apollon77** [comment]
Die challenge ist in meinen Augen die folgende: Wenn ALLE zu lesenden Adapter nicht gelesen werden könne ... alles ok, dann könnte man durchaus sagen das man "nichts" tut.
Sobald aber ein Kalender von X geladen werden kann und ggf Events setzt dann wird es interessant weil ja "unbekannt" ist was jetzt weg ist weil die ganzen anderen Daten Fehlen.

ich weiss auch nicht ob "zuerst alles lesen und sobald einer einen Fehler hat dann nichts tun für alle" der sinnvolle Ansatz ist.

**Comment by Apollon77** [comment]
Ich habe in 1.10.4 mal versucht das für "kein kalender kann geladen werden" umzusetzen. Für Mischzustände ist es aber immer noch so

**Comment by Baenker** [comment]
was genau hast Du den umgesetzt? Was passiert nun genau wenn kein Kalender geladen werden kann?

**Comment by Apollon77** [comment]
Wenn kein Kalender galdern werden kann werden weder die ganzen "data.*" States aktualisiert und auch die "events.*" nicht "aufgeräumt" (aka auf false gesetzt weil ja nicht getroffen hat)

**Comment by Baenker** [comment]
Das kann aber nach hinten los gehen oder? Wie oben schon geschrieben wenn ich heute Urlaub habe und Morgen nicht und der Kalender kann um 00:03 nicht abgerufen werden dürfen die events nicht gleich bleiben. Es müssen dann die Events von events.1 nach events.0 verschoben werden, da es einen Tageswechsel gab. Nur bei Abrufen am gleichen Tag muss nichts passieren.

Wenn es gleich bleibt verschlafe ich sonst :-)

**Comment by Apollon77** [comment]
Dann hol ihn nicht nur einmal am Tag ab :-))

Dann wäre ich eher dabei das man Kalenderfiles lokal ablegt nach dem lesen und bei Lesefehlern dann diese lokale Version nutzt ... ?! Ist vllt das sinnvollste ... --> 1.11.0

**Comment by Baenker** [comment]
Auch wenn ich ihn mehrmals abhole ändert es nichts an der Tatsache das ein Termin der heute endet morgen nicht gültig ist. Internet kann auch mal 6 Stunden und länger ausfallen. Unser Provider nutzt für Wartungsarbeiten häufig das Zeitfenster 00:00 - 8:00 Uhr. Und das führt zu einen Problem. Wo die Daten mit den bisherigen Versionen geändert wurden auf false hatte man einen Fallback. Bei mir war alles false immer normaler Arbeitstag. Das heißt im schlimmsten Fall hatte ich Urlaub und wurde morgens geweckt und die Heizung ging früher an. Ärgerlich aber das konnte nur max 30 Tage im Jahr passieren. Mit der neuen Version weiß man erst mal nicht ob die Daten vom Adapter passen oder nicht und das jeden Tag. Das Risiko das die Felder falsch sind ist also wesentlich höher.
Es sollte zumindest dann ein neues Feld geben was man abgreifen kann, welches im Fehlerfall gefüllt wird. Man kann das dann als Fallback nutzen und die Automation zur Vorsicht auf Standard stellen. Klar wenn man den Kalender nur nutzt für Geburtstage, kein Problem aber wenn man ihn für Hausautomation nutzt finde ich die Lösung unglücklich.
Bin auch kein Freund davon beliebig oft Daten abzurufen, die sich nicht stündlich ändern. Zumal ich nachts nie Termine im Kalender eintrage.

Die Kalenderfile lokal abzuspeichern wäre wirklich die Beste alternative. Ich bleibe dann wohl vorsorglich lieber bei einer Version < 1.10.04.

P.S. Version 1.10.4 wäre für mich ein Breaking Change aus o. g. Gründen

**Comment by Apollon77** [comment]
> Die Kalenderfile lokal abzuspeichern wäre wirklich die Beste alternative. Ich bleibe dann wohl vorsorglich lieber bei einer Version < 1.10.04.

da ist in 1.11.0 implementiert ... have fun

**Comment by Apollon77** [comment]
> P.S. Version 1.10.4 wäre für mich ein Breaking Change aus o. g. Gründen

Das kommt jetzt sehr auf dich sichtweise an :-) Und ja kann für dich "breakting" sein. Für andere ist es die Behebung eines Bugs der Events geändert hat obwohl gar keine Daten neu verarbeitet wurde ... alles sehr spezifisch. Aber ich verstehe Deine sichtweise, daher das neue Feature in 1.11.0

**Comment by Baenker** [comment]
Ich werde es testen. Vielen vielen Dank. Wobei das natürlich schwierig ist, da ich diesen Fehler bisher zum Glück sehr selten hatte.

**Comment by Apollon77** [comment]
No answer, Closed. Please reopen if happens again
