### ISSUE TITLE
Wiederkehrende Termine erscheinen nicht

### ISSUE THREAD

**Issue by ing-michel** [iobroker-community-adapters/ioBroker.ical#234]
Hallo

Danke für das nützliche Plugin. Nutze den Kalender für die Müllabfuhrtermine im IOBroker. Jedoch werden keine angepassten wiederkehrenden Termine angezeigt. Lediglich Serientermine Termine werden angezeigt.
Wenn ein Termin wegen Ostern z.B. von Dienstag auf Mittwoch geschoben wurde, ist dieser im iCloud-kala
ender am Mittwoch eingetragen; gezeigt wird aber trotzdem der Dienstag.

**Versions:**  
 - Adapter version: 1.7.4

**Comment by kleiner-onliner** [comment]
Hallo,

bei mir ist es genauso. Ich nutze das Plugin ebenfalls im Zusammenhang mit IOBroker für die Müllabfuhrtermine. Sich wiederholende Termine werden korrekt gelesen, allerdings "verschobene", sich wiederholende Termine nicht.

Adapterversion: 1.7.4.

**Comment by Apollon77** [comment]
is it working with 1.7.3?

**Comment by ing-michel** [comment]
I'm sorry, but: How will I get this?

**Comment by kleiner-onliner** [comment]
Yes, it is the same behavior with v 1.7.3.

**Comment by Feuer-sturm** [comment]
@ing-michel 
Switch to "Expert mode" in the adapter overview. Then you can install a specific version with button [+]

![grafik](https://user-images.githubusercontent.com/25422320/113930461-9b19bd80-97f1-11eb-99f7-603d69dbf580.png)
![grafik](https://user-images.githubusercontent.com/25422320/113930528-ae2c8d80-97f1-11eb-9c54-dbff49532fb8.png)

**Comment by ing-michel** [comment]
Thanks!

**Comment by kleiner-onliner** [comment]
Hi Apollon77,

Do you need an example to determine the problem?

**Comment by Apollon77** [comment]
Sure, a minimal ical file that reproduces it helps any developer that find time to look into it

**Comment by kleiner-onliner** [comment]
BEGIN:VCALENDAR
PRODID:-//davical.org//NONSGML AWL Calendar//EN
VERSION:2.0
CALSCALE:GREGORIAN
X-WR-CALNAME:Test
BEGIN:VEVENT
DTSTAMP:20210427T191722Z
UID:d066bf16-8e05-4317-887b-28833b9fd68c
SEQUENCE:4
SUMMARY:Bio recurring appointment Test
COLOR:dodgerblue
DTSTART;VALUE=DATE:20210426
DTEND;VALUE=DATE:20210427
RRULE:FREQ=DAILY;INTERVAL=3
CLASS:PUBLIC
STATUS:CONFIRMED
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
DTSTAMP:20210427T191722Z
UID:d066bf16-8e05-4317-887b-28833b9fd68c
RECURRENCE-ID;VALUE=DATE:20210429
SEQUENCE:1
SUMMARY:Bio recurring appointment Test
COLOR:dodgerblue
DTSTART;VALUE=DATE:20210428
DTEND;VALUE=DATE:20210429
CLASS:PUBLIC
STATUS:CONFIRMED
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR

**Comment by kleiner-onliner** [comment]
This is an appointment that repeats every 3 days. Start is April 26th, 2021. April 29, 2021 was postponed to April 28, 2021. Nevertheless, April 29, 2012 is displayed.

**Comment by Apollon77** [comment]
Bitte in 1.10.3 prüfen ob noch vorhanden als Issue

**Comment by Apollon77** [comment]
No answer, Closed
