### ISSUE TITLE
Falsche Fälligkeit

### ISSUE THREAD

**Issue by ing-michel** [iobroker-community-adapters/ioBroker.ical#236]
Hallo,
habe mir mit ical einen Geburtstagskalender von iCloud eingelesen (webcam durch http ersetzt).

Nun zeigt mir ical aber Termine für heute (16.4.21) an, die gar nicht von heute sind.

Dieser Termin wird für heute angezeigt:
`BEGIN:VEVENT
DTEND;VALUE=DATE:20151217

LAST-MODIFIED:20151215T082429Z

UID:691F6885-DF3C-4650-A840-DA20F8EBD409

DTSTAMP:20161215T100910Z

STATUS:CONFIRMED

SEQUENCE:0

SUMMARY:Horst Abcdefg

DTSTART;VALUE=DATE:20151216

CREATED:20151215T082429Z

RRULE:FREQ=YEARLY;BYMONTHDAY=16

END:VEVENT`

Im Objekt text steht dann:
`Heute   Nino Abcdeefg 
Heute   Brigitte Abcdeefg 
Heute   Horst Abcdeefg 
Heute   Brigitte Abcdeefg 
Heute   Birger Abcdeefg `

Wobei position 2 und 4 auch einen anderen Termin haben.
(Nachnamen unkenntlich gemacht)
Kennt jemand von Euch das Problem?
Danke und Gruß
Michel

**Comment by ing-michel** [comment]
Das Problem tritt mit Terminen auf, die den gleichen Tag, aber einen anderen Monat zum Inhalt haben.
Z.B. wird heute am 26.04. ein Termin vom 26.12. angezeigt.

**Comment by Apollon77** [comment]
Bitte in 1.10.3 prüfen ob noch vorhanden

**Comment by Apollon77** [comment]
No answer, Closed
