### ISSUE TITLE
No Multiple events in one ical entry possible

### ISSUE THREAD

**Issue by jhergeth** [iobroker-community-adapters/ioBroker.ical#24]
When defining two or more events like: "work" and "evening". It is not possible to trigger both with one clender entry like: "work evening". Only the first event will be set to true during the calendar entry..

Solution:
Uncomment in main.js the break in line 469 (function checkForEvents) which stopps the processing of possible events after the first has been found. like:

` function checkForEvents(reason, today, event, fullday, realnow) {

    // show unknown events
    var result = true;
    // Schauen ob es ein Event in der Tabelle gibt
    for (var i = 0; i < events.length; i++) {
        if (reason.indexOf(events[i].name) != -1) {
            // auslesen ob das Event angezeigt werden soll
            result = events[i].display;
            adapter.log.debug('found event in table: ' + events[i].name);

            // If full day event
            // Follow processing only if event is today
            if ((fullday  && (event.start <= today)   && (today   <= event.end)) || // full day
                (!fullday && (event.start <= realnow) && (realnow <= event.end))) { // with time
                if (fullday) {
                    adapter.log.debug('Event (full day): ' + event.start + ' ' + today   + ' ' + event.end);
                } else {
                    adapter.log.debug('Event with time: '  + event.start + ' ' + realnow + ' ' + event.end);
                }

                // If yet processed
                if (events[i].processed) {
                    // nothing to do
                    adapter.log.debug('Event ' + events[i].name + ' yet processed');
                } else {
                    // Process event
                    events[i].processed = true;
                    if (!events[i].state) {
                        events[i].state = true;
                        adapter.log.info('Set events.' + events[i].name + ' to true');
                        adapter.setState('events.' + events[i].name, {val: events[i].state, ack: true});
                    }
                }
            }
//            break;
        }
    }
    return result;
}
`

**Comment by Apollon77** [comment]
I will change that in next release.

**Comment by Apollon77** [comment]
Bitte mal 1.4.0 vom Github testen!
