### ISSUE TITLE
State value to set for has to be type xx but received type yy (js-controller 3.3.x)

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.ical#242]
Admin 5.0.11
js-controller 3.3.5

With js-controller 3.3.x the following warning is shown:

`ical.0 (6873) State value to set for "ical.0.data.table" has to be type "string" but received type "object"`

**Comment by TheBrain26** [comment]
js-controller 3.3.8

Same Problem


ical.1 | 2021-05-05 09:30:21.639 | info | State value to set for "ical.1.data.table" has to be stringified but received type "object"
-- | -- | -- | --

**Comment by Apollon77** [comment]
fixed in next version 1.10.0
