### ISSUE TITLE
uncaught Exception ical 1.9.3 nodejs 14.16.1 js-controller 3.3.8

### ISSUE THREAD

**Issue by thomasBrecho** [iobroker-community-adapters/ioBroker.ical#252]
**Describe the bug**  
after URLProcessing of Nextcloud Calendars iCal is terminating due to uncaught Exception. No items in iobroker where updated. 

**To Reproduce**  
1. Go to 'instances'
2. Click on 'Reload'

**Expected behavior**  
URL Processing of Nextcloud Calendars without terminating

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.9.3
 - JS-Controller version: 3.3.8
 - Node version: 14.16.1
 - Operating system: ubunbtu 18.04 LTS

**Additional context**  
This behaviour is since update from nodejs 10.x to 14.x

![icalError](https://user-images.githubusercontent.com/54706984/118039246-68bf2b00-b370-11eb-8669-0e4994ddee3a.PNG)

**Comment by Apollon77** [comment]
Can you please try with upcoming 1.10.0 again?

**Comment by thomasBrecho** [comment]
yeah it's working now! great - thank's so much :-)
