### ISSUE TITLE
Synology Kalender

### ISSUE THREAD

**Issue by friedataube** [iobroker-community-adapters/ioBroker.ical#259]
**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by friedataube** [comment]
Moin,
Ich habe einen Kalender auf einer Synology Station.
Seit einiger zeit kommt die FEHLERMELDUNG Error: unable to verify the first certificate
UND ES WIR NICHTs MEHR ABGERUFEN.
Ich habe den im IOBroker angebotenen Adapter 1.7.3
Und den von hier 1.9.3 probiert aber bringen tut das allen nicht,
Auch von https auf http umstellen hat nichts gebracht,
Den gleichen Kalender benutze ich in meine Apple Welt und es funktioniert. 
Weiß einer nen rat. 

GRUSS MARCO

**Comment by Apollon77** [comment]
also wenn du http anstelle https nutzt sollte es keine zertifikatsfehle geben ...

welche nodejs version ist im Einsatz?

**Comment by Apollon77** [comment]
Closed, no answer
