### ISSUE TITLE
Termine mit 0 Minuten Dauer tauchen nicht im Adapter auf

### ISSUE THREAD

**Issue by toeoe** [iobroker-community-adapters/ioBroker.ical#26]
Hat ein Termin eine Dauer von 0 Minuten, wird dieser vom Adapter nicht erkannt bzw. eingelesen. Ändert man die Dauer des Termins auf z.B. 15 Minuten, findet der Adapter ihn sofort.

**Comment by jens-maus** [comment]
Hmm, wenn ein Termin doch aber genau 0 Minuten dauert existiert er dichvauch eigentlich nicht, oder? ;)

**Comment by toeoe** [comment]
Naja, das wäre eine Grundsatzdiskussion. ;-)
Wieso sollte ich einen Termin mit 0 Minuten anlegen, wenn es ihn eh nicht gibt. Ich lege oft Termine mit 0 Minuten an, weil ich einfach an etwas erinnert werden möchte, dies aber nicht 15 Minuten in meinem Kalender belegen muss. ;-)

**Comment by Apollon77** [comment]
Idee wäre den auch nur mit seiner Startzeit anzuzeigen. Ich mach das manchmal bei Remindern auch so ...

**Comment by Apollon77** [comment]
Bitte mal 1.4.0 vom Github testen!
