### ISSUE TITLE
Farbe pro Termin

### ISSUE THREAD

**Issue by HSE83** [iobroker-community-adapters/ioBroker.ical#263]
Moin,

es wäre schick, wenn der COLOR-Datenpunkt mit in den Termin mit aufgenommen werden könnte um pro Termin eine eigene Farbe vergeben zu können.
Alternativ wäre es cool (vielleicht sogar noch cooler als der erste Wunsch) "unbekannte" Datenpunkte aus der ICAL-Datei für jeden Termin über den JS-Datenpunkt verfügbar zu machen. Damit könnte man z.B. beliebige Formatierungen in Abhängigkeit von den Kalenderdaten selber per JS umsetzen.

Gruß,
Tobi

**Comment by Feuer-sturm** [comment]
@HSE83 Ich hab gerade einmal den Stand von deinem Github https://github.com/HSE83/ioBroker.ical/tree/add_color_feature in meiner Testumgebung installiert.

Was mir spontan aufgefallen ist:
- Hinter dem neuen Text ist ein Doppelpunkt. Soll dahinter noch etwas kommen, wenn die Checkbox aktiviert ist?
- Die Speichernbuttons werden nicht aktiviert, wenn man die neue Checkbox aktiviert
![grafik](https://user-images.githubusercontent.com/25422320/137598941-0d63a56c-efcf-4433-8f9e-65f1cf214ec8.png)

Mir ist noch nicht ganz klar, was die  neue Erweiterung genau bringt, bzw. was man damit machen kann. Kannst du hierzu noch ein paar Ergänzende Worte schreiben?

**Comment by Apollon77** [comment]
Included in GitHub version. @Feuer-sturm wenn im Termin selbst eine farbe angegeben ist dann wird die für das html in ner box als hintergrundfarbe genutzt?!

**Comment by Feuer-sturm** [comment]
@Apollon77 @HSE83 
Das scheint zu funktionieren :-)
Darstellung erhält man durch Anzeige des Datenpunktes "ical.x.data.html"
![grafik](https://user-images.githubusercontent.com/25422320/159137170-d9cc4139-f745-4c94-a9a3-894e0e8066db.png)

**Comment by Apollon77** [comment]
Cool, dann nehmen wir das so
