### ISSUE TITLE
Ausblenden der Jahreszahl, wenn gewünscht

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.ical#27]
Gut wäre: bei den Einstellungen ein Kästchen wo man die Jahreszahl manuell ausblenden kann.
Die ansicht in vis wäre dann so.

![bild1](https://user-images.githubusercontent.com/25694404/34351993-3f11cbe0-ea20-11e7-9bb1-e6459767fcd2.jpg)

**Comment by Apollon77** [comment]
Bitte vom Github testen. Neue Einstellung ist drin - Checkbox zum Ausblenden der Jahreszahl

**Comment by bahnuhr** [comment]
funktioniert.

Danke.
