### ISSUE TITLE
Change of type of data.table

### ISSUE THREAD

**Issue by SVallant** [iobroker-community-adapters/ioBroker.ical#271]
_IMPORTANT: data.table is now a stringified array!! Consider when using this value!_

Please do not change the type of any state inside 1 version.
Many scripts are based on this value and have to be changed. 
Better create a new state.

Thank you.

**Comment by Apollon77** [comment]
Sorry but before that the adapter was storing invalid data and that e.g. never worked if someone used redis as DB, so it was completely incosistent and in fcat a bug.

On the other hand: IF you use the most current latest "JavaScript" adapter then the adapter will autinatically convert that for you, s maybe your script do not need to be changed ...

**Comment by SVallant** [comment]
ok, i understand.
