### ISSUE TITLE
Serientermin ohne Uhrzeit

### ISSUE THREAD

**Issue by stefantaust** [iobroker-community-adapters/ioBroker.ical#274]
Bei einem Serientermin wird immer zusätzlich die Uhrzeit ausgegeben von 02:00 - 00:00 obwohl es ein Ganztagstermin ist. 

Zeitzone? Deshalb ab 02:00?

Ein ganztags Einzeltermin wird korrekt dargestellt

**Comment by Baenker** [comment]
siehe #249
