### ISSUE TITLE
ical Setting daysPast can not be decreased to zero with button

### ISSUE THREAD

**Issue by Feuer-sturm** [iobroker-community-adapters/ioBroker.ical#275]
ical 1.10.1

It is possible to increase the daysPast value with the up button but it is not possible to decrease the value to 0 with the down button:
![Animation14](https://user-images.githubusercontent.com/25422320/126835355-155289db-3c91-4b67-b0e6-667c7b0ee933.gif)

I think the problem is this here:
https://github.com/iobroker-community-adapters/ioBroker.ical/blob/ffdd3d7e01219d6269ed8331929b21da892653f5/admin/index_m.html#L127

If you change the min value to 0 you are able to decrease to zero with the down button
`<input class="value" id="daysPast" type="number"  min="0" max="99"/>`

I am not sure if this is the only line which needs to be changed.

**Comment by Apollon77** [comment]
@Feuer-sturm Want to do a PR for the change? :-) Your PR is against your own fork ... you need to do PR against this here :-)

**Comment by Feuer-sturm** [comment]
@Apollon77 I know it is in my own fork :-)  A shor feedback would be good if there are any other files which needs to modifyed to solve this problem or if index_m.html is the only one. I am not really familiar with the dependencies of the files.

**Comment by Apollon77** [comment]
As told in Discord ... all good and s´complete I think

**Comment by Feuer-sturm** [comment]
PR is available. Issue closed.
