### ISSUE TITLE
Termine werden zwei Stunden zu früh angezeigt

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.ical#279]
**Describe the bug**  
Die wiederholenden Termine werden in der V1.10.2 zwei Stunden zu früh angezeigt.

![kalender2](https://user-images.githubusercontent.com/35745035/127400964-4eb9ac7a-aaa5-42d4-8540-c93355920574.PNG)
![kalender](https://user-images.githubusercontent.com/35745035/127400965-1966b426-0145-4d36-a998-b517a202da80.PNG)

**Versions:**  
 - Adapter version: V1.10.2
 - JS-Controller: version: V3.3.15
 - Node version: V14.17.2
 - Operating system: Linux

**Comment by Feuer-sturm** [comment]
Hallo @senger1985 , das Problem ist in der 1.10.2 bekannt. @Apollon77 hat dafür schon einen Fix vorbereitet. Wir suchen aber noch einen anderen Fehler da vergangene Termine nicht mehr angezeigt werden, wenn man " Vergangene Tage" auf > 0 stellt

**Comment by Apollon77** [comment]
Das 2h Thema ist in GitHub schon gefixt, ich teste aber gerade noch das andere von @Feuer-sturm genannte Thema mit Ihm ... also kann sein das was anderes kaputt ist :-)

**Comment by Apollon77** [comment]
Bitte 1.10.3 testen

**Comment by senger1985** [comment]
Hat geklappt, danke.
Kann geschlossen werden.
