### ISSUE TITLE
Balken links in Adapter-Farbe

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.ical#28]
In den Einstellungen ein Kästchen wo man einen Balken links einblenden kann.

![bild2](https://user-images.githubusercontent.com/25694404/34352049-7bebb0b2-ea20-11e7-99c5-30bbddafb055.jpg)

Mit folgendem Code lass ich den Balken in Adapter-Farbe erzeugen:
`_bgcolor = calendar.color;`

Mit folgendem Code ändere ich die bgcolor bei dem Kalender Müll manuell per Script ab:
`if(calendar.name == "Müll") {
            if(entry.event == "Bio Tonne") {
                _bgcolor = "#a0e878";
                _color="color:#a0e878";
            }
            else if(entry.event == "Restmüll Tonne") {
                _bgcolor = "#ce6f6f"; 
                _color="color:#ce6f6f";
            }
            else if(entry.event == "Blaue Tonne") {
                _bgcolor = "#508fdc";
                _color="color:#508fdc";
            }
            else if(entry.event == "Gelbe Tonne") {
                _bgcolor = "#eee06d";
                _color="color:#eee06d";
            }
        }
        else _bgcolor = calendar.color;`

Hier wird dann auch das event in der entsprechenden Farben angezeigt.

mfg
Dieter

**Comment by Apollon77** [comment]
Und wie hast du den Balken umgesetzt? Du nimmst befindet eine Tabelle oder ?! Im normalen html sind es „span“s ...

**Comment by bahnuhr** [comment]
siehe mein Script in iobroker.
Die entsprechende Stelle hier nochmal:

`        if (balken === false) _bgcolor = "";
        
        if (_bgcolor !== "") html+="<tr style='background:transparent; background-image: linear-gradient("+_bgcolor+","+_bgcolor+"); background-size: 6px 90%; background-repeat: no-repeat;'>";
        else html+="<tr>";
`

**Comment by Apollon77** [comment]
Irgendeine Idee wie man das mit „nicht table“ macht?

**Comment by bahnuhr** [comment]
Ne, da kann ich dir nicht weiterhelfen.

Für mich aber auch nicht notwendig.
Ohne Balken find ichs eh besser.

**Comment by Apollon77** [comment]
Dann lass ich es als "Enhancement" mal noch offen aber unassigned ... vllt will später noch jemand dazu kommentieren und dann kommts wieder auf :-)

**Comment by bahnuhr** [comment]
mach hier doch auch zu.
Wenn jemand die Balken will, dann geht dies halt nicht mit dem Adapter.
Manuell per Script wäre dies dann weiterhin möglich.
mfg
Dieter
