### ISSUE TITLE
Ganztägige Serientermine werden nicht mehr als ganztägig angezeigt

### ISSUE THREAD

**Issue by lessthanmore1** [iobroker-community-adapters/ioBroker.ical#280]
Version: 1.11.0
Ganztägige Einzeltermine werden weiterhin als "ganztägig" angezeigt.
Sobald es aber ein Serientermin ist, so wird statt "ganztägig" "00:00 - 22:00" angezeigt.

Beispiel:
- Blaue Tonne: Einzeltermin - ganztägig.
- Termin darunter: Serientermin - ganztägig.
![1627633942501-unbenannt](https://user-images.githubusercontent.com/88196004/127657799-b8252cc8-53a2-4a44-bd9d-72f75a87cae2.jpg)

**Comment by Feuer-sturm** [comment]
@lessthanmore1 Kannst du bitte noch Screenshots von den ical Einstellungen bereitstellen? Welche Optionen sind aktiviert?

**Comment by Apollon77** [comment]
Und Debug Log wäre noch das prfekte (Admin - Instanzen - Expertenmodus ... Logstufe der ical Instanz auf Debug ... dann läuft Sie. Logfile vion Platte unter /opt/iobroker/log/... nicht Admin (der schneidet Zeilen ab)

**Comment by lessthanmore1** [comment]
Hier noch die ics files.
Einstellungen des Adapters:
![1](https://user-images.githubusercontent.com/88196004/127663834-923c168a-7541-4e1a-a3d5-1ff90c346f29.jpg)
![2](https://user-images.githubusercontent.com/88196004/127663842-c1fd56d3-eb1b-4e94-8ead-dd2508c7f31b.jpg)
![3](https://user-images.githubusercontent.com/88196004/127663844-b2395957-ae5e-419b-867b-f63ce37fe755.jpg)


[Archiv.zip](https://github.com/iobroker-community-adapters/ioBroker.ical/files/6907962/Archiv.zip)

**Comment by Apollon77** [comment]
1.11.1 auf dem Weg
