### ISSUE TITLE
Datenpunkt Termin Beschreibung

### ISSUE THREAD

**Issue by xTomi93** [iobroker-community-adapters/ioBroker.ical#281]
Hallo,

ich möchte mir einen Geburtstagskalender bauen der mir anzeigt wer in wie vielen Tagen Geburtstag hat und wie alt diese Person wird, dies hatte ich so früher schonmal in FHEM integriert über den Google Kalender, doch da ich jetzt auf iO-Broker umgestiegen bin will ich nicht extra nur für diese Informationen FHEM im Hintergrund mitlaufen lassen, daher die Frage ob es möglich ist die Beschreibung eines Termins mit zu übernehmen in ein Datenpunkt.  Meine Termine sind aktuell z.B. so angelegt.

Datum: tt.mm.jjjj
Terminname: Person X
Beschreibung: 1993

und über die Beschreibung kann ich ja dann das Alter mittels Bockly errechnen außer man integriert eine "Geburtstagskalender "-Funktion wie bei FHEM die es dann automatisch errechnet und einen Datenpunkt mit "Alter" anlegt.

Würde mich sehr freuen wenn es möglich wäre dies umzusetzen.

Mit freundlichen Grüßen
Thomas

**Comment by Baenker** [comment]
Ich vermute die Mehrheit hat den Gerburstag eher eingetragen mit Person X (67. Geburtstag). Zumindest baut Apple die Daten bei mir so auf. Es wäre also eine sehr spezielle Funktion. Wäre es nicht einfacher Du baust Deine Daten anders auf?

**Comment by mrjeschke** [comment]
Hallo,
Es gibt einen Adapter von Matthias Kleine Birthday der sollte genau das machen.

**Comment by xTomi93** [comment]
> Ich vermute die Mehrheit hat den Gerburstag eher eingetragen mit Person X (67. Geburtstag). Zumindest baut Apple die Daten bei mir so auf. Es wäre also eine sehr spezielle Funktion. Wäre es nicht einfacher Du baust Deine Daten anders auf?

**Comment by xTomi93** [comment]
Von Matthias Kleine hatte damals auch die Anleitung für FHEM deshalb ist auch mein ganzer Geburtstags Kalender so angelegt, dies alles zu ändern wäre zwar möglich könnte allerdings paar tage dauern.

Seinen Birthday Adapter für iobroker hab ich gar nicht bemerkt werde ihn mal direkt ausprobieren, vielen Dank.

p.s. diesen Beitrag zu schließen war eigentlich vorerst gar nicht meine absicht ^^
