### ISSUE TITLE
Request Methode POST mit Formular Daten

### ISSUE THREAD

**Issue by h07d0q** [iobroker-community-adapters/ioBroker.ical#285]
Die URLs werden standardmäßig über die Methode "GET" abgerufen.
Für einen Müllkalender muss ich diesen leider über "POST" mit den ausgewählten Abfallarten anfordern und bekomme die .ics Datei als response.

Die URL füllt das Formular im vornherein aus und aus dem Quelltext kommt man an die Formulardaten ICS_DOWNLOAD und REQUEST_TOKEN, wovon nur die Übermittlung von ICS_DOWNLOAD ausreicht, welche sich nicht verändert.

Kann man die Methode als Auswahl-dropdown-spalte und eine Spalte für die Formulardaten hinzufügen?

**funktionierendes JS:**
```
request.post({url: 'https://www.entsorgung-regional.de/entsorgung/leerungstermine/terminservice-ics-datei.html?icsgemeinde=M%C3%BChlacker&icsortsteil=D%C3%BCrrmenz&icsabfallart%5B%5D=Bioabfall&icsabfallart%5B%5D=Elektrogro%C3%9Fger%C3%A4te&icsabfallart%5B%5D=flach&icsabfallart%5B%5D=Restm%C3%BCll&icsabfallart%5B%5D=rund&icsabfallart%5B%5D=Schadstoff&icsabfallart%5B%5D=Sperrm%C3%BCll',
form: {ICS_DOWNLOAD:'3def184ad8f4755ff269862ea77393dd'/*,
REQUEST_TOKEN:'mdKLCvd4G0ZY8NZnqapIiUnudicwXPllcEVj15AZIVM'*/}},
async function(err,httpResponse,body){
/* write to file: httpResponse.body */
     }).on("error", function (e) {console.error(e);});
} catch (e) { console.error(e); }
```

Als Umweg müsste ich dieses Skript in einen Zeitplan packen und den Download in einer lokalen Datei zwischenspeichern, welche wiederum in der ical-Instanz eingetragen wird...

**Comment by jens-maus** [comment]
> Als Umweg müsste ich dieses Skript in einen Zeitplan packen und den Download in einer lokalen Datei zwischenspeichern, welche wiederum in der ical-Instanz eingetragen wird...

Genau so hätte ich das jetzt vorgeschlagen. IMHO können wir unmöglich alle Nutzungsszenarien hier abdecken. D.h. wenn du an das .ics nur via POST request rankommst dann lad den Kalender eben wie von dir beschrieben über ein separates skript zyklisch herunter und geb den lokalen pfad zum ics im ical adapter an. Genau so mache ich das auch mit einem anderen ics.

**Comment by h07d0q** [comment]
Werde es wohl übergangsweise so machen, aber eventuell gibt's noch andere, die dieses Feature gerne hätten.
Eventuell reiche ich mal einen PR ein (wäre mein erster)...

**Comment by Apollon77** [comment]
Ich wäre auch erstmal für ein lokales File. Das in den Adapter so einzubauen das es wirklich generisch nutzbar ist stelle ich mir sehr schwierig vor

**Comment by Baenker** [comment]
Ich importiere einfach die ics-Datei in den Google Kalender. Somit sieht man die Termine nicht nur im Adapter sondern auch in den normalen Kalender

**Comment by h07d0q** [comment]
Hatte ich bisher auch so, jedoch waren die Abfuhrtermine in einem eigenen Google Kalender (damit ausblendbar).
Die Termine können sich aber ändern und deswegen rufe ich wöchentlich die .ics ab.
Ein weiterer Punkt ist, dass die Termine aktuell nur bis Ende des Jahres eingepflegt sind und ich zu der Zeit nicht direkt daran denke den Kalender neu abzurufen :)
