### ISSUE TITLE
Abgelaufene Termine kommen den ganzen Tag

### ISSUE THREAD

**Issue by liv-in-sky** [iobroker-community-adapters/ioBroker.ical#286]
thread im forum https://forum.iobroker.net/post/658982

es ist heute der 5.8 und es ist 10:41 uhr

soll es so sein, das bei den daten dieser termin noch drin steht ?

```
	{
		"date": "05.08.2021 07:00-07:15",
		"event": "PAPIER TONNE",
		"_class": "ical_daily ical_today",
		"_date": "2021-08-05T05:00:00.000Z",
		"_end": "2021-08-05T05:15:00.000Z",
		"_section": "",
		"_IDID": "2sglr8mg3dj6pkb0bftufeagkv@google.com",
		"_allDay": false,
		"_private": false,
		"_rule": " rrule ",
		"location": "",
		"_calName": "daily",
		"_calColor": "#88f4f6"
	},
```

das debug login kann ich hier nicht posten - zuviele infos drin - bitte andere übermittlung vorschlagen

**Comment by Apollon77** [comment]
Die lokale Uhrzeit ist egal, wann ist der ical Adapter das etzte mal gelaufen? Das ist das relevante.

Log gern an iobroker@fischer-ka.de mit Angabe dieses Issue Links

**Comment by liv-in-sky** [comment]
das log ist im email

ist schon klar, dass du nicht die lokale zeit brauchst - im forum ist die antwort gewesen

aber im log kannst du das ja auch sehen

**Comment by Apollon77** [comment]
Please check Github version

**Comment by Feuer-sturm** [comment]
Fix funktioniert
