### ISSUE TITLE
"ganzer Tag" bei entsprechenden Terminen

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.ical#29]
In den Einstellungen ein Kästchen, dass "ganzer Tag" hingeschrieben wird, wenn es sich um einen Ganztagstermin handelt.

In vis dann so:
![bild2](https://user-images.githubusercontent.com/25694404/34352177-47b82040-ea21-11e7-87e1-8f74283e8535.jpg)

mfg
Dieter

**Comment by Apollon77** [comment]
Es gibt doch ein Textfeld in der konfig wo man angeben kann welcher Text bei ganztagsterminen anstelle der Zeit angezeigt werden soll. Schein Dochtes mal „ganzer Tag“ rein. Ich würde erwarten das das genau diesen Effekt hat.

**Comment by bahnuhr** [comment]
Ich habe dieses Textfeld nicht.
![bild2](https://user-images.githubusercontent.com/25694404/34360942-f81471e8-ea65-11e7-99a1-efc058335882.jpg)

Wo soll das sein?

**Comment by Apollon77** [comment]
Ersetze 0:00 mit ... hast du ;-)

Er würde dann das Datum schreiben und dahinter anstelle 0:00 diesen Text schreiben. 

Muss nochmal reinschauen heute Abend.

**Comment by Apollon77** [comment]
Also ich habs mal versucht. Termin morgen 0:00-0:00 (also Fullday) und in "Ersetze 0:00 mit" hab ich auf "ganzer Tag" gesetzt. Dann kommt ein "27.12.2017  ganzer Tag" raus.

Passtd as? Kannst Du es bitte verifizieren ... Danke

**Comment by bahnuhr** [comment]
Ja, sorum funktioniert das:

a) Ersetze 00:00 mit "ganztags"
Es kommt: 27.12. ganztags event

Wenn man dies aber nun rückgängig macht, funktioniert das nicht

b) Ersetze 00:00 mit (Inhalt gelöscht)
Es kommt: 27.12. 00:00-00:00 event

Es dürfte aber doch gar nicht mehr angezeigt werden. Richtig wäre:
27.12. event

mfg

**Comment by Apollon77** [comment]
Standardmäßig steht da ein leerzeichen drin wenn man das nur weg haben will :-) Die Einstellung wird nur aktiv wenn der Wert ungleich leer ist. Das war schon immer so
