### ISSUE TITLE
Einzelner geänderter Termin, aus Serienterminen wird nicht geändert

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.ical#299]
Wenn ich einen Termin, der als Serientermin eingetragen wurde, ändere, weil sich z. B.: der Tag geändert hat(nur für diesen einen Termin), wird dieser im ICAL-Adapter nicht abgegriffen und richtig angezeigt.

**Versions:**  
 - Adapter version: V1.11.4
 - JS-Controller version: V3.3.15
 - Node version: V14.17.5
 - Operating system: LINUX

**Comment by Apollon77** [comment]
Then please try to minimize this to a simple case and provide an example ICS File for that and provide a debug log

**Comment by senger1985** [comment]
email was sent

**Comment by Hohenbostler** [comment]
Hallo, 

ich habe genau das gleiche Problem. Ich habe nur einen Eintrag aus dem SerienKalender geändert und dieses wird nicht im iobroker eingelesen

**Comment by Hohenbostler** [comment]
Hi. 
wird hier noch ein Testkalender benötigt ?

**Comment by maximal1981** [comment]
Die Angaben sind nur bedingt korrekt.

Habe es selbst erst festgestellt. Es wird der Standardtag der Serie abgerufen und nicht die Verschiebung.
Sprich, der 01.11.2021 wäre laut Serie der Termin, wurde aber bereits vor etlichen Monaten auf den 05.11.2021 verschoben.

Angezeigt wurde der 01.11. Jedoch sollte im Auszug unten noch ein Restmüll Termin am 05.11. sein der aber fehlt

`[{"date":"In 3 Tagen  ","event":"Bio","_class":"ical_Abfuhrplan ical_3days","_date":"2021-11-04T23:00:00.000Z","_end":"2021-11-05T23:00:00.000Z","_section":"","_IDID":"@google.com","_allDay":true,"_private":false,"_rule":" rrule ","location":"","_calName":"Abfuhrplan","_calColor":"#000000"},{"date":"19.11.2021  ","event":"Bio","_class":"ical_Abfuhrplan ","_date":"2021-11-18T23:00:00.000Z","_end":"2021-11-19T23:00:00.000Z","_section":"","_IDID":"@google.com","_allDay":true,"_private":false,"_rule":" rrule ","location":"","_calName":"Abfuhrplan","_calColor":"#000000"},{"date":"26.11.2021  `


Ich habe für mich jetzt den einen Termin dupliziert und den "falschen" aus der Serie gelöscht.

**Comment by liv-in-sky** [comment]
vielleicht hilft das:
habe mal die daten angeschaut - hier sieht man was da bekommen wird und was angezeigt bzw angezeigt werden soll

![Image 2](https://user-images.githubusercontent.com/18462890/140509648-cc1482a4-55b1-48aa-8137-ba248fdb5c07.png)

**Comment by Feuer-sturm** [comment]
@Apollon77 Du hattest hier https://forum.iobroker.net/topic/48976/ical-trashschedule-daten-neu-synchronisieren/18 geschrieben, dass vermutlich ein Problem in node-ical ist. Ist das hier https://github.com/jens-maus/node-ical das richtige Projekt, wo man dann ein Ticket anlegen müsste?

**Comment by Apollon77** [comment]
ja

**Comment by Apollon77** [comment]
Bitte mal mit ical adapter Version von heute versuchen

**Comment by Hohenbostler** [comment]
Hallo, 

ich glaube wenn ich es richtig getestet habe das es nicht funktioniert hat . So kommt es im iobroker an:
![image](https://user-images.githubusercontent.com/42488069/141062655-c5092684-5495-41b2-b2aa-05a1333e084a.png)


so sieht es in meinem Kalender Aus

![image](https://user-images.githubusercontent.com/42488069/141062433-dcd08dad-22f7-40f0-a52b-fe5a48615c41.png)

Und so in meinem Kalender wo ich die ics testweite mal eingebunden habe. Somit ist diese richtig.

![image](https://user-images.githubusercontent.com/42488069/141063323-cdd7f461-95c4-41b6-8b56-3b22a10951b9.png)



Ich muss bei mir noch dazu sagen , jeder Tag ist ein einzelner Serienkalender. Also alle Montage  sind einer , alle Dienstage ein zweiter usw usw.

**Comment by Hohenbostler** [comment]
Was noch zu bemerken ist, ich habe den gleichen Kalender im Jarvis eingebunden dort funktioniert es einwandfrei . 
Das nur als Anmerkung und iwem was böses zu wollen oder es böse zu meinen

**Comment by liv-in-sky** [comment]
bei mir funktioniert es leider  auch nicht

kalender zeigt verschobenen termin


![Image 2](https://user-images.githubusercontent.com/18462890/141091742-984d100d-c8b3-4cec-8bb8-a68a9e728151.png)

ical anzeige weiterhin:


![Image 3](https://user-images.githubusercontent.com/18462890/141091757-06235538-d085-4ba0-9a1c-831e7a2acf05.png)

**Comment by Feuer-sturm** [comment]
Ich hab gerade einmal die Version 1.11.6 getestet und bei mir werden jetzt einzelne Termine aus einer Serie richtig in ioBroker dargestellt, wenn ich diese verändere oder lösche.

@jens-maus Ist es dieses issue, welches du mit der 1.11.6 gefixt hast?

1.11.6 (2021-12-17)
    (jens-maus) fixed incorrect recurrence event processing

**Comment by jens-maus** [comment]
Genau so ist es

**Comment by Apollon77** [comment]
cool!!
