### ISSUE TITLE
Time auch anzeigen bei aktuellem Termin wenn wir uns gerade darin befinden (wenn Datum anstatt "Ersetze Datum mit Worten")

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.ical#30]
Wenn in den Einstellungen nicht angehakt: "Ersetze Datum mit Worten"
dann wird bei Terminen die gerade aktuell sind angezeigt:
--> event
d.h. die Time ist nicht mehr vorhanden.

Wenn in den Einstellungen anghakt: "Ersetze Datum mit Worten"
dann wird bei Terminen die gerade aktuell sind angezeigt:
Heute 11:00-14:00 event
d.h. die Time wird angezeigt (und dies ist auch richtig so).

Fazit:
Time anzeigen wenn ersetzen mit Worten eben nicht gewünscht ist.

mfg
Dieter

**Comment by Apollon77** [comment]
Ist das in dr aktuellen 1.4.0 vom github auch noch so? Dachte da hatte ich schon was vereinheitlicht. 
Ich schaue heute Abend mal rein spätestens

**Comment by bahnuhr** [comment]
Ja, hast recht.
jetzt wird angezeigt:
-> endzeit event

(Die Anfangszeit wird nicht mehr mit angezeigt).
Scheint aber so gewollt sein.

**Comment by Apollon77** [comment]
Aus meiner sich ja, weil läuft ja schon. Anfang daher ja egal oder?!

Damit gefixt für dich?

**Comment by bahnuhr** [comment]
Ja, lass es so.
Pfeil, endzeit und event

**Comment by Apollon77** [comment]
Dann lassen wir es so :-)
