### ISSUE TITLE
Vergangene Termine verschwinden nicht mehr

### ISSUE THREAD

**Issue by dominikkerkow** [iobroker-community-adapters/ioBroker.ical#301]
Seit einem neuen Update verschwinden die Termine am selben Tag nicht mehr, wenn die Uhrzeit abgelaufen ist.

**Comment by Feuer-sturm** [comment]
@dominikkerkow Welche Version vom ical Adapter setzt du ein? 
Das Thema hatten wir hier schon einmal https://github.com/iobroker-community-adapters/ioBroker.ical/issues/286 und  sollte mit der Version 1.11.4 behoben sein https://github.com/iobroker-community-adapters/ioBroker.ical/blob/master/README.md#1114-2021-09-02

**Comment by Apollon77** [comment]
Ich update 1.11.4 mal in stable

**Comment by dominikkerkow** [comment]
Sorry für die späte Antwort. Ich habe 1.11.2
Seit heute funktioniert es aber wieder *confused*

**Comment by dominikkerkow** [comment]
Ok, nun habe ich wieder den Effekt, dass die Termine stehen bleiben. 2 Termine sind heute morgen verschwunden, der Rest nicht.

**Comment by Feuer-sturm** [comment]
@dominikkerkow Das Problem ist erst in der 1.11.4 gefixt. @Apollon77 will die 1.11.4 im stable vereröffentlichen dann wirst du sie auch sehen und aktualisieren können (ich gehe mal davon aus, dass du auf dem stable repository arbeitest).

**Comment by Apollon77** [comment]
ist seit gestern im stable ...

**Comment by dominikkerkow** [comment]
Sieht super aus! Danke für die schnelle Kommunikation und Lösung.
