### ISSUE TITLE
Pfeil anzeigen

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.ical#31]
In den Einstellungen ein Häkchen, dass der Pfeil angezeigt werden soll oder eben nicht.

Mir gefällt er nicht.
Datum finde ich schöner.

mfg
Dieter

**Comment by Apollon77** [comment]
Der Pfeil bezeichnet ja einen Termin der gerade läuft wo dann der endzeitpunkt anstelle Start angezeigt wird. Was wäre dein Ersatz für den Pfeil? Noch das Wort „bis“?

Irgendwie muss man das ja unterscheiden können ...

**Comment by bahnuhr** [comment]
ok, dann lass den Pfeil stehen.
Bekomme jetzt auch die Endzeit angezeigt.
Wäre schön wenn der event auch rot wäre. (also die gesamte Zeile)

**Comment by Apollon77** [comment]
Schau zu der Thematik mal bitte im Tester forumsbereich im iobroker Forum ... lass das mal da diskutieren. Notfalls muss ich das konfigurierbar machen. 

Kommt davon das vorher die Spans falsch waren.

**Comment by Apollon77** [comment]
Also kann der issue auch zu? Super
