### ISSUE TITLE
Mehrere kalender getrennt behandeln

### ISSUE THREAD

**Issue by Hohenbostler** [iobroker-community-adapters/ioBroker.ical#310]
Hi ich würde mir wünsche das ich mehrere Kalender in einer Instanz getrennt ausgeben lassen kann.

Aktuell ist es leider so das alle Kalender einer Instanz zusammen die Datenpunkte unter Data füllen. 
Das zwing mich dazu das ich mittlerweile 5 Instanzen angelegt habe da ich gerne die einzelnen Kalender gerne autark von den anderen behandeln würde. Die könnte man zB realisieren durch eine Checkbox in den Kalendern ( einzeln ausgeben ) 
Und dann genriert sich pro einzelner ausgabe eine neue Ordnerstruktur

**Comment by Apollon77** [comment]
Was spricht gegen 5 Instanzen?

**Comment by Hohenbostler** [comment]
Nur evtl die Performance und der Pflegeaufwand
