### ISSUE TITLE
Einmaliger Termin wird erkannt, wiederholende Termine nicht

### ISSUE THREAD

**Issue by pjo12345** [iobroker-community-adapters/ioBroker.ical#313]
Moin!
Ich habe bei mir festgestellt, dass sich ,ganztägige und wiederholende Termine (bei mir alle 6 Wochen) nicht erkannt werden, also in ical.0.events.now nicht auf true gesetzt werden. Ändere ich den Termin auf ganztägig einmalig (eine komplette Woche Mo-Fr), dann wird er auf true gesetzt. Das kann ich beliebig wiederholen.

**Comment by Feuer-sturm** [comment]
@pjo12345 Schau dir bitte einmal dieses issue ab, ob dein Problem damit abgedeckt ist: https://github.com/iobroker-community-adapters/ioBroker.ical/issues/307

**Comment by pjo12345** [comment]
@Feuer-sturm Jo, mit 1.11.0 funktioniert es wieder.

**Comment by Feuer-sturm** [comment]
@pjo12345 Wenn sich dein Problem mit dem anderen issue deckt, dann kann dieses Ticket ja geschlossen werden.

**Comment by pjo12345** [comment]
Ok, ich schließe diesen Issue, da das Problem schon erwähnt wurde.
