### ISSUE TITLE
ical-anzeige

### ISSUE THREAD

**Issue by vauvau07** [iobroker-community-adapters/ioBroker.ical#32]
nach update keine Änderung
<img width="256" alt="unbenannt" src="https://user-images.githubusercontent.com/34857880/34355333-c8ca5a0a-ea34-11e7-8587-ee05ed013284.PNG">

und die Daten

[Allgem.zip](https://github.com/ioBroker/ioBroker.ical/files/1587228/Allgem.zip)

**Comment by Apollon77** [comment]
Kannst Du bitte nochmal neu vom Github installieren und dann die Instanz restarten. Und bitte mal die Konfig des Adapters noch als Screenshot schicken. Kann das gerade nicht nahvollziehen

**Comment by Apollon77** [comment]
Korreigiere. Kann es nachvollziehen - zumindestens das mit dem falschen "+1" ... Bin dran.

Die "00:00" bekommst Du weg indem Du in der Kontig bei "Ersetzte 0:00 mit" einfach ein leerzeichen reinschreibst

**Comment by Apollon77** [comment]
Bitte testen, sollte jetzt weg sein.

**Comment by Apollon77** [comment]
ne klappt noch nicht :-(

**Comment by vauvau07** [comment]
neu vom Github installiert, ical.0 restart, 00:00 mit Leerzeichen : keine Veränderung

<img width="464" alt="ical 0" src="https://user-images.githubusercontent.com/34857880/34381216-78ff32ba-eb07-11e7-8570-3b2236eba1fa.PNG">

**Comment by vauvau07** [comment]
Datum stimmt jetzt nicht mehr , ein Tag zurück

**Comment by Apollon77** [comment]
Ja ich weiß. Ersetze Datum mit Worten ist tricky. In dem Bereich bin ich noch dran :-( ohne das passt alles ... heute Abend

**Comment by Apollon77** [comment]
So, denke (hoffe) habs jetzt. Bitte neu vom Github nehmen und schauen ...

**Comment by vauvau07** [comment]
nach neu vom Github: +1 ist nicht mehr vorhanden, einmalig Ganztägtig auch i.O., bei Ganztätigen Wiederholungen 00:00

**Comment by Apollon77** [comment]
Das letztgenannte: bug? Bitte mal Screenshot.

**Comment by Apollon77** [comment]
Ganztägige Wiederholung ist ein nicht sauber behandelter Fall (war schon immer so). Ich schau mal

**Comment by vauvau07** [comment]
<img width="260" alt="testtermin" src="https://user-images.githubusercontent.com/34857880/34407747-5b909962-ebc0-11e7-936c-8d3cb09fe509.PNG">

**Comment by Apollon77** [comment]
Bitte mal neueste github Version versuchen hab die Logik bei recurring mal so angepasst das Ende über die dauer des Termins neu festgelegt wird.

**Comment by vauvau07** [comment]
<img width="222" alt="testtermin" src="https://user-images.githubusercontent.com/34857880/34412406-60e397b2-ebdd-11e7-8138-ddd42b45a291.PNG">
vielen Dank, daß ist das Ergebnis

**Comment by Apollon77** [comment]
Dann kann hier zu? ;)

**Comment by vauvau07** [comment]
Ja, vielen Dank nochmal ;)

**Comment by Apollon77** [comment]
So ich habe noch ein paar Kleinigkeiten gefixt. Bitte jetzt nochmal GithUb testen alle die können. Das wäre aktuell mein "Release candidate" :-)

**Comment by vauvau07** [comment]
Bei mir alles i.O.
