### ISSUE TITLE
error: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone

### ISSUE THREAD

**Issue by realwax** [iobroker-community-adapters/ioBroker.ical#325]
https://github.com/ioBroker/ioBroker.js-controller/issues/1528

As stated by the js-controller devs and git I like to address the issue her:

`2021-11-21 12:01:07.553  - [32minfo[39m: ical.0 (21640) processing URL: G https://calendar.google.com/calendar/ical/.....
2021-11-21 12:01:08.395  - [32minfo[39m: ical.0 (21640) processing URL: W https://calendar.google.com/calendar/ical/.....
2021-11-21 12:01:14.505  - [32minfo[39m: ical.0 (21640) Terminated (NO_ERROR): Without reason
2021-11-21 12:01:15.293  - [31merror[39m: host.iobrokerQNAP Caught by controller[0]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
2021-11-21 12:01:15.293  - [31merror[39m: host.iobrokerQNAP Caught by controller[1]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
2021-11-21 12:01:15.293  - [31merror[39m: host.iobrokerQNAP Caught by controller[2]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
2021-11-21 12:01:15.294  - [31merror[39m: host.iobrokerQNAP Caught by controller[3]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
2021-11-21 12:01:15.294  - [31merror[39m: host.iobrokerQNAP Caught by controller[4]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone`

**Comment by thost96** [comment]
same for me

**Comment by liv-in-sky** [comment]
me to

**Comment by Apollon77** [comment]
try latest 1.11.5

**Comment by liv-in-sky** [comment]
ist nicht besser geworden mit 1.11.5 - massig von den einträgen `Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone`


ausschnitt von syslog:
![Image 4](https://user-images.githubusercontent.com/18462890/145543485-2cbccb1e-d3bb-473b-954e-9ccb30cd32d3.png)



`Dec 10 09:11:39 iobroker59 bash[43596]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Dec 10 09:11:39 iobroker59 bash[43596]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Dec 10 09:11:39 iobroker59 bash[43596]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Dec 10 09:11:39 iobroker59 bash[43596]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Dec 10 09:11:39 iobroker59 bash[43596]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Dec 10 09:11:39 iobroker59 bash[43596]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Dec 10 09:11:39 iobroker59 bash[43596]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone

Dec 10 09:12:02 iobroker59 bash[43652]: (Use `node --trace-warnings ...` to show where the warning was created)
Dec 10 09:12:02 iobroker59 bash[43652]: (node:43652) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
Dec 10 09:12:02 iobroker59 bash[43652]: (node:43652) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
Dec 10 09:12:02 iobroker59 bash[43652]: (node:43652) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency`

**Comment by realwax** [comment]
1.11.5 was the version I reported the error with.

**Comment by wendy2702** [comment]
Any news on this?

**Comment by realwax** [comment]
As far as I understand it seems to originate out of the usage from rrule that is being used by ical. Here in this article they got rid of these messages using an earlier version. (~ hotfix :/ ) So it seems like there is another way to fix it as the usage must be adapted to what the error message states. 

https://stackoverflow.com/questions/64299310/rrule-using-tzid-without-luxon-available-is-unsupported

Hopefully one of the devs can pick it up but on the other hand it's just a bunch of warnings yet and still everything is functional.

Have a nice day. :)

**Comment by Apollon77** [comment]
This should be fixed, or?!

**Comment by realwax** [comment]
Nope...

Ingo Fischer ***@***.***> schrieb am Sa., 19. März 2022,
14:17:

**Comment by Apollon77** [comment]
Yes I also found the reason I think. Can you pklease try GitHub version?

**Comment by realwax** [comment]
> Yes I also found the reason I think. Can you pklease try GitHub version?

Thank you. It seems to be gone. Updated against GIT - no messages anymore today.

**Comment by liv-in-sky** [comment]
seems to work now - installed new adapter version - can't see any of this message

**Comment by RK62** [comment]
Same error when using Google-Calendar with ical v1.13.1
