### ISSUE TITLE
1 wiederkehrenden Termin verschoben -> wird falsch angezeigt

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.ical#33]
Ich habe in google einen wiederkehrenden Termin erstellt:

test2
morgen um 17:00-19:00
alle 2 Tage gleiche Uhrzeit; 3 x wiederkehrend.

Folglich:
27.12. um 17:00-19:00
29.12. um 17:00-19:00
31.12. um 17:00-19:00

Dann habe ich den mittleren Termin verschoben auf 13:00-15:00
In google dann folglich:
27.12. um 17:00-19:00
29.12. um 13:00-15:00
31.12. um 17:00-19:00

Dies kommt aber nicht in ical an:
In Ical wird auch der mittlere Termin mit 17:00-19:00 ausgewiesen !
![bild2](https://user-images.githubusercontent.com/25694404/34361199-4d6a86e4-ea68-11e7-9043-c8f83831e284.jpg)

Dies war der bug den ich auch in iobroker beschrieben hatte.
Es stimmen sogar die Datumsangaben nicht mehr.
Wenn heute der 26.12. ist; warum wird dann in ical "übermorgen", in 4 Tagen und in 6 Tagen ausgewiesen (hier ist jeweils 1 Tag zu viel).

mfg
Dieter

**Comment by Apollon77** [comment]
Hast du das mal als ics file?

**Comment by bahnuhr** [comment]
wo finde ich das?

Hab aber den test-Termin schon wieder gelöscht.

**Comment by Apollon77** [comment]
Das ist das File was unter der URL kommt die du im ical Adapter angegeben hast. Falls der Link privat ist nicht so schlimm, dann file runterladen.

Ansonsten versuche ich mal so einen Termin selbst zu machen

**Comment by Apollon77** [comment]
Also es sieht nach einem problem in der verwendeten node-ical Library aus die das parst.

@jens-maus 
Kann bei node.ical leider keine Issues auf machen:
Folgendes ics wird falsch geparst:

```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Steuerung
X-WR-TIMEZONE:Europe/Berlin
X-WR-CALDESC:Heim-Steuerung
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20171227T130000
DTEND;TZID=Europe/Berlin:20171227T140000
EXDATE;TZID=Europe/Berlin:20171231T130000
RRULE:FREQ=DAILY;INTERVAL=2
DTSTAMP:20171227T110728Z
UID:2C340B07-5893-4921-B0E5-A5EE82858F01
CREATED:20171227T082153Z
DESCRIPTION:
LAST-MODIFIED:20171227T110650Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:RecurringTest
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20171229T150000
DTEND;TZID=Europe/Berlin:20171229T160000
DTSTAMP:20171227T110728Z
UID:2C340B07-5893-4921-B0E5-A5EE82858F01
RECURRENCE-ID;TZID=Europe/Berlin:20171229T130000
CREATED:20171227T082153Z
DESCRIPTION:
LAST-MODIFIED:20171227T082203Z
LOCATION:
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:RecurringTest
TRANSP:OPAQUE
X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
END:VEVENT
END:VCALENDAR
```
Das EXDATE wird nicht beachtet und die Verschiebung auch nicht :-(
Any idea?

**Comment by Apollon77** [comment]
Aaaalso ... Status ist:
Was klappt ist das löschen von einzelnen Terminen der widerkehrenden Reihe. Das wird korrekt aussortiert.
Was nicht klappt ist wenn man einzelne Termine verschiebt.
@jens-maus Any idea?

**Comment by Apollon77** [comment]
@jens-maus Habe in einigen commits bei der originalen Lib und PRs und sowas gewühlt ... hätte erwartet das auch schon bei Dir (erste) Logik drin ist für das Recurring zeug und das ich unter "recurrences" Die Ausnahmen (also weitere Events mit gleicher UUID) finde. Aber da ist nix ... hab debugging im recurring test beim Adapter eingebaut :-(
Any idea?

**Comment by 2000ede** [comment]
Hallo, 
ich weiss nicht, ob dies auch mein Problem ist.
Ich trage in einem google Kalender Geburtstage als jährlich wiederkehrende Termine (GANZTÄGIG) ein.
Gestern zeigte er mir diesen Termin dann als von "00:00-23:00" Uhr an.
Heute zeigt er mir den heutigen Termin unter "noch 1 Tag" an.

Könnt Ihr das bitte mal prüfen? Herzlichen Dank!
Ich gehe davon aus, dass das Problem nur bei wiederkehrenden Terminen besteht.

hier nochmal zu sehen: er erkennt 3 Termine für heute, weist aber zwei der drei unter "noch 1 Tag aus"
![grafik](https://user-images.githubusercontent.com/37264959/38130506-b03287ce-3403-11e8-9511-0c4aa4ea7c12.png)

**Comment by Apollon77** [comment]
Und aktuellste Version 1.5.2 glaube ich installieren!! Oder welche Version ist es bei dir?

**Comment by 2000ede** [comment]
ok, sorry, wollte keinen Doppelpost aufmachen.
jetzt angelegt: https://github.com/ioBroker/ioBroker.ical/issues/54

**Comment by Apollon77** [comment]
fixed by 1.6.2
