### ISSUE TITLE
node 14: warning im syslog

### ISSUE THREAD

**Issue by liv-in-sky** [iobroker-community-adapters/ioBroker.ical#330]
bekomme diese warnung im syslog wenn ical daten holt:

`Dec  5 10:30:13 iobroker59 bash[70469]: (node:70469) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency
Dec  5 10:33:01 iobroker59 bash[71367]: (node:71367) Warning: Accessing non-existent property 'count' of module exports inside circular dependency
Dec  5 10:33:01 iobroker59 bash[71367]: (Use `node --trace-warnings ...` to show where the warning was created)
Dec  5 10:33:01 iobroker59 bash[71367]: (node:71367) Warning: Accessing non-existent property 'findOne' of module exports inside circular dependency
Dec  5 10:33:01 iobroker59 bash[71367]: (node:71367) Warning: Accessing non-existent property 'remove' of module exports inside circular dependency
Dec  5 10:33:01 iobroker59 bash[71367]: (node:71367) Warning: Accessing non-existent property 'updateOne' of module exports inside circular dependency`

**Comment by Apollon77** [comment]
Please check mongodb paket version ... thjis is the reason. See also js.controller 4.0 Stable update thtreda FAQ

**Comment by liv-in-sky** [comment]
fehler scheint weg zu sein

habe beim holen von ical nun **viele** dieser meldungen

`
Mar  7 16:26:31 iobroker59 bash[189864]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Mar  7 16:26:31 iobroker59 bash[189864]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Mar  7 16:26:31 iobroker59 bash[189864]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Mar  7 16:26:31 iobroker59 bash[189864]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Mar  7 16:26:31 iobroker59 bash[189864]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Mar  7 16:26:31 iobroker59 bash[189864]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
Mar  7 16:26:31 iobroker59 bash[189864]: Using TZID without Luxon available is unsupported. Returned times are in UTC, not the requested time zone
`

habe das gefunden - https://stackoverflow.com/questions/64299310/rrule-using-tzid-without-luxon-available-is-unsupported

ist die info wichtig - wenn nicht, kannst du gerne "closen"

**Comment by liv-in-sky** [comment]
achso - ist ja schon "geclosed"
