### ISSUE TITLE
Kalender wird ignoriert

### ISSUE THREAD

**Issue by Parodontitis** [iobroker-community-adapters/ioBroker.ical#338]
**Describe the bug**  
Kalender wird eingelesen aber keine Werte in die Datenpunkte eingetragen. Gilt nur für diese Kalender-Typen/Quelle. Andere Kalender (nextcloud o.ä) funktionieren bei mir.

Es werden entsprechende Dateien in /opt/iobroker/node_modules/iobroker.ical/18375191f7440413133... generiert, aber der Datenpunkt ical.1.data.html bleibt leer. Tagesvorschau habe ich auf 20 hochgestellt.

**To Reproduce**  
https://www.worms.de/de/web/ebwo/abfallkalender/2021/ical.php?id=4ca5c7e9a80c81206.90149618
https://www.worms.de/de/web/ebwo/abfallkalender/2022/ical.php?id=4ca5c7e9a80c81206.90149618

**Versions:**  
 - Adapter version: 1.11.6
 - JS-Controller version:  3.3.22
 - Node version: v12.22.5
 - Operating system: debian

**Additional context**  
Problem tritt seit ca 3 Wochen auf.

**Funktionierender Kalender**
Wenn ich die Ical-Datei in Nextcloud importiere und und den Calender in Iobroker importiere, dann wird alles richtig angezeigt. So sieht die funktionierende Datei aus:

```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:Abfall 2022
X-APPLE-CALENDAR-COLOR:#499AA2
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VEVENT
UID:20211223T124627Z-61c461930b0a41.79210387@worms.de
SUMMARY;CHARSET=UTF-8:Restmüll Abholung - Gaustraße 97-165\; 96-210
DESCRIPTION:Ein Service des Entsorgungs- und Baubetrieb der Stadt Worms - S
 tand: 23.12.2021 12:46
CLASS:PUBLIC
DTSTART;VALUE=DATE:20220420
DTSTAMP:20211223T124627Z
END:VEVENT
BEGIN:VEVENT
UID:20211223T124627Z-61c461930b15e0.57936468@worms.de
SUMMARY;CHARSET=UTF-8:Restmüll Abholung - Gaustraße 97-165\; 96-210
DESCRIPTION:Ein Service des Entsorgungs- und Baubetrieb der Stadt Worms - S
 tand: 23.12.2021 12:46
CLASS:PUBLIC
DTSTART;VALUE=DATE:20221129
DTSTAMP:20211223T124627Z
END:VEVENT
```

**Ignorierter Kalender**
So sieht die ignorierte Datei aus:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Stadt Worms//ebwo Abfallkalender//EN
METHOD:PUBLISH


BEGIN:VEVENT
UID:20211223T130313Z-61c46581548585.20207021@worms.de
SUMMARY;CHARSET=UTF-8:Gelbe Tonne Abholung - Gaustraße 97-165; 96-210
DESCRIPTION:Ein Service des Entsorgungs- und Baubetrieb der Stadt Worms - Stand: 23.12.2021 13:03
CLASS:PUBLIC
DTSTART;VALUE=DATE:20220107
DTSTAMP:20211223T130313Z
END:VEVENT


BEGIN:VEVENT
UID:20211223T130313Z-61c465815486f4.83445781@worms.de
SUMMARY;CHARSET=UTF-8:Gelbe Tonne Abholung - Gaustraße 97-165; 96-210
DESCRIPTION:Ein Service des Entsorgungs- und Baubetrieb der Stadt Worms - Stand: 23.12.2021 13:03
CLASS:PUBLIC
DTSTART;VALUE=DATE:20220121
DTSTAMP:20211223T130313Z
END:VEVENT
```

**Comment by MarcoLaser** [comment]
Habe das gleiche Problem, aber nur mit Version 1.11.5 oder .6.
Geht bei mir auch um nen [Abfallkalender](https://wbl.de/pdf/ical2022.php?t=1640021970&strasse=Zum+Pier&no_behaelter_14=0&no_container_14=1&no_behaelter_4=1&no_container_4=1&no_gelb=0&no_gelb_container=1&no_bio=0&no_papier=0&no_papier_container=1) 
Auf Debug zeigt er mir Folgenden Fehler nach dem Auslesen des Links
`{"<b>fatal error</b>":" Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'd00373fc'@'127.0.0.1' (using password: YES) in /www/htdocs/w0077a9f/relaunch2020.wbl.de/pdf/ical2022.php:28","stack trace":"","#0 /www/htdocs/w0077a9f/relaunch2020.wbl.de/pdf/ical2022.php(28)":" PDO-&gt;__construct('mysql:dbname=d0...', 'd00373fc', 'wbl2006DB')"}`
In Version 1.11.4 geht der gleiche Link ohne Probleme

**Comment by Apollon77** [comment]
Hm ... also dann bekommt der adapter das ics File gar nicht ... und der Fehler kommt eher vom server als von irgendwas anderem. ALso wnen ich im Browser die obige URL aufrufe bekomme ich exakt den gleichen Fehler. Da hat der Webserver der das File anbietet gerade ein problem!

**Comment by MarcoLaser** [comment]
Okay stimmt scheinbar war da gestern wirklich ein Server Problem bei denen aber jetzt läuft es wieder aber immer noch keine Ergebnisse unter der neuen Version nur mit 11.4
Kommt keine Fehlermeldung mehr, nur da wo er den Inhalt der ics anzeigen sollte nur {}

**Comment by Apollon77** [comment]
Dann mal Debug log bitte

**Comment by MarcoLaser** [comment]
checkICal: endpreview - Fri Feb 11 2022 18:00:34 GMT+0100 (Central European Standard Time)
--
ical.0 | 2022-01-02 18:00:34.166 | debug | checkICal: startpreview - Sun Jan 02 2022 00:00:00 GMT+0100 (Central European Standard Time)
ical.0 | 2022-01-02 18:00:34.165 | debug | {}
ical.0 | 2022-01-02 18:00:34.163 | info | processing URL: Müll 22 https://wbl.de/pdf/ical2022.php?t=1640021970&strasse=Zum+Pier&no_behaelter_14=0&no_container_14=1&no_behaelter_4=1&no_container_4=1&no_gelb=0&no_gelb_container=1&no_bio=0&no_papier=0&no_papier_container=1
ical.0 | 2022-01-02 18:00:34.153 | debug | File read successfully https://wbl.de/pdf/ical2022.php?t=1640021970&strasse=Zum+Pier&no_behaelter_14=0&no_container_14=1&no_behaelter_4=1&no_container_4=1&no_gelb=0&no_gelb_container=1&no_bio=0&no_papier=0&no_papier_container=1
ical.0 | 2022-01-02 18:00:34.152 | debug | Successfully cached content for calendar "https://wbl.de/pdf/ical2022.php?t=1640021970&strasse=Zum+Pier&no_behaelter_14=0&no_container_14=1&no_behaelter_4=1&no_container_4=1&no_gelb=0&no_gelb_container=1&no_bio=0&no_papier=0&no_papier_container=1" as /opt/iobroker/node_modules/iobroker.ical/ae82767810017d52766ebe1998af37cb
ical.0 | 2022-01-02 18:00:33.990 | debug | reading calendar from URL: https://wbl.de/pdf/ical2022.php?t=1640021970&strasse=Zum+Pier&no_behaelter_14=0&no_container_14=1&no_behaelter_4=1&no_container_4=1&no_gelb=0&no_gelb_container=1&no_bio=0&no_papier=0&no_papier_container=1, color: #000000

**Comment by Apollon77** [comment]
Den gehört das Issue eher in die node_ical Lib ... Weil die parst das File nicht

**Comment by MarcoLaser** [comment]
Hab ich mir schon gedacht, dann Versuche ich es da nochmal. Welche Version hat denn die 11.4 benutzt? Dann kann ich es da abgeben

**Comment by Apollon77** [comment]
0.13.0 war es ... inzweiachen ist es 0.14.1

**Comment by Apollon77** [comment]
Bitte hier offen assen Und Issues verlinken ... Danke!

**Comment by r-kane** [comment]
Ich verweise hier gerne auf mein Ticket https://github.com/iobroker-community-adapters/ioBroker.ical/issues/324 im Bezug auf 1.11.5. Klingt zumindest nach dem, was ich seit November habe. Aktuell muss ich bei 1.11.4 bleiben, damit der Kalender eingelesen wird.

**Comment by MarcoLaser** [comment]
Was mich etwas wundert ist dass wir beide aus Lünen sind und sonst kaum andere Leute Probleme haben. Vielleicht hat auch die WBL da etwas was mit der neuen Version nicht kompatibel ist.

**Comment by Parodontitis** [comment]
Ist es schlimm, wenn ich nicht aus Lünen komme und trotzdem das Problem habe? ;-)

**Comment by Apollon77** [comment]
Wenn einer von euch mal versuchen will eine regex zu ändern ob es and er liegt dann bitte :-))

Am Ende müstet Ihr malk diese Änderung in node-ical rückgängig machen https://github.com/jens-maus/node-ical/commit/45792f5e2bb7aa6d24993cee82342ffb7da5a068#diff-a717da36dca416b92146c74d0e6a1cae778967192eda55915710200af50ec829

Also effektiv auf eurem host:
* `cd /opt/iobroker`
* `find .name ical.js`
* Dann da gefundene vile (müsste in einem node_ical oderner liegen) ändern und diese eine zeile zurück ändern.

Dann adapter neu starten ... gehts dann?

**Comment by Parodontitis** [comment]
Ja. Wenn die Änderung rückgängig mache, dann werden die Termine wieder erkannt!

2022-03-19 17:23:57.805  - info: ical.1 (24210) starting. Version 1.11.6 in /opt/iobroker/node_modules/iobroker.ical, node: v12.22.5, js-controller: 4.0.21
2022-03-19 17:23:58.119  - info: ical.1 (24210) processing URL: Abfall1 https://www.worms.de/de/web/ebwo/abfallkalender/2022/ical.php?id=4ca5c7e9a80c81206.90149618
2022-03-19 17:23:58.126  - info: ical.1 (24210) Set events.12.Gelbe to true
2022-03-19 17:23:58.131  - info: ical.1 (24210) Set events.13.Gelbe to true
2022-03-19 17:23:58.140  - info: ical.1 (24210) Set events.8.Altpapier to true
2022-03-19 17:23:58.144  - info: ical.1 (24210) Set events.9.Altpapier to true
2022-03-19 17:23:58.152  - info: ical.1 (24210) Set events.3.Restmüll to true
2022-03-19 17:23:58.162  - info: ical.1 (24210) Set events.10.Biomüll to true
2022-03-19 17:23:58.165  - info: ical.1 (24210) Set events.11.Biomüll to true

**Comment by Apollon77** [comment]
Thank you, so thats the wrkaround for now until we have a fix in node_ical, lets see what comes out there https://github.com/jens-maus/node-ical/issues/173#issuecomment-1073055297

**Comment by Apollon77** [comment]
Fixed on GitHub
