### ISSUE TITLE
Farbe rot für Termin bis ....

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.ical#34]
Wenn ein Termin länger dauert (z.b. über mehrere Tage; also z.b. bis 14.01. Weihnachtsferien)
Dann sollte dieser Termin auch rot eingefärbt sein; denn er trifft ja heute zu.
(aktuell: White).

**Comment by Apollon77** [comment]
Hier ist es so das schon die ganze Zeit Termine die früher gestartet sind und noch laufen (früher als aktueller tag 0:00) in der definierten Farbe und mit css klasse "icalNormal" (Zeitangabe) bzw "icalNormal2" (Text) dargestellt werden. Also auch hier per CSS manipulierbar.

Passt das so mit den Foruminfos?

**Comment by Apollon77** [comment]
Idee/Frage: http://forum.iobroker.net/viewtopic.php?f=36&t=9981&p=108012#p108012 ?!

**Comment by bahnuhr** [comment]
Auch hier: mach zu.
css oder Script; dann passt es.

mfg
Dieter

**Comment by Apollon77** [comment]
Idee/Frage: http://forum.iobroker.net/viewtopic.php?f=36&t=9981&p=108012#p108012 ?!

**Comment by Apollon77** [comment]
Doku CSS im README drin: https://github.com/ioBroker/ioBroker.ical/tree/master#css
