### ISSUE TITLE
Datenpunkte im Baum Later werden nicht aktualisiert

### ISSUE THREAD

**Issue by Siggi0904** [iobroker-community-adapters/ioBroker.ical#340]
Mit der aktuellen Stable-Version werden die Datenpunkte im Baum ical.0.events.0.later nicht aktualisiert.
Im Baum ical.0.events.0.now und ical.0.events.0.today ist alles richtig.
Siehe:
![grafik](https://user-images.githubusercontent.com/4992106/147567231-ac61c583-3f43-49b5-80e3-0b8aaf6e6883.png)

Der Zeitstempel aus later für 3.Schict liegt irgendwo im August, bei now und today passt es zum ersten auftretenim Kalender.

Danke für das Reparieren.

**Comment by Apollon77** [comment]
Kannst Du bitte mal die Beta Version testen? (Via Admin be CUstom install der erste tab)

**Comment by Siggi0904** [comment]
Hallo, da ich aktuell nur das Produktiv-System habe, würde ich dies ungern durchführen.
Danke.

**Comment by Feuer-sturm** [comment]
Ich kann heute abend mal schauen ob ich das Verhalten bei mir auch sehe und dann die neue github Version testen @Apollon77

**Comment by Feuer-sturm** [comment]
@Siggi0904 Hast du ein paar mehr Details zu deinem Termin, welcher die Probleme bereitet?
Ist es ein Serientermin, ganztägig oder von x:xx bis y:yy Uhr

Warum sollte der Termin "3Schicht" auch bei later auf true stehen, wenn er gerade anliegt (now = true)?

**Comment by Siggi0904** [comment]
Der Termin "3Schicht" ist ein ganztagstermin, der von Montag bis Samstag reicht.

Es kann ja auch sein, dass ich later falsch verstehe.
Ich verstehe hierbei nicht, wann later greift.
Scheinbar nur, wenn es ein Termin am Tag mit einem Zeitraum ist.

**Comment by Feuer-sturm** [comment]
@Siggi0904 Dazu müsste am besten @Apollon77 was sagen wie sich "later" verhalten soll.

So wie ich das hier https://github.com/iobroker-community-adapters/ioBroker.ical/blob/9ad2a943e559b204828b88841cb43ac4dfb27352/main.js#L668 verstehe, wird "later" nur dann gefüllt, wenn der Termin später als Jetzt beginnt

Siehst du bei ganztägiten Terminen einen Mehrwert, wenn hier later auch noch auf true gesetzt wird?

**Comment by Apollon77** [comment]
Exakt. Later ist "nicht begonnen" weil sonst wäre es "now" :-)

**Comment by Feuer-sturm** [comment]
Damit wäre es ein "works as designed"

**Comment by Siggi0904** [comment]
Okay, so verstehe ich das auch.

Dann sollte das eventuell im readme nochmal erklärt werden.
Entsprechend der Termintypen (Zeit, ganztags, mehrere Tage und Serientyp) könnte das dann zum besseren Verständnis beitragen.

**Comment by Apollon77** [comment]
@Siggi0904 Darf ich dich bitten da einen readme vorschlag als PR zu machen (Du nutzt das mehr als ich). Ist auch ganz simpel im Browser: geh hier im Repo auf README.md und auf den Stift oben rechts ... füge das hinzu was sinn macht und dann runterscrollen und "änderung vorschlagen"

**Comment by Siggi0904** [comment]
Naja, bis auf meine paar Ganztagstermine habe ich ja auch nichts.
Aber ich schau mir das heute Abend an.

**Comment by Apollon77** [comment]
@Siggi0904 Immer noch geplant? :-))

**Comment by Siggi0904** [comment]
Wenn ich wüsste wie. Ich habe bisher nur zwei Ganztagstermine verwendet.

**Comment by Apollon77** [comment]
@Feuer-sturm kannst du ggf das in der Doku mit übernehmen?

**Comment by Feuer-sturm** [comment]
Bin schon dabei :-)
https://github.com/Feuer-sturm/ioBroker.ical/blob/readme-ical-update/docs/de/README.md
Ist im Abschnitt "Erklärung zu den States unter ical.0.events.0" aufgeführt

**Comment by Feuer-sturm** [comment]
Doku wird mit dem PR https://github.com/iobroker-community-adapters/ioBroker.ical/pull/389 aktualisiert. 

@Apollon77 issue kann dann hier geschlossen werden.
