### ISSUE TITLE
Write a new calendar entry

### ISSUE THREAD

**Issue by maxpd1** [iobroker-community-adapters/ioBroker.ical#346]
Hi,

at the moment it is only possible to read calendar entries. But is it planned to also write calendar entries?

For example if I changed the bed sheets I want to give my google home a signal and an automatical entry in calendar should be created in 14 days to indicate next schedule for changing the sheets.

Regards maxpd

**Comment by jens-maus** [comment]
Nope, this is IMHO out of the scope of the current ioBroker.ical adapter. However, feel free to contribute by sending in a pull request if you identify a way to implement this.
