### ISSUE TITLE
bold oder eben nicht

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.ical#35]
- Textdarstellung in bold oder eben nicht.
aktuell: Date und time bold; Event nicht bold.

Wünschenswert wäre:
alles in bold oder eben nicht.

P.S.
Eine Steuerung wie sonst mit dem widget unter Fonds funktioniert nicht.
Warum geht das denn nicht ?

**Comment by Apollon77** [comment]
Ich schaue mal, kann aber nichts versprechen. Der Adapter generiert sonst mit css Klassen und was passiert ist dann im vis widget drin... oder so ... das ist damit nicht ganz so simpel und vis/Widgets ist für mich immer noch Buch mit 7 Siegeln ...

**Comment by bahnuhr** [comment]
Ist für mich nicht so schlimm.
Dann lass ich halt zusätzlich noch das andere Script drüber laufen.
(ohne Script wärs halt schöner)

**Comment by jens-maus** [comment]
Also ich muss auch sagen das so langsam die änderungswünsche überhand nehmen. Vor allem da die meist nur stilistischer natur sind und solche dinge sollten in der tat mit css&co von jedem nutzer selbst umgesetzt werden IMHO.

**Comment by Apollon77** [comment]
Der Adapter müsste es aber html technisch „enablen“ ... aber wie gesagt ich bin nicht der html-ler :-(

**Comment by bahnuhr** [comment]
@jens: ... Also ich muss auch sagen das so langsam die änderungswünsche überhand nehmen. ....

War doch so gewünscht. Und wenn ich teste, dann könnt ihr doch von mir erwarten, dass ich alles hinschreibe was mir auffällt.

**Comment by bahnuhr** [comment]
@jens: ... solche dinge sollten in der tat mit css&co von jedem nutzer selbst umgesetzt werden ....

Das glaube ich nicht; die Anzahl dieser Nutzer ist m.E. verschwindend gering.

**Comment by Apollon77** [comment]
Ja ich hatte um Feedback gebeten. Aus Sicht der User ist der iCal Adapter lange „vernachlässigt“ worden und ich wollte die Chance nutzen wenigstens zu sammeln. Sammeln heißt nicht das auch alles umgesetzt werden muss ;-) aber man hat einen stand und kann bewusst entscheiden etwas ggf nicht zu tun. 

Das „alles geht per css“ ist so ein Thema ... einerseits stimme ich zu wenn der Adapter das vom html her erlaubt. Andererseits ist einer der Zielsetzungen von ioBroker das man sowas nur für wirklich eigene Wünsche braucht und die sinnvollen standardfeatures „simpel konfigurierbar“ sind. 
Die Grundfrage ist dabei immer wo die Grenze ist ... und die sieht jeder pot. anders ... die Wahrheit liegt irgendwo in der Mitte. 

Wenn Dinge per css gehen kann vllt auch ein Profi wir du Jens nen Tipp geben wie das hier mit css zu machen ist. Dann kann man das auch so zu machen.

**Comment by bahnuhr** [comment]
.... Wenn Dinge per css gehen kann vllt auch ein Profi wir du Jens nen Tipp geben wie das hier mit css zu machen ist. ....

Ja, das würde mich auch interessieren.

**Comment by bahnuhr** [comment]
Im Forum hat diesbezüglich gerade jemand bzgl. css geantwortet.

**Comment by Apollon77** [comment]
Ja wenn das sooooo einfach ist ;-))

Packe es als Beispiel in die Adapter readme

**Comment by bahnuhr** [comment]
Mach hier zu.
Wenn jemand dies ändern möchte, dann soll er css nehmen.
Oder wie ich ein Script in iobroker.
mfg
Dieter

**Comment by Apollon77** [comment]
Doku CSS im README drin: https://github.com/ioBroker/ioBroker.ical/tree/master#css
