### ISSUE TITLE
Adapter schaltet bei Kalender Event nicht

### ISSUE THREAD

**Issue by Platti26** [iobroker-community-adapters/ioBroker.ical#355]
**Describe the bug**  
Der Adapter liest meinen Kalender problemlos ein. Auch die Objekte (today, now etc) werden korrekt gesetzt.
Sobald der Termin im Kalender aktiv ist, wird auch im Log eingetragen. Allerdings wird nicht geschaltet.

Einmal hatte ich Erfolg, indem ich den Eintrag im für das Ereignis im ical Adapter gelöscht und neu angelegt hatte, während ein Termin aktiv war. Der nachfolgende Test funktionierte leider wieder nicht.

![image](https://user-images.githubusercontent.com/24937780/151710820-22a0d0b9-8e4f-4df7-bdfa-1d6fda29f5f5.png)

Über die Objekte und auch andere Adapter lässt sich das Gerät problemlos schalten.

**Versions:**  
 - Adapter version: v1.11.6
 - JS-Controller version:  3.3.2
 - Node version:  14.18.3
 - Operating system: Raspbian GNU/Linux 10 (buster)

**Comment by Apollon77** [comment]
yes, will be fixed once #322 is merged

**Comment by Apollon77** [comment]
Please check GitHub version. The events table should now include a checkbiox to define if ack is set or now (not = control). Please try it out and give feedback

**Comment by Platti26** [comment]
Hi Ingo,

unfortunately it does not work with running version 1.11.6.
I have an thermostat (HmIP-BWTH) connected with Raspberry Matic. If I create an event in google calendar, the objects are correct for today (true) and now (false). If the event starts, the objects are changed to today=false and now=true. But Nothing else happend. The values of the thermostat was not changed. I used 23.5 degrees and 21.5 degrees, but for testing I used integer values as well. But the same result.

Than I created an 2nd Event for  an shelly device. The values are on=true and off=false. In this case the values in the objects was also correct after restart the ical instance, but when the event starts, the values of today and now are not changed and nothing happened again.

How I can support you.

Kind regards!

 

Thomas Platter

An den Kopfweiden 19
14473 Potsdam

Tel: 0331-87006277
Mob: 0151-18820039

Von: Ingo Fischer
Gesendet: Samstag, 19. März 2022 13:56
An: iobroker-community-adapters/ioBroker.ical
Cc: Platti26; Author
Betreff: Re: [iobroker-community-adapters/ioBroker.ical] Adapter schaltet beiKalender Event nicht (Issue #355)

Please check GitHub version. The events table should now include a checkbiox to define if ack is set or now (not = control). Please try it out and give feedback
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Feuer-sturm** [comment]
@Apollon77 
Checkbox is available
![grafik](https://user-images.githubusercontent.com/25422320/159138965-db974877-5616-4ae3-99bb-b07f574316ff.png)

And depending on the checkbox this value is different.
![grafik](https://user-images.githubusercontent.com/25422320/159139000-2cffbdc8-b268-42e3-bbea-e91a565c4b24.png)
![grafik](https://user-images.githubusercontent.com/25422320/159139025-6d9b2b1c-6637-4182-9513-8ed085f5281e.png)

I juste made a check on this level.

**Comment by Feuer-sturm** [comment]
@Platti26 Did you install the github version of ical adapter?
Please remove your private address from your comment ;-)

**Comment by Platti26** [comment]
I think so, that was my way:

**Comment by Platti26** [comment]
Yes, it is.

**Comment by Apollon77** [comment]
@Platti26 sending emails will not integrate any attachements.

So did aoxu also configured the events to NOT set the ack flag?? Check out the config. There is a new Comlumn in the table called "ack"

**Comment by Platti26** [comment]
It works! I tested with the ack flag is turned off now. It was a little bit confused, that the change of the status only occurs, when the cronjob runs. But now it is clear and normally not an problem. Only if I test with less time between on and off.

Thanks!

**Comment by Apollon77** [comment]
Yes "cron" adapter can only do something when they run.
