### ISSUE TITLE
Color für gesamte Zeile

### ISSUE THREAD

**Issue by bahnuhr** [iobroker-community-adapters/ioBroker.ical#36]
- colorfarbe des Textes in Kalenderfarbe in Google
dann aber auch alles: Date, time und Event.
(aktuell: nur Event oder nur Date (bei heute, morgen, übermorgen))

**Comment by Apollon77** [comment]
Also so wie es vorher war?!

**Comment by jens-maus** [comment]
Wie gesagt, mach css klassen für jeden teil und dann soll das jeder für sich so machen wie er will. Persönlich fand ich z.b. Die colorierung des gesamten termins mit der gleichen farbe für mich am besten und zraue mich aktuell nicht ein update des adapters zu machen weil och schon vor lauter bearebiteter änderungstickets nicht mehr durchblicke was mich da jetzt beim update erwartet...

**Comment by bahnuhr** [comment]
.... Persönlich fand ich z.b. Die colorierung des gesamten termins mit der gleichen farbe für mich am besten ...

Ich seh das auch so.
Und ... selber entscheiden... find ich noch besser.

mfg

**Comment by Apollon77** [comment]
Im Forum würde durchaus diskutiert das es wie jetzt (also darum/Zeit farbig, Rest weiß) besser lesbar ist. Aber schon da sind wir in der Geschmackssache. 
Das ist aber einfach zu lösen durch ändern der span verschachtelung (war vorher kaputt, zwei Spans gingen nie zu) ?!

Wenn hier flexible css Lösung gewünscht müsste es jemand anders umsetzen. Ich würde Setting machen was Spans anders verschachtelt.

**Comment by Apollon77** [comment]
@jens-maus: es erwarten dich viele fixes und  ein paar neue Features. Alles in den github issues und im Forum mit anderen usern diskutiert. Teste es und gib Feedback. 

Technisch habe ich adaptertests eingebaut die prüfen ob Dinge korrekt generiert werden. Support bräuchte ich noch bei einem recurring Thema ... siehe issues. Das ist eher ein Node-iCal Thema denke ich.

**Comment by jens-maus** [comment]
Das hab ich schon wahrgenommen, bin allerdings zur zeit busy und komme gerade nicht dazu mir das anzuschauen. Müsste erstmal schauen ob ein merge von node-ical mit upstream schon Verbesserung bringt. Leider gibt es da inzwsichen zuviele forks davon das da momentan schwer ist das chaos in der Entwicklung dieses node modules zu durchschauen..

**Comment by Apollon77** [comment]
Jupp dabei in ich auch gescheitert und habe für jetzt abgebrochen. Wenn ich mal ganz viel Muse habe vllt ein zweiter Anlauf ;-)

Ich hab im Adapter, so wie ich verstanden hatte das es im Node-iCal Return object zurück kommen sollte, mal Debug log eingebaut. Somit könnte man recht simpel nach einem Update der lib sehen ob es jetzt korrekt drin ist.

**Comment by Apollon77** [comment]
@bahnuhr: Mit den CSS Tips aus dem Forum ist das ok ?! Dann würde ich das in die DOku aufnehmen und hier zu machen

**Comment by Apollon77** [comment]
Idee/Frage: http://forum.iobroker.net/viewtopic.php?f=36&t=9981&p=108012#p108012 ?!

**Comment by bahnuhr** [comment]
mit den css muss ich mir noch anschauen.
Wenn du der Meinung bist, es ist gut so dann mach hier zu.
Momentan lass ich dieses Script noch drüber laufen.
Sieht bei mir jetzt so aus, wie ich es haben will.
Danke für deine Arbeit.

mfg
Dieter

**Comment by Apollon77** [comment]
Idee/Frage: http://forum.iobroker.net/viewtopic.php?f=36&t=9981&p=108012#p108012 ?!

**Comment by Apollon77** [comment]
Doku CSS im README drin: https://github.com/ioBroker/ioBroker.ical/tree/master#css
