### ISSUE TITLE
now Event not working properly

### ISSUE THREAD

**Issue by aski71** [iobroker-community-adapters/ioBroker.ical#366]
I added an event in my calendar for 18:35 - 18:45.
The respective object in now did not switch to true at 18:35 but around 18:37. And it switched back to false within about a minute.

**Versions:**  
 - Adapter version: 1.11.6
 - JS-Controller version: 4.0.5
 - Node version: 16.14.0
 - Operating system: Ubuntu 18.04.6

**Comment by Apollon77** [comment]
Provide debug logs please from such tries

**Comment by aski71** [comment]
Will try to reproduce.
I had another successful try yesterday later in the evening when specifiying an event from 21:00 - 21:20.
Weird.

**Comment by Apollon77** [comment]
Please reopen if reporoducable
