### ISSUE TITLE
Feiertag (heute) wird angezeigt als "noch 1 Tag

### ISSUE THREAD

**Issue by looxer01** [iobroker-community-adapters/ioBroker.ical#37]
Hi,
Ich habe festgestellt, dass ein ganztägiger Termin (hier ein Feiertag) statt als "heute" angezeigt wird als "noch 1 Tag"

vG Looxer

![ical1](https://user-images.githubusercontent.com/11609655/34461092-49bd01b2-ee22-11e7-86ba-bdd1e45afdf6.JPG)

**Comment by Apollon77** [comment]
Ja so ist das wenn man keine Datumsangabe haben will ;-)
War an sich schon immer so denke ich. Öde stand bisher immer „today“ da auch wenn bereits begonnen war?

Welche Anzeige hättest du erwartet?

Wenn du nicht „Zeitangabe ausblenden“ gewählt hast sollte ab 12 Uhr mittags eher „x Stunden übrig“ angezeigt werden.

**Comment by jens-maus** [comment]
Das ist mir auch bereits aufgefallen. Hier sollte meiner Meinung nach statt „Noch 1 Tag“ immer „Noch X Stunden“ erscheinen für die dauer die der Termin noch gültig ist...

**Comment by jens-maus** [comment]
Und dann wenn <1 Std am besten „Noch X Minuten“...

**Comment by Apollon77** [comment]
Nochmal geschaut. Bisher Stand dort „heute“ und so habe ich es jetzt wieder gemacht. 

„Noch x Stunden“ würde auch gehen, aber hätte je nach schedule des Adapters teils falsche Werte. „X Minuten“ erst recht. Daher siehe oben ;-)

**Comment by looxer01** [comment]
super, jetzt steht es wieder auf "Heute". Aus meiner Sicht hat es keinen Sinn gemacht bei einem ganztägigen Termin die Stunden bis zum Tagesende zu zählen :)
Jetzt ist es gut.

vG

**Comment by Apollon77** [comment]
testing auch wieder gron, ich wäre damit erst mal durch - ausser CSS Doku sobald es nochmal im Forum Feedback gab :-)
