### ISSUE TITLE
iCloud Calendar not working anymore

### ISSUE THREAD

**Issue by Marty56** [iobroker-community-adapters/ioBroker.ical#381]
**Describe the bug**  
I am reading two iCloud calendars which has been working fine for many months.

**To Reproduce**  
When ical tries to access the iCloud Calendars, it receives the following warning
```
Error reading "https://p56-caldav.icloud.com/published/2/xxxxxx": Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://p56-caldav.icloud.com/published/2/xxxxxx
```

. xxxxxx is masking my key.

I have double checked the url, and it has not changed and is correct.
No data is received and all data points are empty.

**Expected behavior**  
read iCal calendar without warnings.

**Versions:**  
 - Adapter version: 1.11.4
 - JS-Controller version: 4.0.19
 - Node version: v14.19.0 
 - Operating system: debian

**Additional context**  
Google Calendar ist working ok.

**Comment by Apollon77** [comment]
Csan you open the same URL in your browser to get the ical file?

**Comment by Marty56** [comment]
Ich bekomme im Browser sinngemäß dieselbe Fehlermeldung, nämlich, dass zu viele Umleitungen aufgetreten sind und dies möglich sei, wenn eine geöffnete Seite auf eine andere Seite umleitet, die wiederum auf die Ursprungsseite verweist.

Sieht nach einem Apple Bug aus, oder?

**Comment by Apollon77** [comment]
Exakt, wenn der Brower es nicht anzeigt dann hat der Adapter genauso wenig eine chance

**Comment by Marty56** [comment]
Ich habe die Ursache gefunden, z.B. einen Workarround für den Apple Bug.

Bei den Kalendern handelte es sich um den Müllentleerungs- und den Schulferienkalendar. Beide Kalendar hatten Termine von über 3 Jahren. Und das war iCloud wohl zu viel.
Ich habe beide Kalender gelöscht und neu angelegt und dann nur die Termine des aktuellen Jahres importiert.
Dann natürlich noch die URLs im Adapter neu eingetragen.

Danach konnte ich die Kalendar sowohl im Browser als auch im iCal Adapter öffnen.

**Comment by firebowl** [comment]
Hab das gleiche Problem aber ich frage nur einen Kalender ab und es gibt auch nur Termine aus diesem Jahr. Ist bei mir auch ein Müllkalender für Restmüll, Altpapier und gelbe Tonne. Sind aber bestimmt nicht mehr als 100 Einträge und es sind auch nicht mehr geworden von geht zu geht nicht mehr. :(

**Comment by Apollon77** [comment]
Effektiv ist es aber so: Wenn auch der Browser es nicht anzeigt hat der Adapter keine Changce ... mal Apple abschreiben? ;-)

**Comment by firebowl** [comment]
Also abschreiben möchte ich Apple nicht, anschreiben könnte ich die mal aber wer den Apple Support kennt... ;)

**Comment by firebowl** [comment]
Ich warte einfach mal ein paar Tage oder Wochen, den neuen Plan bekomme ich erst Ende des Jahres und bis dahin ändert sich nix. ;)

**Comment by hail0** [comment]
Hi zusammen,

ich bekomme die gleiche Fehlermeldung wie die Herrschaften über mir:

`Error reading "http://p71-caldav.icloud.com/published/XXXXXXXXXX": Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://p39-caldav.icloud.com/published/XXXXXXXXX`

Wenn ich allerdings die Kalender URL aufrufe, bekomme ich die .ics Datei heruntergeladen.

Woher könnte die Fehlermeldung noch stammen?

Danke und VG!
