### ISSUE TITLE
Adapter stopped working with iCloud calendar - maxRedirects

### ISSUE THREAD

**Issue by firebowl** [iobroker-community-adapters/ioBroker.ical#386]
Since a few days the adapter can no longer fetch events from a shared iCloud calendar.

Error reading "https://p72-caldav.icloud.com/published/2/xxxxx": Error: Exceeded maxRedirects. Probably stuck in a redirect loop https://p72-caldav.icloud.com/published/2/xxxxx

**Comment by Apollon77** [comment]
Does it work if you try this in your browser? If not then it is an issue of the URL or of apple ...

Maybe this helps? https://github.com/iobroker-community-adapters/ioBroker.ical/issues/381
