### ISSUE TITLE
Der Datenpunkt "ical.1.events.0.today" wird am Tag der Zeitumstellung falsch gesetzt

### ISSUE THREAD

**Issue by Marty56** [iobroker-community-adapters/ioBroker.ical#393]
**Describe the bug**  
Der Datenpunkt "ical.1.events.0.today" wird am Tag der Zeitumstellung von Winter auf Sommerzeit falsch gesetzt. Er zeigt die Werte für morgen an.

**Versions:**  
 - Adapter version: 1.11.4
 - JS-Controller version: 4.0.21
 - Node version: v14.19.0
 - Operating system: debian buster

**Comment by Feuer-sturm** [comment]
@Marty56 kannst du bitte einmal das Verhalten mit der aktuellen beta 1.12.1 prüfen ob dort das Problem auch noch existiert?

**Comment by Marty56** [comment]
Ich habe die Beta installiert und den ganzen Objektbaum gelöscht und dann ical gestartet.
Der Objektbaum wurde neu angelegt, aber ical.1.events.0.today ist immer noch falsch.

**Comment by Feuer-sturm** [comment]
@Marty56 danke

**Comment by Apollon77** [comment]
Dann brauche ich bitte ien volles Debug log mit genauen infos was genau falsch ist - am besten anhand eines einfache/minimalistischen beispiels

**Comment by Feuer-sturm** [comment]
@Marty56 Ich hab einmal meine Testeinträge / Events kontrolliert.
Bei mir sehe ich keine Auffälligkeit mit dem ical Adapter 1.12.1
![grafik](https://user-images.githubusercontent.com/25422320/160288982-f9360498-bc6a-420c-90e8-f9295748d8d1.png)


Was für ein Termin (Wiederholender Termin, Ganztägiger Termin, Termin mit Start, Endzeit) liegt heute bei dir an, der als Event falsch erkannt wird?

Poste bitte auch einmal Screenshots von deinen Einstellungen.

**Comment by Marty56** [comment]
Ich konnte gestern leider nichts mehr machen, weil ich nicht zuhause war.
Heute stimmen die Einträge wieder.
Sorry.
Vielleicht war es der Spezialfall, dass 1. Sommerzeit war und 2. zwei Geburtstage ganztägig eingetragen war.
Danke für Eure Mühe.
