### ISSUE TITLE
Ganztägiger Termin wird einen Tag zu früh angezeigt

### ISSUE THREAD

**Issue by DFS-90** [iobroker-community-adapters/ioBroker.ical#396]
Guten Morgen,

ich nutze als E-Mail-Server Kopano mit Kopano-ical 11.0.2 sowie ioBroker mit der aktuellsten Version dieses Plugins.
Das System, auf welchem Kopano läuft, hat die Zeitzone Europe/Berlin, diese ist auch in der Plugin-Konfiguration korrekt benannt

Die ioBroker-Info-Seite zeigt mir ferner das korrekte Datum sowie die korrekte Uhrzeit an.

Ich kann via ical-Schnittstelle meinen Kalender problemlos abfragen.
Zeitlich definierte Termine werden korrekt angezeigt und als Filter auch korrekt ausgewertet.

Ganztägige Termine, die ich in Outlook eingebe, werden im Kopano-Web-Interface korrekt angezeigt und vice versa.
Wenn ich im ioBroker-iCal-Plugin jedoch einen Filter für "Dienst WT" setze, wird mir dieser einen Tag zu früh angezeigt.

Dies ist ebenso in table bzw. text des Kalenders nachvollziehbar:
Mein Urlaub, den ich nicht filtere, erscheint dort für morgen (29.03.), obwohl dieser erst am 30.03. beginnt.

Anbei der Auszug aus der entsprechenden ical-Datei:

BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//Kopano//11.0.2//EN
CALSCALE:GREGORIAN
METHOD:PUBLISH
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:19700101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10;WKST=SU
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3;WKST=SU
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:UTC
BEGIN:STANDARD
DTSTART:19700101T000000
TZOFFSETFROM:+0000
TZOFFSETTO:+0000
END:STANDARD
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:Customized Time Zone
BEGIN:STANDARD
DTSTART:19700101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10;WKST=SU
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3;WKST=SU
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:(UTC+01:00) BrÃ¼ssel (Bruxelles\, Brussels)\, Kopenhagen 
 (KÃ¸benhavn)
BEGIN:STANDARD
DTSTART:19700101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;BYDAY=4SU;BYMONTH=10;WKST=SU
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3;WKST=SU
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:(UTC+01:00)
BEGIN:STANDARD
DTSTART:19700101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10;WKST=SU
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3;WKST=SU
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VTIMEZONE
TZID:(GMT +01:00)
BEGIN:STANDARD
DTSTART:19700101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10;WKST=SU
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:19700101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3;WKST=SU
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
TRANSP:TRANSPARENT
X-MICROSOFT-CDO-INTENDEDSTATUS:FREE
CREATED:20220328T083400Z
LAST-MODIFIED:20220328T083336Z
DTSTAMP:20220328T083336Z
DTSTART;VALUE=DATE:20220327
DTEND;VALUE=DATE:20220328
SUMMARY:Dienst WT
DESCRIPTION:\n
CATEGORIES:Dienst
CLASS:PUBLIC
UID:
 040000008200E00074C5B7101A82E00800000000600872568F42D801000000000000000010
 00000054EC19A8C0EA57479AE23CC0487DE50D
X-MOZ-SNOOZE-TIME:20220327T040000Z
X-MICROSOFT-CDO-OWNER-CRITICAL-CHANGE:20220328T090602Z
X-MICROSOFT-CDO-ATTENDEE-CRITICAL-CHANGE:20220328T090602Z
X-MICROSOFT-CDO-APPT-SEQUENCE:0
X-MICROSOFT-CDO-OWNERAPPTID:-1
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
BEGIN:VALARM
TRIGGER:-PT18H
ACTION:DISPLAY
DESCRIPTION:Reminder
END:VALARM

Ich habe gesehen, dass es bereits gelöste Anliegen mit ganztägigen Terminen gab, bin dort jedoch nicht fündig geworden.
Hat jemand eine Idee, wo das Problem liegt?

Vielen Dank und beste Grüße,
David

**Comment by Apollon77** [comment]
Bitte Verison von Beta bzw GitHub nutzen, da sollte das schon gefixt sein
