### ISSUE TITLE
Error: Exceeded maxRedirects. Probably stuck in a redirect loop

### ISSUE THREAD

**Issue by Trrw** [iobroker-community-adapters/ioBroker.ical#398]
Hallo,

leider bekomme ich seit Tagen diesen Fehler. "Error: Exceeded maxRedirects. Probably stuck in a redirect loop". Der Link zum iCloud Kalender funktioniert weiterhin. Also ich konnte den Kalender in einem anderen Programm hinterlegen.

Auf dem Screenshot sieht man den Fehler. Geschwärzt ist natürlich der iCloud Kalender

![Bildschirmfoto 2022-04-01 um 11 00 46](https://user-images.githubusercontent.com/24519230/161236591-6c0facbf-9a70-4cfb-b323-5571c332568b.png)

**Comment by Apollon77** [comment]
Can you open the file in a browse? If you also get that error you need to find the reason and check the link ... mybe same as https://github.com/iobroker-community-adapters/ioBroker.ical/issues/381 ?
