### ISSUE TITLE
Irreführende Darstellung bei ganztätigen Terminen.

### ISSUE THREAD

**Issue by pge** [iobroker-community-adapters/ioBroker.ical#40]
Follow-Up aus: http://forum.iobroker.net/viewtopic.php?f=20&t=10752&p=115384

Wenn ein ganztägiger Termin (z.b. am 18.1.2018) ansteht, wird dieser als:

--> 19.1.2018 

angezeigt. Das soll indizieren, dass der Termin am 19.1. endet, was ich aber für irreführend halte, da es sich ja um einen ganztägigen Termin am 18.1. handelt.

![bildschirmfoto 2018-01-18 um 10 04 43](https://user-images.githubusercontent.com/874616/35094799-b2e42b20-fc46-11e7-9562-bd57ad99fa53.png)
![bildschirmfoto 2018-01-18 um 11 53 37](https://user-images.githubusercontent.com/874616/35094805-b589305a-fc46-11e7-9910-381b65ed29d1.png)

**Comment by Apollon77** [comment]
@pge Is the screenshot from above from v1.4.0 of the adapter? I can not reproduce this
