### ISSUE TITLE
support of nextcloud tasks

### ISSUE THREAD

**Issue by Sigi74** [iobroker-community-adapters/ioBroker.ical#402]
Could you support Nextcloud tasks (reading and if possible writing) ? Would be great!

Thanks!

Ich benütze die Aufgabenliste (Task) in Nextcloud die auch über caldav mit dem Handy syncronisiert werde; 
Würde gerne die Daten auch in iobroker einlesen

**Comment by Apollon77** [comment]
Tasks sind aber nicht kalender?! und auch nicht ICS als Dateiformat. Wenn wäre das ein anderer Adapter ... bitte ggf. einen neuen AdapterRequest anlegen

**Comment by Sigi74** [comment]
Hätte gedacht, das passt hier; 
Kalender über Nextcloud werden ja über den caldav synchronisiert.
Jede Aufgabenliste braucht soweit ich weiß einen passenden Kalender dazu.
Link zum Kalender https://cloud.domain.com/remote.php/dav/calendars/User/personal/
Link laut Nextcloud zur Aufgabenliste https://cloud.domain.com/remote.php/dav/calendars/User/personal/

Und am PC sowie auch am Handy ist es immer derselbe Sync-Client der beides Synchronisiert 
(Dabei Syncronisiere ich mit https://www.davx5.com/ wenn das von Interesse ist)

**Comment by Sigi74** [comment]
> Tasks sind aber nicht kalender?! und auch nicht ICS als Dateiformat. Wenn wäre das ein anderer Adapter ... bitte ggf. einen neuen AdapterRequest anlegen

**Comment by Sigi74** [comment]
w

**Comment by Garfonso** [comment]
> Tasks sind aber nicht kalender?! und auch nicht ICS als Dateiformat. Wenn wäre das ein anderer Adapter ... bitte ggf. einen neuen AdapterRequest anlegen

Das stimmt nicht. Tatsächlich sind die Tasks im Kalender und sogar in der ICS Datei (zumindest bei Nextcloud). Man müsste "nur" die VTODO Einträge in der Datei unterstützen und Parsen.

**Comment by jens-maus** [comment]
> > Tasks sind aber nicht kalender?! und auch nicht ICS als Dateiformat. Wenn wäre das ein anderer Adapter ... bitte ggf. einen neuen AdapterRequest anlegen
> 
> Das stimmt nicht. Tatsächlich sind die Tasks im Kalender und sogar in der ICS Datei (zumindest bei Nextcloud). Man müsste "nur" die VTODO Einträge in der Datei unterstützen und Parsen.

Sie stecken vielleicht in der ICS mit drin, sind inhaltlich trotzdem keine Kalendereinträge. Und geparst werden sie eben einfach nicht weil der ioBroker.ical adapter als ical bibliothek "node-ical" verwendet das auch von VTODO Einträgen auch nichts weiss. Insofern gibt es hier nix zu tun und wenn du sowas umgesetzt haben willst sollte man IMHO einen extra neuen Adapter ioBroker.todo oder so dafür generieren. Hier in diesem Ticket geht es aber definitiv erst einmal nicht weiter.

**Comment by Garfonso** [comment]
Sorry, aber das stimmt nicht... node-ical unterstützt VTODO und ical sortiert VTODOs aktiv aus. Es war eine Sache von ein paar Minuten einfach eine Liste von TODOs mit auszulesen: https://github.com/Garfonso/ioBroker.ical

Ich höre an der Stelle erstmal auf, weil mir der usecase auch nicht 100% klar ist und man den erstmal klar definieren müsste, um eine Darstellung der To-dos im ioBroker zu haben. 

Es bleibt natürlich der Punkt, dass ical != ics ist. Aber naja... Ob da jetzt ein zweiter Adapter wirklich die beste Option ist für ein paar Zeilen Code. VTODO und VEVENT liegen nicht umsonst immer zusammen, es ist halt weitgehend dasselbe.
