### ISSUE TITLE
support of nextcloud tasks

### ISSUE THREAD

**Issue by Sigi74** [iobroker-community-adapters/ioBroker.ical#407]
Reopen: https://github.com/iobroker-community-adapters/ioBroker.ical/issues/402

Could you support Nextcloud tasks (reading and if possible writing) ? Would be great!

Thanks!

Ich benütze die Aufgabenliste (Task) in Nextcloud die auch über caldav mit dem Handy syncronisiert werde;
Würde gerne die Daten auch in iobroker einlesen

Habe die ics-datei heruntergeladen und sie mit einem Editor angesehen 
Die Tasks (Aufgaben) sind alle in der ICS vorhanden
Format:
```
BEGIN:VTODO
UID: 
CREATED:20190627T165810
LAST-MODIFIED:20191119T111724
DTSTAMP:20191119T111724
SUMMARY: Irgendeine Aufgabe
PERCENT-COMPLETE:70
STATUS:IN-PROCESS
DESCRIPTION:
END:VTODO
```

Wenn es mehr Beispiele braucht, kann ich gerne welche posten.

**Comment by jens-maus** [comment]
Das wird nichts werden. Die node-ical library die von ioBroker.ical genutzt wird unterstützt das nicht. Auch passt das nicht ins Konzept, denn der Adapter heisst nunmal 'ical' und nicht 'ics' und folglich geht es hier eben um Kalender und nicht TODO Listen. D.h. Anders lösen!

**Comment by Sigi74** [comment]
Finde ich schade, da beides eigentlich zusammengehört.
Es ist ja ein und dasselbe File, wo Kalendereinträge und To-do-Listen gespeichert werden.

**Comment by jens-maus** [comment]
> Finde ich schade, da beides eigentlich zusammengehört.

Dann entwickle ne Erweiterung/Änderung dazu und sende ein PullRequest ein.

**Comment by Sigi74** [comment]
Bin leider kein Programmierer, deshalb finde ich es ja schade :-) 
Ich kenne mich ja leider nicht aus, aber soweit ich sehen kann, auch bei Apple/ical scheint es zusammenzugehören 
Nennt sich dort "Erinnerungen"

**Comment by Apollon77** [comment]
@Sigi74 Dann lege einen Adapter Request an wenn nicht schon da und dann kann man es in einen neuen Adapter einbauen

**Comment by Sigi74** [comment]
@Apollon77 
Adapter Request erstellt 
Dann hoffe ich mal :-)
https://github.com/ioBroker/AdapterRequests/issues/723
