### ISSUE TITLE
Fehlerhafte Eventauswertung

### ISSUE THREAD

**Issue by dontobi** [iobroker-community-adapters/ioBroker.ical#42]
Ich habe vor ein paar Tagen den ical Adapter in Betrieb genommen und meinen Schichtplan Kalender eingetragen.

Als Events habe ich Frühschicht, Spätschicht und Nachtschicht eingetragen.

Während der Termine Frühschicht und Spätschicht ist das zugehörige Event auf true gesetzt.
Bei dem Event Nachtschicht ist der Wert jedoch nur bis 0 Uhr auf true gesetzt, obwohl der Kalendereintrag von 22 Uhr bis morgens 6 Uhr eingetragen ist.

Ich bitte um einen Fix des Problems. Gerne teste ich auch mögliche Fixes.

**Comment by Apollon77** [comment]
Bitte aktuelle Github Version installieren. Geht es dort?

**Comment by Apollon77** [comment]
Bitte reopen wenn es in 1.4.0 nicht geht und ics file anhängen
