### ISSUE TITLE
Using TZID without Luxon available is unsupported.

### ISSUE THREAD

**Issue by realwax** [iobroker-community-adapters/ioBroker.ical#426]
https://github.com/iobroker-community-adapters/ioBroker.ical/issues/325

It's back again... 

v1.13.0
js 4.0.23
node v14.19.2

Thank you

**Comment by klein0r** [comment]
Seems like the errors wasn't fixed: https://github.com/jakubroztocil/rrule/issues/501#issuecomment-1146503580

**Comment by Apollon77** [comment]
@klein0r Thats why rrule downgrade again :-)

**Comment by klein0r** [comment]
@Apollon77 Downgrade to which version? 1.13.0 contains ``"rrule": "2.6.9"``

**Comment by Apollon77** [comment]
Ahh ok, then I missed that :-)) e should just make sure not to upgrade rrule :-)

**Comment by mswiege** [comment]
I have rrule 2.6.4 and I also have this issue. It is even that extreme that after one day kern.log and syslog get that big (in my case 11+ GB) until the disk is full and everything stops working until I flush the logs.

**Comment by realwax** [comment]
Is there anything we can do to hotfix this. I see Alexa adapter using a newer version of rrule. I am not to deep into npm/nodejs. Would it fix to change the dependencies of the contained package.json? Rrule is set to static 2.6.9. Which version would work without this issues. If I got it right whether ^ in front of the verions to follow master versions update wise or specifying the correct vesion should do the trick. 


"dependencies": {
    "@iobroker/adapter-core": "^2.6.0",
    "axios": "^0.27.2",
    "cloneextend": "^0.0.3",
    "json-schema": "^0.4.0",
    "node-ical": "^0.15.1",
    "rrule": "2.6.9"
  },


Can you recommend any measure? 

Thank you!

**Comment by Apollon77** [comment]
Ok, last time the fix was to have rrule 2.6.4 ... but then dependabot upgradded it to 2.6.9 again ...

**Comment by Apollon77** [comment]
1.13.2 on it's way

**Comment by larsauswsw** [comment]
When will 1.13.2 be available as stable version?
