### ISSUE TITLE
Events mit fehlenden Start und od. Endzeiten

### ISSUE THREAD

**Issue by chris10t** [iobroker-community-adapters/ioBroker.ical#43]
Hallo
Events mit fehlenden Start und od. Endzeiten nicht ignorieren, ev. über die Settings steuern :-)
siehe http://forum.iobroker.net/viewtopic.php?f=8&t=11343
Danke
LG Chris

**Comment by Apollon77** [comment]
ich wäre dabei zu sagen: Wenn "end" fehlt dann kann das mit start  end gefixt werden. wann/Wie kann es fehlendes "Start" geben?

**Comment by chris10t** [comment]
Das fehlende "End" könnte durchaus mit dem Start gefixt werden. Wie es jedoch mit Serien-Terminen od Ganztägigen sich verhält weiß ich nicht, 
Ehrlich gesagt habe ich mich zuwenig damit beschäftigt - solange die Lösung mein Problem löst :-)
LG

**Comment by Apollon77** [comment]
ich würde nur das fehlende end intern hinzufügen wenn es fehlt.

**Comment by Apollon77** [comment]
fixed auf Guthub (1.4.1) bitte testen!

**Comment by chris10t** [comment]
vielen Dank für die rasche Bearbeitung. 
Leider dauert es bei mir länger - komme erst Anfang nächster Woche dazu
LG

**Comment by chris10t** [comment]
Ausprobiert und alles gut. 
DANKE!
