### ISSUE TITLE
Office 365 - ICS ; aber nicht für alle

### ISSUE THREAD

**Issue by FirsttheFirst** [iobroker-community-adapters/ioBroker.ical#431]
Hi,

ich habe das Problem das ich einen Office 365 Family Account habe und i iobroker meine Kalender Sync habe.

Alle Kalender bis auf meinem werden syncronisiert.

Wenn ich den Adapter 1.12.1 lösche und neu installiere und dann noch die Anpassung mache:

  | // Find out whether SSL certificate errors shall be ignored
-- | --
  | const options = {
  | uri: urlOrFile,
  | headers: {
  | 'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.0.0 Safari/537.36'
  | }
  | };

Dann geht es ein paar Tage und dann ist nur mein Kalender wieder raus.
Alle anderen funktionieren ohne Probleme.

Ein Update auf 1.13.x bringt auch nichts.

Ich verzweifle hier langsam.

Gruß Freak

**Comment by Apollon77** [comment]
Und welche Version vom Adapter bringt Dir welche Fehlermeldungen im Log? AM besten die aktuellste Latest/Beta nutzen

**Comment by FirsttheFirst** [comment]
Hi,

aktuell versuche ich "Wieder" die Version 1.12.1
mit der hat es nun 2 Tage funktioniert meinen Kalender zu ziehen.
Gestern Abend ist dann "NUR" meiner wieder weg.
die anderen 4 funktionieren weiterhin ohne Probleme, es ist IMMER nur mein Kalender.

in der Version 1.13.x funktioniert es auch nicht.

Hier der Log (gekürzt)

Freak:
ical.0 | 2022-07-10 08:06:03.165 | debug | File read successfully https://outlook.live.com/owa/calendar/7d...............X/calendar.ics
-- | -- | -- | --
ical.0 | 2022-07-10 08:06:03.164 | debug | Successfully cached content for calendar "https://outlook.live.com/owa/calendar/7d......................30/calendar.ics" as /opt/iobroker/node_modules/iobroker.ical/cxxxxxxxxxxxxxxxxxxef3

Frau:
ical.0 | 2022-07-10 08:06:02.656 | info | processing URL: **Jennie** https://outlook.live.com/owa/calendar/4d3..........24/calendar.ics
ical.0 | 2022-07-10 08:06:02.515 | debug | File read successfully https://outlook.live.com/owa/calendar/4.................4/calendar.ics
ical.0 | 2022-07-10 08:06:02.515 | debug | Successfully cached content for calendar "https://outlook.live.com/owa/calendar/4d.........................24/calendar.ics" as /opt/iobroker/node_modules/iobroker.ical/a34...........................ace2

Kind:
ical.0 | 2022-07-10 08:06:02.466 | info | processing URL: **Jason-Lee** https://outlook.live.com/owa/calendar/202.................................258/calendar.ics
ical.0 | 2022-07-10 08:06:02.384 | debug | File read successfully https://outlook.live.com/owa/calendar/20..............258/calendar.ics
ical.0 | 2022-07-10 08:06:02.384 | debug | Successfully cached content for calendar "https://outlook.live.com/owa/calendar/202.....................258/calendar.ics" as /opt/iobroker/node_modules/iobroker.ical/a8...................fac

Kind:
ical.0 | 2022-07-10 08:06:02.379 | info | processing URL: **Hailey** https://outlook.live.com/owa/calendar/cf...........CDD/calendar.ics
ical.0 | 2022-07-10 08:06:02.343 | debug | File read successfully https://outlook.live.com/owa/calendar/cf..........CDD/calendar.ics
ical.0 | 2022-07-10 08:06:02.343 | debug | Successfully cached content for calendar "https://outlook.live.com/owa/calendar/cf........................CDD/calendar.ics" as /opt/iobroker/node_modules/iobroker.ical/71...........................................085

Kind:
ical.0 | 2022-07-10 08:06:02.319 | info | processing URL: **Alex** 
https://outlook.live.com/owa/calendar/0ab8.............E35/calendar.ics
ical.0 | 2022-07-10 08:06:02.294 | debug | File read successfully https://outlook.live.com/owa/calendar/0ab8.........E35/calendar.ics
ical.0 | 2022-07-10 08:06:02.293 | debug | Successfully cached content for calendar "https://outlook.live.com/owa/calendar/0ab....................E35/calendar.ics" as /opt/iobroker/node_modules/iobroker.ical/854............................f96


ical.0 | 2022-07-10 08:06:01.970 | debug | reading calendar from URL: https://outlook.live.com/owa/calendar/202.............................................258/calendar.ics, color: #000000
ical.0 | 2022-07-10 08:06:01.969 | debug | reading calendar from URL: https://outlook.live.com/owa/calendar/0ab8..........................................5E35/calendar.ics, color: #b49d4b
ical.0 | 2022-07-10 08:06:01.969 | debug | reading calendar from URL: https://outlook.live.com/owa/calendar/cf.........................................CDD/calendar.ics, color: #ccfd1c
ical.0 | 2022-07-10 08:06:01.967 | debug | reading calendar from URL: https://outlook.live.com/owa/calendar/4d3...............................................8024/calendar.ics, color: #ec0909
ical.0 | 2022-07-10 08:06:01.962 | debug | reading calendar from URL: https://outlook.live.com/owa/calendar/7d................................................C30/calendar.ics, color: #9f9d9d




Jetzt habe ich nur mal nach meinem Kalender gesucht:


ical.0 | 2022-07-10 08:22:03.376 | debug | File read successfully https://outlook.live.com/owa/calendar/7d........C30/calendar.ics
-- | -- | -- | --
ical.0 | 2022-07-10 08:22:03.375 | debug | Successfully cached content for calendar "https://outlook.live.com/owa/calendar/7d..............C30/calendar.ics" as /opt/iobroker/node_modules/iobroker.ical/c7...........f3



So sind aktuell die Ergebnisse.

Danke für deine Hilfe
Gruß Freak

**Comment by FirsttheFirst** [comment]
noch eine Ergänzung, ich habe nun ical.1 installiert um nur meine Daten abzufragen:

Okjekte sind aber leer.

<html>
<body>


ical.1 | 2022-07-10 09:20:07.986 | info | Terminated (NO_ERROR): Without reason
-- | -- | -- | --
ical.1 | 2022-07-10 09:20:07.986 | debug | Plugin sentry destroyed
ical.1 | 2022-07-10 09:20:02.980 | debug | Checking unprocessed event 7 null Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.980 | debug | Checking unprocessed event 6 null Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.979 | debug | Checking unprocessed event 5 null Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.979 | debug | Checking unprocessed event 4 null Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.978 | debug | Checking unprocessed event 3 null Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.978 | debug | Checking unprocessed event 2 null Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.977 | debug | Checking unprocessed event 1 null Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.977 | debug | Checking unprocessed event 0 later Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.977 | debug | Checking unprocessed event 0 now Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.976 | debug | Checking unprocessed event 0 today Vacation = false, state = false
ical.1 | 2022-07-10 09:20:02.910 | debug | displaying dates because of callback
ical.1 | 2022-07-10 09:20:02.886 | debug | File read successfully https://outlook.live.com/owa/calendar/7d..........C30/calendar.ics
ical.1 | 2022-07-10 09:20:02.885 | debug | Successfully cached content for calendar "https://outlook.live.com/owa/calendar/7d..................C30/calendar.ics" as /opt/iobroker/node_modules/iobroker.ical/a9.........dd
ical.1 | 2022-07-10 09:20:01.750 | debug | reading calendar from URL: https://outlook.live.com/owa/calendar/7d................C30/calendar.ics, color: #cfcece
ical.1 | 2022-07-10 09:20:01.672 | silly | States system redis pmessage system.adapter.ical.1.logLevel/system.adapter.ical.1.logLevel:{"val":"silly","ack":true,"ts":16...................64,"q":0,"from":"system.adapter.ical.1","lc":16.........................79}
ical.1 | 2022-07-10 09:20:01.645 | info | starting. Version 1.13.1 (non-npm: iobroker-community-adapters/ioBroker.ical#bb13.......................041) in /opt/iobroker/node_modules/iobroker.ical, node: v14.19.3, js-controller: 4.0.23
ical.1 | 2022-07-10 09:20:01.361 | debug | Plugin sentry Initialize Plugin (enabled=true)


</body>
</html>

**Comment by FirsttheFirst** [comment]
heute, egal welche Version, liest er laut LOG nicht mehr meine Kalender URL ein, diese wird einfach ignoriert

**Comment by FirsttheFirst** [comment]
Moin, 

ich habe nun mehrere Versuche mit allen APPs und Programmen inkl. MS Support gemacht, komisch ist:

![image](https://user-images.githubusercontent.com/100960468/183900132-fcc8db07-41b4-4778-ba87-ae132070e9e6.png)

Aber er kann es mir nicht anzeigen, wenn aber Daten da sein sollen.

**Comment by FirsttheFirst** [comment]
hier nochmal ein Anhang. Kann es sein das mehr als 4 Kalender nicht möglich sind (Gesamt)?

![image](https://user-images.githubusercontent.com/100960468/183915616-4a228327-5a78-4227-908e-7eb4267543f9.png)

**Comment by Apollon77** [comment]
Doch das sollte gehen ... zeig mal bitte die konfiguration ...
* Admin, Expertenmodus aktivieren
* Objekte Tab
* dort "system.adapter.ical.0" objekt aufklappen und rechts auf den stift.
* Dann das Raw JSON hier posten

**Comment by FirsttheFirst** [comment]
Das Problem bestand lange, aber ich konnte mich nicht drum kümmern. Nun habe ich alles neu gemacht, dann ging es ca 3 Tage, aber nun ist es wieder weg ohne das sich etwas getan habe.

Ich würde das ja hier posten, aber da sind ja meine ICS Daten drin und meine Kalender sollen ja nicht öffentlich gestellt werden, sondern ich möchte die verwenden.

Wie soll das gemacht werden ?

Gruß
