### ISSUE TITLE
Referring back to #366 : now Event not functioning properly

### ISSUE THREAD

**Issue by aski71** [iobroker-community-adapters/ioBroker.ical#432]
I discovered the following issue:

At 18:35: Created a calender entry for 19:15 for monitor point "Charge".
At 19:00: cron updates calender objects in ioBroker: Charge = false. (correct). It previews an event for Charge at 19:15.
At 19:15: Nothing happens
At 19:30: cron updates calender object in ioBroker again. Charge gets set to true.

I would have expected the Charge event to go to true at 19:15.
Was that a wrong assumption?

**Comment by Apollon77** [comment]
The data are only refreshed when the adapter runs. This means when the adapter does not run 19:15 also the event will not change back - the data will newly be evaluated once the next timed trigger runs.
This is a "scheduled" adapter that only executed code in the given cron-schedule you provide

**Comment by aski71** [comment]
Just to better understand:

Any calender event that happens between cron times of the adapter are only carried out at the cron times when the adapter refreshes?

So if the cron runs :00 and :30, any event that's in the diary in between (e.g. :12 or :17 :27) will only be executed at :00 or :30 whichever is closer?

My thought process was:
New diary entries are only synchronized at :00 or :30 but the diary entries will always be executed at the correct time: a 19:23 event at 19:23. 

So my thought process was wrong?

**Comment by Apollon77** [comment]
1.) Yes
2.) Yes
3.) Yes :-)

**Comment by aski71** [comment]
Got it, thanks. 👍🏻
