### ISSUE TITLE
(gelöst)Termin wird ein Tag später nicht auf false gestezt

### ISSUE THREAD

**Issue by ihavenonick** [iobroker-community-adapters/ioBroker.ical#44]
Hallo,
ich hab die Version 1.4.2 bei mir laufen und da scheint sich ein Bug eingeschlichen zu haben.
Bei mir wird die Heizung anhand von Einträgen für mein Schichtplan im Google Kalender gesteuert. Die Einträge sind dann eben "früh", "spät", "WE" und "Tag" (für die Feiertagserkennung). 
Das hatte auch alles zu Anfang  funktioniert. Jetzt habe ich das Problem, dass sobald ein Wechsel z.B. von "früh" zu "WE" stattfindet, an dem Tag an dem eigentlich im Kalender nur "WE" drin steht, mein Heizungs Script aber gleichzeitig noch das "früh" Programm startet da dieser Datenpunkt auch auf "true" steht, obwohl im Kalender hier nur der Eintrag "WE" aktiv ist. Hier wird ein Eintrag vom vorherigen Tag "mit geschleppt" der im Kalender so nie auftaucht.
Ich meine was gelesen zu haben das vergangene Ereignisse noch angezeigt werden, was in dem Fall nicht gut ist. Kann man das ausschalten, oder wie bringe ich dem iCal Adapter bei, dass er nur stur das auf "true" setzten soll, was an diesem Tag auch aktiv ist?

**Comment by Apollon77** [comment]
Bitte mal Version vom Github installieren. da wurde noch was geändert.
Ansonsten log bitte senden von einer Verarbeitung wo das Event aus gehen sollte mit Loglevel "Debug"

**Comment by ihavenonick** [comment]
So wie es aussieht läuft es mit der GitHub Version wieder. Hatte nur die Instanz manuell installieren müssen, das wurde bei der Installation über GitHub nicht gemacht, obwohl ich vorher den Adapter komplett gelöscht hatte. Alles neu eingerichtet und bis jetzt passt es wieder.
Danke für die prompte Problemlösung.

Was mir bei der fehlerhaften Version auch noch aufgefallen ist, unter dem DP data count waren die Events 2 Tage verschoben zum eigentlichen Eintrag im Kalender, was die Überschneidung auch erklären würde.

**Comment by Apollon77** [comment]
Super, Du hättest den Adapter nicht deinstallieren müssen. An sich einfach drüber installieren

**Comment by ihavenonick** [comment]
Da keiner so richtig sicher war, woran es liegt, geh ich da immer auf Nummer sicher und die erneute Konfiguration des Adapter dauert keine 5 Minuten.
Egal, es läuft wieder wie es soll, klasse Arbeit
