### ISSUE TITLE
Sich widerholende Ganztagstermine aus iCloud werden zum Teil falsch dargestellt

### ISSUE THREAD

**Issue by drtp** [iobroker-community-adapters/ioBroker.ical#45]
Hallo,

ich habe das Problem, dass sich wiederholende Ganztagstermine des iCloud-Kalenders meiner Frau zu falschen Zeitpunkten angezeigt werden.
![2018-03-07_17h15_22](https://user-images.githubusercontent.com/17758445/37103859-84e55770-222b-11e8-8761-9044d0cde12a.png)

Hier ein Screenshot des entsprechenden iCloud-Kalenders, in dem der oben markierte Ganztagstermin nicht erscheint.
![2018-03-07_17h16_28](https://user-images.githubusercontent.com/17758445/37103866-8e1e1dfe-222b-11e8-8c10-60a3faa794d7.png)

Tatsächlich findet der markierte Ganztagstermin erst am 7. August, also genau 5 Monate später, statt.

Seltsamerweise tritt das Problem bei meinen eigenen Ganztagsterminen aus der iCloud nicht auf. Woran könnte das liegen?

Gruß,

Thorsten

**Comment by Apollon77** [comment]
Bitte installier mal die aktuellste Version vom GitHub. Existiert das Problem dann noch? 

Dann bitte loglevel auf Debug (Instanzen - Expertenmodus, dann Spalte loglevel ändern.) und hier posten.

**Comment by jens-maus** [comment]
Hattest du diesen Termin in der Vergangenheit vielleicht mal fälschlicherweise auf dieses Datum gesetzt und dann gelöscht oder verschoben? Einen ähnliches Verhalten hatte ich vor ein paar tagen auch mit einem termin der auftauchte obwohl ich ihn verschoben hatte. Hatte aber leider keine zeit mir das in den ics files anzuschauen sodass nur die Vermutung bleibt das verschobene termine ggf irgendwie im ics format anders geflaggt werden und das der ioBroker ical nur nicht beherrscht. Aber wie gesagt, bur eine Vermutung.

**Comment by drtp** [comment]
Hallo,

@Apollon77: Da muss ich mal nachfragen. Kann ich das Update im Terminal des Docker-Containers  per "sudo apt-get update" und "sudo apt-get upgrade" durchführen, oder wie mache ich das am besten? 

@jens-maus: Das dürfte nicht die Ursache des Problems sein. Die betreffenden Ganztages-Termine wurden definitiv nicht verschoben. So sind beispielsweise auch viele Geburtstage betroffen, die einfach um fünf Monate versetzt angezeigt werden. Was mich aber stutzig macht, ist die Tatsache, dass das Problem bei meinem eigenen iCloud-Kalender nicht auftritt, sondern nur bei einem von zweien meiner Frau. Vielleicht sollten wir einfach mal den betreffenden iCloud-Kalender neu anlegen.

**Comment by Apollon77** [comment]
Adapter-Update über Admin. Tab "Adapter", dort bei den Icons oben "Custom Install" wählen, ical auswählen und update installieren von Github

**Comment by Apollon77** [comment]
Ich habe gestern die 1.4.2 ins Latest geschoben. Also am einfachsten in den ioBroker-EInstellungen den Verwahrungsort auf "Latest" stellen und dann unter Adapter "reload" drücken. Dann sollte das Update angeboten werden im Admin

**Comment by drtp** [comment]
So, hab jetzt mal auf die Version 1.5.0 von iCal upgedatet. Allerdings ist im Moment kein problematischer Termin mehr vorhanden. Ich muss das jetzt mal beobachten und melde mich wieder. Auf jeden Fall schon mal vielen Dank für die schnelle Unterstützung.

**Comment by Apollon77** [comment]
Ich mache hier mal zu ... wenn es wieder auftritt bitte Reopen

**Comment by drtp** [comment]
Das Problem tritt leider nach wie vor auf. Allerdings nur mit einem einzigen iCloud-Kalender. Alle anderen funktionieren, wie gewünscht.

**Comment by Apollon77** [comment]
Bitte mal aktuellste Version vom Github versuchen. Wir haben an "ganztagesterminen" nochmal was optimiert
