### ISSUE TITLE
"Ersetze 00:00 mit:" funktioniert nicht

### ISSUE THREAD

**Issue by eXTreMe-1337** [iobroker-community-adapters/ioBroker.ical#46]
In Adapterversion 1.4.2 funktioniert bei mir das "Ersetze 00:00 mit:" nicht. Wenn ich im Feld z.B. ein "x" oder " " eingebe dann steht im HTML Datenpunkt trotzdem weiterhin "00:00" als Startzeit für ein ganztägiges Event statt dem "x" oder " ". Mache ich etwas falsch oder ist das ein Fehler?

**Comment by Apollon77** [comment]
Also in den Adaptertests tut es. Wie exakt sehen die Einstellungen aus?

**Comment by Apollon77** [comment]
PS: Nur um sicherzugehen: Das "Ersetzte 0:00 mit" ist nur für "ganztagesevents" gedacht und implementiert. Es greift also nicht bei sonstigen "Nicht-Ganzstages terminen" die um 0:00 starten oder enden!

**Comment by eXTreMe-1337** [comment]
> Also in den Adaptertests tut es. Wie exakt sehen die Einstellungen aus?

Habe inzwischen von 1.4.2 auf 1.5.0 geupdated (und teste auch gleich deine 1.5.1).
![ical2](https://user-images.githubusercontent.com/28637054/37469730-3f252d82-2866-11e8-9591-e9a74bf68d32.png)
Und ja, es handelt sich um ein Ganztags-Event.
ich habe statt x auch "x" (also mit anführungszeichen) oder nur ein Leerzeichen bzw Leerzeichen in Anführungszeichen versucht, klappt aber alles nicht.

**Comment by Apollon77** [comment]
Dann bitte Loglevel auf Debug und Log von einem Lauf senden. Hier oder als PN im Forum

**Comment by Apollon77** [comment]
1.5.2?

**Comment by eXTreMe-1337** [comment]
sorry für die späte antwort:
ja der "Fehler" besteht weiterhin, auch mit 1.5.3.
Log lasse ich dir im Forum zukommen.

**Comment by Apollon77** [comment]
Siehe Forum-PN: Du hast keine Ganzstages-Events, sondern 0 Minuten Events.

Wenn ich das sehe ist das kein Ganztagesevent sondern nur 0 Minuten.
Das "Ersetze 0:00 mit" greift nur bei "Ganztagesevents". Um das zu Forcieren musst Du noch "Start-Endzeiten verbergen" aktivieren
