### ISSUE TITLE
adjust runEveryMinutes

### ISSUE THREAD

**Issue by Marco-online** [iobroker-community-adapters/ioBroker.ical#463]
where can i adjust runEveryMinutes , at the moment it runs every 30 minutes, but i want to set is to 24 hours.

**Comment by Feuer-sturm** [comment]
@Marco-online If you want to change the time how often ical adapter will be scheduled you can change it in menu instances in this sub menu:
![grafik](https://user-images.githubusercontent.com/25422320/190217742-a55fb7df-c6ca-4264-b760-7887e7417fed.png)

**Comment by Marco-online** [comment]
@Feuer-sturm  Thanks for your quick reply, worked for me !

**Comment by Feuer-sturm** [comment]
@Marco-online great. Please close this issue if everything is fine
