### ISSUE TITLE
Einbindung von webcal Kalender URLs funktioniert nicht

### ISSUE THREAD

**Issue by eXTreMe-1337** [iobroker-community-adapters/ioBroker.ical#47]
Ist es möglich webcal URLs einzutragen? Wenn ich die Adapterdoku richtig verstanden habe soll man einfach in der URL das webcal:// durch http:// ersetzen ... klappt aber nicht. https:// hab ich auch schon versucht, ebenfalls erfoglos. Wollte gerne meine Geburtstags und Veranstaltungen aus Facebook darüber einbinden. Auch über den Umweg die Kalender erst vom Googlekalender abonnieren zu lassen und dann den Googlelink des abonnierten (Facebook-)Kalenders einzutragen hat auch nicht geklappt.

**Comment by Apollon77** [comment]
Die eingegebene URL muss ein valides ICS-File Format (ical Format https://de.wikipedia.org/wiki/ICalendar) liefern. Dann geht der Adapter.
Bei einigen Anbietern bekommt man das exakt zurück unter der URL. Bei Fcebook weiss ich nicht

**Comment by eXTreMe-1337** [comment]
wenn ich die URL des Kalenders mit http:// statt webcal:// in meinen Browser eingebe, dann wird ein .ics File als Download geöffnet. Das sollte doch dann valide sein, oder nicht?

**Comment by Apollon77** [comment]
Ja. Am besten machen. Adapter loglevel auf Debug setzen und dann file und log (direkt aus
Dem logfile Kopiert nicht aus dem Admin!!)

**Comment by eXTreMe-1337** [comment]
ok, habe ich gemacht, ich sehe dort aber keine fehler im log (terminated with "ok").
ich schicke dir aber die entsprechenden zeilen aus dem logfile per PN über das Forum wenn das ok ist, ich poste das ungern hier öffentlich, da dort die kalenderurl incl authentifizierungstoken drinsteht.
