### ISSUE TITLE
iCal file upload

### ISSUE THREAD

**Issue by Jey-Cee** [iobroker-community-adapters/ioBroker.ical#479]
**Describe the solution you'd like**
Upload a iCal file in adapter config (or redirect to file tab), store it in adapter storage and make it choosable in the config. 

**Describe alternatives you've considered**
Upload it via ftp to filesystem and add path in config. Or use web adapter storage and add URL in config.

**Comment by Jey-Cee** [comment]
Work in progress: https://github.com/Jey-Cee/ioBroker.ical
Waiting for fix issue in jsonConfigComponent: https://github.com/ioBroker/ioBroker.admin/issues/1766

**Comment by Jey-Cee** [comment]
Still not solved

**Comment by Feuer-sturm** [comment]
@Jey-Cee is this issue still relvant?
Issue is linked to admin issue https://github.com/ioBroker/ioBroker.admin/issues/1766 as well
