### ISSUE TITLE
Featurerequest: "+1" Ausblenden in HTML State bei Events die über 0 Uhr hinaus gehen

### ISSUE THREAD

**Issue by eXTreMe-1337** [iobroker-community-adapters/ioBroker.ical#48]
Ich binde die HTML States des Adapters in VIS ein. Wenn ich ein Event habe das erst am Folgetag endet, dann wird immer ein "+1" hintendran gestellt (z.B. 19.03.2018 22:00-06:00+1 N-Schicht).
Das "+1" möchte ich gerne ausblenden. Geht das? Wenn ja: wo?
Falls nicht: Kann man das bitte implementieren? Danke vorab!

**Comment by Apollon77** [comment]
Das +x (kann ja auch +3 sein) bedeutet das das Ende x Tage in der Zukunft liegt. Wenn man das rausnimmt wie willst du das erkennen?

**Comment by eXTreMe-1337** [comment]
In meinem Anwendungsfall (Schichtplan Kalender) sind alle Events immer 8 Stunden lang, ein +2 oder größer ist da also nicht möglich. :)
Daher wäre eine "opt-out" Funktion für dieses "Feature" für mich sehr nützlich.

**Comment by Apollon77** [comment]
hm ... man könnte überlegen bei Events mit einer Dauer <24h das +1 webzulassen weil "menschlich verständlich"

**Comment by eXTreMe-1337** [comment]
das klingt gut!

**Comment by Apollon77** [comment]
Bitte mal 1.5.1 vom Github testen

**Comment by eXTreMe-1337** [comment]
Super, das klappt genau so wie ich es haben wollte in der 1.5.1!
Danke für die schnelle Umsetzung!
