### ISSUE TITLE
Option, für Notizen und Ort

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.ical#495]
Ist es möglich, eine Option einzufügen, Notizen, die im Termin stehen und Orte, im "HTML"-Datenpunkt mit anzugeben?

**Comment by warhammer73** [comment]
Hätte ich auch Interesse.

**Comment by senger1985** [comment]
Bitte Issue wieder öffnen, da Fall noch nicht behandelt
