### ISSUE TITLE
LOCATION nicht enthalten

### ISSUE THREAD

**Issue by hdering** [iobroker-community-adapters/ioBroker.ical#50]
In meinen Terminen nutze ich das Feld Veranstaltungsort (in googe ical: LOCATION). Diese werden anscheinend nicht ausgelesen.

Ist das gewollt oder eventuell ein Fehler?

**Comment by Apollon77** [comment]
Ein Fehler ist es nicht. Was würdest Du denn erwarten was passiert bzw wo "location" verfürbar sein sollte? In den Data-JSON ?

**Comment by hdering** [comment]
Jepp in dem JSON Objekt würde es mir reichen.

**Comment by hdering** [comment]
Denkst du das klappt auf die schnelle?

**Comment by Apollon77** [comment]
Bitte 1.5.3 vom GitHub testen. Geht?

**Comment by hdering** [comment]
Perfekt. Funktioniert! Ticket kann geschlossen werden :).
