### ISSUE TITLE
Ablage der Daten pro Kalendereintrag in Datenpunkten

### ISSUE THREAD

**Issue by warhammer73** [iobroker-community-adapters/ioBroker.ical#504]
Hallo,

wäre es in Zukunft möglich die Daten pro Termin einzeln auswertbar in Datenpunkten abzulegen?

Also z.B.:
Ordner "1" mit den darunter liegenden Datenpunkten:
Date
Starttime
Endtime
Description
Location
Summary
... analog Ordner 2...X abhängig von den Parametern wieviele Tage im Voraus die Daten genutzt werden sollen.

Nutzen der Erweiterung:
Es wäre damit einfacher die einzelnen Termine als Informationen für weiterführende Steuerungen per Script zu verwenden ohne immer das Datenfeld Text oder Table selbst parsen zu müssen.

**Comment by Apollon77** [comment]
Ich denke ich das das "so einfach wäre" weil ja all diese states dann dynamisch angelegt werden würden und dann wieder gelöscht und so ...  wie soll ein Skript das nutzen?

**Comment by warhammer73** [comment]
So wie jetzt auch die Einträge genutzt werden aus dem vw-connect Adapter für das Laden (Bis zu 100 letzte Einträge), wie sourceanalytics Einträge etc.

Durch den Baum wandern, das gesuchte Date vergleichen und wenn es ein Match gibt die restlichen Einträge auslesen.

Würde ich sinnvoller finden, als das aktuell nötige manuelle parsen des Text DPs und wenn man alternativ zu "Tagen" die Anzahl der Termine im voraus parametrierbar macht könnte man dann sogar relativ einfach noch auf Veränderungen reagieren.

Aber Details müsste man dann in der Tat nochmal betrachten falls so eine Erweiterung in Betracht gezogen wird.

**Comment by Apollon77** [comment]
> So wie jetzt auch die Einträge genutzt werden aus dem vw-connect Adapter für das Laden (Bis zu 100 letzte Einträge),

Ganz ehrlich: Nur das es Adapter tun heisst nicht das es sinnvoll ist ;-) Vor allem nicht als Objekt-Strukturen.

Da wäre in meinen Augen einzig "JSON" auch nur irgendwie sinnvoll geeignet, aber ja da müsste man mal ganz tief inklusive den Use-cases dazu überlegen

**Comment by warhammer73** [comment]
Naja, mein Usecase im Groben:
Die Familie trägt in den Kalender für die Heizung/Klimatisierung des Hauses relevante Informationen ein. Diese Informationen werden verwendet um Gasheizung und Splitklima anhand der Daten im Kalender, vorhandenen Temperaturen, Wettervorhersage und aktuellem Akkustand zu steuern. 

Aktuell muss ich mich durch das Textfeld suchen ob und was sich geändert hat um in den allermeisten Fällen zu entscheiden "Interessiert mich aktuell gar nicht". Json wäre da schonmal mehr Standard als die aktuelle Text Struktur, aber ein Eintrag für alle Termine befreit halt noch nicht von immer wieder überflüssigem durchsuchen.

Eigene Strukturen pro Termin hätten da den Vorteil das ich sie als Trigger verwenden könnte (... und wenn die Ordner entweder today, nextday... im Namen versehen wären könnte man gleich nur auf die richtigen Triggern). Wobei dann einer der Use-Cases der zu betrachten ist natürlich "mehrere Termine pro Tag" wäre.

**Comment by Apollon77** [comment]
Die Idee bisher für sowas sind genau die Events ... Man definiert ein paar Wörter in den "Terminen" und due hast boolean states ob etwas davon aktiv ist oder nicht . EInfaches wort-matching und der adapter tut das schon ...

**Comment by warhammer73** [comment]
In den Events finde ich aber nur den Titel/Summary des Termins. Weder wann er startet, noch wann er endet, keinen Ort, keine Kommentare. Insofern würde mir ein Event zwar sagen das da irgend ein Termin da ist - Details muss ich mir immer noch über text, table oder html zusammensuchen.

**Comment by Apollon77** [comment]
Naja oder du vergibst die "texte" so das alles drin ist ... aber ja ... all good

**Comment by warhammer73** [comment]
Ja, ich kann mir auch Workarounds über Workarounds basteln und den Titel vom Termin so lang machen das da alles drinsteht. Von Temperatur über Raum bis zur Start und Endzeit. Oh Wait - Datum, Start- und Endzeit muss ich ja trotzdem eingeben, weil sonst der Trigger nicht triggert.
... und spätestens mit "30.12.2023,08:00,12:00,Wohnzimmer,22,Arbeit, aber nur wenn Du arbeiten willst, sonst 30.12.2023,08:00,12:00,Wohnzimmer,22, ja-mit letztem Komma. Wieso? Ist halt so."   und dem Hinweis das ganze dann nochmal als Datum, Start, Endzeit des Termins einzutragen ist der WAF dann so niedrig das ich auch gleich sagen kann "Geh zum Display und trag dort ein wann es warm sein soll".

Der Workaround ist also die Doppelpflege von Daten - inkl. aller Inkonsistenzrisiken - und dann ein manuelles zerpflücken des Termintitels.
Wirklich?

Kann ja sein das ich der einzige bin so einem UC bin, dann macht eine Umsetzung eh keinen Sinn. Aber der Vorschlag hilft eher nicht - Dann doch besser alles über text raussuchen. ;)

**Comment by jens-maus** [comment]
> Der Workaround ist also die Doppelpflege von Daten - inkl. aller Inkonsistenzrisiken - und dann ein manuelles zerpflücken des Termintitels. Wirklich?

Die Alternative dazu ist doch klar: Setz dich hin, mach die Änderungen und submitte ein PullRequest. Dieser Adapter ist open source, also los ran!

**Comment by warhammer73** [comment]
> > Der Workaround ist also die Doppelpflege von Daten - inkl. aller Inkonsistenzrisiken - und dann ein manuelles zerpflücken des Termintitels. Wirklich?
> 
> Die Alternative dazu ist doch klar: Setz dich hin, mach die Änderungen und submitte ein PullRequest. Dieser Adapter ist open source, also los ran!

Nö, nicht mehr. Als Student mit viel Zeit habe ich Ende der 90er einiges an Treibern für Videobeschleuniger, Capturekarten, Ansteuerung von spezieller Hardware etc. gebaut, angepasst und erweitert. Jetzt habe ich die Zeit dafür nicht mehr weil mir andere Dinge wesentlich wichtiger sind im Leben. 
Offensichtlich bin ich bisher der Einzige der für meinen Vorschlag Verwendung hat - Solche Einzelsachen sollte man tunlichst aus einer SW heraushalten. Verkompliziert nur die weitere Entwicklung, das Testen etc.

Aber spannend Dein Tonfall und die offensichtliche Erwartung hier doch bitte nicht über mögliche und weniger mögliche Workarounds zu diskutieren. ;)

Wie ich schon schrieb - Für mich wird die Alternative jetzt sein aus dem text DP die Daten rauszuparsen. Unschön aber relativ schnell umzusetzen.
