### ISSUE TITLE
keine Einstellungen möglich

### ISSUE THREAD

**Issue by RamsesIoBroker** [iobroker-community-adapters/ioBroker.ical#51]
Nach der Installation kann ich unter Einstellungen lediglich "Tagesvorschau", "Farbe" und den Bereich "00:00" ändern, alles andere ist nicht anwählbar, auch nicht die anderen Reiter oben oder alles was unter "+" eingebbar sein sollte. Unter Instanzen fehlt vor iCal die Ampel.

![instanz](https://user-images.githubusercontent.com/37696863/37827508-0e0c9e64-2e98-11e8-88b4-489d8a31d96a.png)

Ich habe es mit den Versionen 1.3.x, 1.4.x und 1.5.x probiert, doch immer die gleichen Probleme.
Was kann ich tun?

Edit
Habe es gerade in einem Forum gefunden:
2. Instanz laden (die geht) - beide Instanzen wieder löschen - Instanz neu laden

**Comment by GermanBluefox** [comment]
Es müssen irgendwelche Fehlermeldungen in der Browserkonsole sein.
Bei mir geht alles.
![image](https://user-images.githubusercontent.com/4582016/37861842-82a7d298-2f42-11e8-8602-59a259323c76.png)

**Comment by RamsesIoBroker** [comment]
Adminversion ist 3.2.0

Aber, wie bereits beschrieben, klappt es ja nun über den Umweg:

zweite Instanz von iCal laden (die funktioniert dann)
erste Instanz löschen
erste Instanz neu laden (die geht dann plötzlich auch)
zweite Instanz (bei Bedarf) löschen

**Comment by Apollon77** [comment]
Dann kann es nur irgendwas mit Browsercache gewesen sein.
