### ISSUE TITLE
Termine von "gestern" gewünscht

### ISSUE THREAD

**Issue by 2000ede** [iobroker-community-adapters/ioBroker.ical#53]
Hallo,
ich würde mir auch die Termine von "gestern" wünschen. Durch die schon jetztige Kennzeichnung durch "heute", "morgen",.... dürfte es für Nutzer kein Problem sein, wenn sie die Termine "gestern" nicht haben wollen.

Danke für Eure Bewertung!

**Comment by Apollon77** [comment]
Was wäre der Sinn von Terminen von gestern? Die sind doch vorbei?!

Ebenso weiss ich nicht was Du mit

> Durch die schon jetztige Kennzeichnung durch "heute", "morgen",.... dürfte es für Nutzer kein Problem sein, wenn sie die Termine "gestern" nicht haben wollen.

meinst. Viele User nutzen die HTML-Table zur Anzeige und ändern da auch nicht viel dran ...  Wenn auch plötzlich immer "gestern" drin wäre wäre das blöd

**Comment by 2000ede** [comment]
Vielen Dank für die schnelle Reaktion!
Nach den Terminen von "heute" und "morgen" kann "gestern" wichtiger sein als "übermorgen" :-)
nach dem Motto "Mist, habe gestern nicht an den Geburtstag gedacht".

Mit der Kennzeichnung meinte ich -> Objekte -> ical.0 -> data -> html ical table 

Hier werden ja (sofern man die Vorgabe gewählt hat), die Termine entsprechend gekennzeichnet mit "Heute", "Morgen", "Übermorgen", "in x Tagen".

M.E. kann damit jeder, der "Gestern" nicht haben will, die im Code rauswerfen. Umgekehrt ist es nicht möglich bzw. nur mit Workaround (stelle mir gerade Skript vor, welches um 23 Uhr vorabend läuft und dann die "heute" werde zwischenspeichert. Das ist aber nicht optimal....

OK. ich dachte mir, könnte auch für andere interessant sein. Wenn damit andere dann Probleme haben, sollte man es ggf. doch so belassen wie es ist. Wäre aber schade :-)

**Comment by Apollon77** [comment]
Also ich denke es ist unpraktikabel das generierte HTM zu verarbeiten und das macht glaube ich auch niemand. Wenn basieren eigene "Aussortierungen" eher auf der JSON-Table.

Der Adapter beachtet momentan alle Termine die zum Zeitpunkt der Verarbeitung gerade laufen oder in der Zukunft sind.
Das Hauptthema mit "vergangenen" terminen ist das das ja nicht "gestern" sein muss. Es kann "heute gerade beendet" sein oder "lief die letzten 5 Tage und gerade/gestern Abend fertig gewesen" und so.

In meinen Augen wäre das Feature also eher auch "vergangene Termine die letzten X Stunden/Tage rückwirkend" auch aufzulisten oder so ... Hm ...

**Comment by RK62** [comment]
Würde für mich auch Sinn machen:
Mein TaskManager **MeisterTask** stellt eine iCal aller noch offenen Aufgaben mit Terminen bereit. Momentan verschwinden überfällige Aufgaben, weil nur Einträge ab heute angezeigt werden. Ein zweiter Parameter für die vergangene Tage als zusätzliche Filter wäre genial.

**Comment by twonky4** [comment]
Kann man sowas nicht mit dem History Adapter lösen?

**Comment by Apollon77** [comment]
Denke eher nicht sinnvoll mit History.
