### ISSUE TITLE
Probleme mit wiederkehrenden Terminen: Falscher Ausweis

### ISSUE THREAD

**Issue by 2000ede** [iobroker-community-adapters/ioBroker.ical#54]
Hallo,

ich möchte folgende Auffälligkeit melden:

Ich trage in einem google Kalender Geburtstage als jährlich wiederkehrende (!) Termine (GANZTÄGIG) ein.
Gestern zeigte er mir diesen Termin dann als von "00:00-23:00" Uhr an.
Heute zeigt er mir den heutigen Termin unter "noch 1 Tag" an.

Könnt Ihr das bitte mal prüfen? Herzlichen Dank!
Ich gehe davon aus, dass das Problem nur bei wiederkehrenden Terminen besteht.

hier nochmal zu sehen: er erkennt 4 Termine für heute, weist aber zwei der vier unter "noch 1 Tag aus"
beides sind wiederkehrende Termine

![grafik](https://user-images.githubusercontent.com/37264959/38131672-444597f4-3408-11e8-9eae-639b2cbefe9e.png)

![grafik](https://user-images.githubusercontent.com/37264959/38131216-9f05f014-3406-11e8-8fd6-72b9c75895e6.png)

![grafik](https://user-images.githubusercontent.com/37264959/38131280-d5111fe4-3406-11e8-89c3-cbd53e4751ab.png)

![grafik](https://user-images.githubusercontent.com/37264959/38131299-e5ceef82-3406-11e8-8629-9bde90effb1e.png)

![grafik](https://user-images.githubusercontent.com/37264959/38131325-f3181e84-3406-11e8-92f6-dfcb487e0618.png)

Debug Ausgabe kenne ich leider als Anfänger hier nicht.

**Comment by Apollon77** [comment]
Debug: Instanzen - Expertenmodus. Spalte loglevel bei der Instanz auf Debug stellen. Laufen lassen. 

Logfile (nicht loganzeige im Admin) von /opt/iobroker/log/... Logs rauskopieren

**Comment by 2000ede** [comment]
danke, wieder was dazu gelernt. Das Logfile ist sehr mächtig und es stehen sehr viele persönliche Daten drin. Kann ich dir auch direkt per mail versenden? Ungerne möchte ich diese frei ist www stellen.

**Comment by BuZZy1337** [comment]
Ich vermute da stimmt etwas mit der Zeitumstellung nicht. (CET/CEST +/- 1 Stunde)..

**Comment by 2000ede** [comment]
interessant ist vielleicht auch die Sicht ohne Datum in Wort:
Hier zeigt er die betroffenen Termine mit einem -> an und einer Uhrzeit
![grafik](https://user-images.githubusercontent.com/37264959/38133152-4d0c0566-340e-11e8-87fd-94a5ccf25e9d.png)

**Comment by Apollon77** [comment]
Der Pfeil heißt „Termin läuft gerade“ und dann wird in deinem Fall die Endzeit angezeigt. 

Und ich teile die Sommer/Winterzeit Idee weil am Ende sieht es so aus wie es dann wäre weil tagesübergreifender termin

**Comment by 2000ede** [comment]
ok. das mit dem Pfeil verstanden. Deinen letzten Absatz habe ich nicht ganz verstanden -> its not a bug - its a feature?

**Comment by BuZZy1337** [comment]
Wäre interessant zu wissen wie deine ics Datei aussieht mit den ganztägigen wiederkehrenden Ereignissen. Da können wir dann bestimmt was am Adapter ändern dass das berücksichtigt wird..

**Comment by Apollon77** [comment]
Genau ics file und einmal ein Debug log vom Lauf für diesen kalender

**Comment by 2000ede** [comment]
gelöscht

**Comment by BuZZy1337** [comment]
Damit ist das "Problem" aber nicht gelöst.. Wenn du jetzt einen wiederkehrenden Termin einstellst wird dieser mit CEST gespeichert (Sommerzeit). Ich tippe, dass wenn die Uhren wieder umgestellt werden und die CET aktiv wird, tritt das Problem auch bei dem neu erstellten Termin auf.

Ich bin gerade im Urlaub und habe nur mein Handy zur Verfügung.. Werde ein paar Tests machen wenn ich wieder zuhause bin..  Wenn Apollon77 bis dahin nicht schon diesbezüglich aktiv geworden ist.. ;) :D

**Comment by Apollon77** [comment]
Bitte mit 1.6.0 vom Github neu testen, siehe testthread im ioBroker Forum bald

**Comment by 2000ede** [comment]
gerne, 
ggf. Anfängerfrage von mir: Die anderen Adapter zeigen immer an, wenn es ein Update gibt. Bei mir im ioBroker (3.3.9) steht weiterhin die Version 1.5.3.
Erfolgt hier noch in der Auswahl die 1.6.0 oder muss ich manuell tätig werden?

**Comment by Apollon77** [comment]
1.6.0 ist noch nicht veröffentlicht. Steht aber zum testen zur Verfügung. Im Admin unter Adapter gibt es den custom install button. Dort „vom github“ und iCal in der Liste wählen. Dann installiert du die Vorabversion.

**Comment by 2000ede** [comment]
Hi,
aktuell tritt das Problem nicht mehr auf. Ich kann allerdings nicht sagen, ob es damit erledigt ist. ggf. trat es seinerzeit auf, dass die Termine vor Zeitumstellung eingestellt wurden und nach Zeitumstellung erst falsch angezeigt wurden.

Problem aber erstmal erledigt. Vielen Dank!

**Comment by Apollon77** [comment]
Einfach wieder öffnen wenn es wieder passiert oder neues issue
