### ISSUE TITLE
Öffentliche Google-Kalender abbildbar?

### ISSUE THREAD

**Issue by 2000ede** [iobroker-community-adapters/ioBroker.ical#55]
Hallo,

ich gewinne freude an dem ical.Adapter. Von Google baue ich meine Kalender über die "Privatadresse im ICAL Format" ein. Neben meinen eigenen Kalendern habe ich auch andere öffentliche abonniert:

z.B. den Kalender von Werder Bremen
https://calendar.google.com/calendar/htmlembed?src=bund_6136_%2557erder%2B%2542remen%23sports%40group.v.calendar.google.com&ctz=Europe%2FBerlin

Hier liegt ja nur die "öffentliche URL" (siehe oben vor). 
Diese Kalender scheint der Ical.Adapter nicht zu berücksichtigen.

Ist dies so oder habe ich etwas falsch gemacht?
Gerne würde ich solche Termine mit in der Ausgabe haben.

Vielen Dank!

**Comment by Apollon77** [comment]
Der Adapter braucht zwingend eine Datei im ics Format als Ergebnis des Aufrufs kommt. Der Link ist irgendwie einer um den Kalender als html in eine Seite einzubinden. 

Finde die ics Adresse des Kalenders und es wird funktionieren ;-)

**Comment by 2000ede** [comment]
ok, danke für die wie immer schnelle Reaktion!
