### ISSUE TITLE
Einzeln geänderte wiederkehrende Termine

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.ical#557]
Wenn man bei wiederkehrenden Terminen, im nachhinein, verändert, wird dieser nicht angezeigt.

**Versions:**  
 - Adapter version: 1.13.2
 - JS-Controller version: 4.0.24
 - Node version: 16.17.0
 - Operating system: Linux auf Proxmox

**Comment by Apollon77** [comment]
Bitte ein minimales ical file zur verfügung stellen und ein debug log von dessen verarbeitung und sagen was passiert und was erwartet wird. Danke

**Comment by senger1985** [comment]
Sry, muss mal etwas "doof" fragen.
Meinst du die ics-Datei?
Bei Google kann ich nur die gesamte ics downloaden und nicht auf minimal stellen.
Und wohin soll ich sie schicken, wenn die Datei gemeint ist?

**Comment by Apollon77** [comment]
Ja eine ics Datei meine ich, und die idee ist einen kalender zu erstennen der nur diesen einen Fall hat und den dann extra zu exportierne oder so ... und Datei einfach hier in GitHub hochladen

**Comment by senger1985** [comment]
Komisch, gerade habe ich nochmal einen wiederkehrenden Termin verschoben und jetzt wird er richtig angezeigt.
Danach habe ich ihn wieder auf den richtigen Tag gesetzt und das hat auch geklappt.
Kannst gerne das Issue schließen.

**Comment by Apollon77** [comment]
Alles kalr, wenn du es nochmals nachstellen kannst gern wieder auf machen mit mehr details
