### ISSUE TITLE
Probleme mit zurückliegenden Terminen

### ISSUE THREAD

**Issue by Eiserfeyer** [iobroker-community-adapters/ioBroker.ical#57]
Versuche noch die Konstellation zu klären, unter denen dieser Fehler auftaucht.

Habe einen Müllkalender, welcher von der dazugehörigen App in den Google-Kalender exportiert wird. Am 13.04.2018 rufe ich von dort den Kalender mit ioBroker.ical auf. Mit den u.g. Einstellungen wird an erster Stelle ein Abfalltermin vom vergangenen Tag (12.04.2018) angezeit:
"→ 13.04. - Ganztags Restabfall".
Setze ich in den u.g. Einstellungen "Jahr verbergen" auf false, wird wieder der Termin von Gestern angezeigt, aber in anderer Darstellung:
"Noch 1 Tag Restabfall"

Setze ich dann auch noch "Start-Endzeiten verbergen" auf false, dann ist die Anzeige wieder ok und der gestrige Termin wird nicht mehr angezeigt.

Wenn gewünscht, sende ich den Kalender gerne zu, weil ich hier irgendwie keine Möglichkeit finde, Anhänge hochzuladen.

--------------------

Einstellungen:
Sprache: Deutsch
Tagesvorschau:7
Benutze Farben für HTML:Ja
Default-Farbe für HTML:white
Datumsangaben mit führender '0':Ja
Ersetze Datum mit Worten:Ja
Jeder Kalendar hat eigene Farbe:Ja
Ersetze 00:00 mit: - Ganztags
Start-Endzeiten verbergen:Ja
Jahr verbergen:Nein

**Comment by Eiserfeyer** [comment]
Nachfolgend besagter Abfallkalender als .ics-Datei.
[Abfallkalender- basic - 2018-04-13.zip](https://github.com/ioBroker/ioBroker.ical/files/1907534/Abfallkalender-.basic.-.2018-04-13.zip)

**Comment by Apollon77** [comment]
Kein Feedback, Closed. Reopen wenn noch relevant
