### ISSUE TITLE
Event falsch ausgelesen

### ISSUE THREAD

**Issue by fs-plugins** [iobroker-community-adapters/ioBroker.ical#60]
Google-Kalender, iobroker alle Module aktuell

vorhanden Rules/Serie, zB jeden 3. Tag 
ein Tag davon im Kalender Termin-Text geändert

es wird der Serien-Text eingelesen, der tatsächliche Text an diesem Tag wird ignoriert

**Comment by Apollon77** [comment]
Duplicate ... verschobene einzeltermine einer Serie gehen aktuell nicht. Korrekt. Liegt an der „unter der Haube“ verwendeten Library :-(

Workaround ist Termin nicht zu verschieben sondern zu löschen und als eigenen Termin anzulegen.

**Comment by Apollon77** [comment]
Ps: #33

**Comment by fs-plugins** [comment]
danke für die schnelle Reaktion
ich hatte den Termin nicht verschoben in Google, sondern geöffnet, Text geändert und beim speichern 'nur diesen Termin'

**Comment by Apollon77** [comment]
Schau dir mal issue #33 an, da ist das issue befinde parsing library verlinkt. Also da gibts schon. Man muss das ggf debuggen und es ist nur ein bug (Vermutung) in der parser Library.

**Comment by fs-plugins** [comment]
hmh, debuggen von fremden codes ist immer problematisch

warum das so wichtig ist: mittels ical werden Diensttermine eingelesen, wenn zB von frei auf Dienstzeit oder von Dienstzeit auf frei gewechselt werden muss, dann schaltet es im Haus Heizungen und anderes ziemlich unsinnig

seufz, werd ich wohl ein komplett eigenes parse-script schreiben müssen oder aus Python Daten zur Verwendung exportieren (habe ja in meinen Routinen weitaus mehr geparste Daten zur Verfügung um zB auch auf gestern zugreifen zu können)
ist ja schon länger so, und wer weiß ob/wann sich da etwas tut (möchte meine Steuerung ja nicht auf unbestimmte Zeit kastrieren oder falsch laufen lassen)

dankeschön für's mühen ;-)

**Comment by Apollon77** [comment]
Häng doch an den Thread dran. Und warum du das brauchst. 

Debuggen von fremden Code ist eine Challenge ;-)

**Comment by fs-plugins** [comment]
> Debuggen von fremden Code ist eine Challenge ;-)

nicht, wenn man genügend eigene Projekte zum abarbeiten hat (zB fs-plugins)  und kaum Zeit für die privaten Projekte übrig bleibt ;-)

werde mir eine Lösung basteln, die auf den vorhandene Daten von PlanerFS aufbauen kann

**Comment by Apollon77** [comment]
Willkommen in Club ;-)
