### ISSUE TITLE
Warnung "admin.0 - ical has an invalid jsonConfig

### ISSUE THREAD

**Issue by mcm1957** [iobroker-community-adapters/ioBroker.ical#602]
Admin logs error:
```
  {
  "instancePath":"/items/_options/items/daysPast",
  "schemaPath":"#/definitions/numberProps/additionalProperties",
  "keyword":"additionalProperties",
  "params":{"additionalProperty":"trim"},
  "message":"must NOT have additional properties"
  },
  {
  "instancePath":"/items/_options",
  "schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if",
  "keyword":"if",
  "params":{"failingKeyword":"then"},
  "message":"must match \"then\" schema"
  }
```

**Comment by mcm1957** [comment]
Component NUMBER does not have an attribiute 'trim'

**Comment by mcm1957** [comment]
fixed with 1.13.6

**Comment by mcm1957** [comment]
NEXT error:

ical has an invalid jsonConfig: [{"instancePath":"/items/_calendars/items/calendars/items/3","schemaPath":"#/definitions/passwordProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"attr"},"message":"must NOT have additional properties"},{"instancePath":"/items/_calendars","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

**Comment by mcm1957** [comment]
This error looks like a schema problem ...

**Comment by dhd70106** [comment]
ical has an invalid jsonConfig: [{"instancePath":"/items/_calendars/items/calendars/items/3","schemaPath":"#/definitions/passwordProps/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"attr"},"message":"must NOT have additional properties"},{"instancePath":"/items/_calendars/items/calendars","schemaPath":"#/patternProperties/%5E.%2B/allOf/23/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/_calendars","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/8/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

**Comment by mcm1957** [comment]
will be handles at schema:
https://github.com/ioBroker/adapter-react-v5/issues/292

**Comment by mcm1957** [comment]
schema has been fixed.

**Comment by Pocky2507** [comment]
ical has an invalid jsonConfig: [{"instancePath":"/items/_calendars/items/calendars/items/5","schemaPath":"#/items/allOf/6/then/allOf/1/additionalProperties","keyword":"additionalProperties","params":{"additionalProperty":"width"},"message":"must NOT have additional properties"},{"instancePath":"/items/_calendars/items/calendars","schemaPath":"#/patternProperties/%5E.%2B/allOf/27/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/_calendars","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/9/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]

**Comment by gidhap** [comment]
@mcm1957 
Hallo fyi 
Ich habe heute die dieselbe Meldung bekommen

`admin.0 | 2024-10-05 13:31:56.132 | warn | ical has an invalid jsonConfig: [{"instancePath":"/items/_calendars/items/calendars/items/5","schemaPath":"#/items/allOf/6/then/allOf/1/additionalProperties","keyword":"additionalProperties","params":
{"additionalProperty":"width"},"message":"must NOT have additional properties"},{"instancePath":"/items/_calendars/items/calendars","schemaPath":"#/patternProperties/%5E.%2B/allOf/27/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"/items/_calendars","schemaPath":"#/properties/items/patternProperties/%5E.%2B/allOf/9/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"},{"instancePath":"","schemaPath":"#/if","keyword":"if","params":{"failingKeyword":"then"},"message":"must match \"then\" schema"}]
`

**Comment by mcm1957** [comment]
Diese Issue ist seit längerer Zeit geclosed. Wenn du ein aktuelles Problem melden willst, dann öffne bitte ein neues Issue und gib die erforderlichen Daten (wie z.B. Versionen) dort an.
