### ISSUE TITLE
Wochentage anzeigen

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.ical#61]
Gäbe es die Möglichkeit, die Termine z. B.: "Mo., 17.09.2018 17:30-18:30 Titel des Termins" anzeigen zu lassen?

**Comment by Apollon77** [comment]
Aktuell nicht. Man müsste die 7 Texte konfigurierbar machen weil es jeder anders haben will (Mo, Mon, Montag, Monday ...)

**Comment by Apollon77** [comment]
PS: Duplicate #39

**Comment by senger1985** [comment]
Gibt es hier schon Neuigkeiten?
Bzw. wurde der Vorschlag komplett verworfen?

**Comment by Apollon77** [comment]
@senger1985 DU hast schon gesehen das das hier als Duplicate geclosed ist? Also in DIESEM Ticket passiert garantiert gar nichts

**Comment by senger1985** [comment]
@Apollon77 sorry, der Kommentar ist unter dem falschen issue gelandet.
