### ISSUE TITLE
Ganztägige Termine

### ISSUE THREAD

**Issue by senger1985** [iobroker-community-adapters/ioBroker.ical#62]
Ganztägige Termine werden in der Version 1.6.1 einen Tag zu früh angezeigt.

**Comment by Apollon77** [comment]
Bitte Beispiel ics Daten und Konfiguration bereitstellen.

**Comment by Apollon77** [comment]
Duplicate zu #59?

**Comment by senger1985** [comment]
Wie kann ich die Datei zur bereitstellen?
Bekomme beim Runterladen eine Datei, die ich nur mit einem Kalender öffnen kann.
P.S.: Es geht um das Auslesen von einem Googlekalender.

**Comment by Apollon77** [comment]
ics Files sind normale Textdateien auch wenn du ggf wegen der File Extension ein wunschprogramm bekommst. Also kannst Du auch so speichern.
mir reicht auch von so einem File nur ein betroffenes Evebt, also versuch es bitte "os klein wie es nur geht" zu machen um das zu reproduzieren ... das ist nämlich das Problem. Bei mir war es nie reproduzierbar als ich #59 geschaut habe

**Comment by senger1985** [comment]
Meinst du so:
BEGIN:VEVENT
DTSTART;VALUE=DATE:20170916
DTEND;VALUE=DATE:20170917
RRULE:FREQ=YEARLY;BYMONTH=9;BYMONTHDAY=16
DTSTAMP:20180913T080621Z
UID:*zensiert*@google.com
CLASS:PUBLIC
CREATED:20170905T135620Z
DESCRIPTION:
LAST-MODIFIED:20180911T083752Z
LOCATION:
SEQUENCE:2
STATUS:TENTATIVE
SUMMARY:Thomas Geburtstag
TRANSP:OPAQUE
X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT

Der Termin ist am 16.09., wird mir aber für den 17.09. angezeigt.

**Comment by Apollon77** [comment]
Ok, versuche es mal die Tage, Danke

**Comment by Apollon77** [comment]
hast du noch nen screenshot der einstellungen vom Adapter und der Anzeige?

**Comment by Apollon77** [comment]
Please retest with 1.6.2!! now on npm, tomorrow in latest

**Comment by senger1985** [comment]
After the update to 1.6.2 I get the following message:

ical.0 | 2018-10-10 12:58:58.429 | error | at processImmediate [as _immediateCallback] (timers.js:745:5)
-- | -- | -- | --
ical.0 | 2018-10-10 12:58:58.429 | error | at tryOnImmediate (timers.js:768:5)
ical.0 | 2018-10-10 12:58:58.429 | error | at runCallback (timers.js:810:20)
ical.0 | 2018-10-10 12:58:58.429 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.ical/main.js:221:25)
ical.0 | 2018-10-10 12:58:58.429 | error | at processData (/opt/iobroker/node_modules/iobroker.ical/main.js:261:54)
ical.0 | 2018-10-10 12:58:58.429 | error | TypeError: Cannot read property 'utcOffset' of null
ical.0 | 2018-10-10 12:58:58.428 | error | uncaught exception: Cannot read property 'utcOffset' of null

**Comment by Apollon77** [comment]
Bitte nochmal vom Github updaten. Gab nen Fix

**Comment by senger1985** [comment]
Super, danke

**Comment by senger1985** [comment]
So wie es aussieht, ja.
Alle Ganztägige Termine, die ich jetzt zum Test eintrage, werden korrekt angezeigt.

**Comment by Apollon77** [comment]
cool
