### ISSUE TITLE
Termine fehlen - ab version 1.13.5

### ISSUE THREAD

**Issue by liv-in-sky** [iobroker-community-adapters/ioBroker.ical#627]
forum: [mcm1957](https://forum.iobroker.net/post/1100012)
https://forum.iobroker.net/post/1100012

bei wiederholungen fehlen daten - sieht man am besten bei 2-wöchigen wiederholungen:

beispiel: 2 wöchig mit alter version: 

![Image 027](https://github.com/iobroker-community-adapters/ioBroker.ical/assets/18462890/5e020ffb-47b9-426f-97c0-df4847fc38d7)

2 wöchig : neuste version - keine kalenderänderung - nur adapter update

![Image 028](https://github.com/iobroker-community-adapters/ioBroker.ical/assets/18462890/269ccfea-e6d4-41cd-8c35-0914a07119da)

**Comment by Apollon77** [comment]
Bitte Debug Log bereitstellen und idealerweise minimales ICS File mit dem es reproduziert werden kann.

Was ist "alte version" und was ist "aktuelle version"? Btte genate versionsnummern

**Comment by liv-in-sky** [comment]
alt ist 1.13.4 - da funktioniert es noch - dann nicht mehr

**Comment by liv-in-sky** [comment]
hier das log:
[log-ical.txt](https://github.com/iobroker-community-adapters/ioBroker.ical/files/13771057/log-ical.txt)
 und das ics
[liv-in-sky@gmail.com.ical.zip](https://github.com/iobroker-community-adapters/ioBroker.ical/files/13771059/liv-in-sky%40gmail.com.ical.zip)

**Comment by mcm1957** [comment]
@jens-maus 
Kannst ev nal schaun ob da was in node-ical faul sein könnte?
DANKE

**Comment by mrjeschke** [comment]
Gleiches Problem.
Wiederholung alle 2 Wochen. Anzeige Adapterversion 1.13.3


```
27.12.2023 08:30-09:00 vierzehntägig 
10.01.2024 08:30-09:00 vierzehntägig 
24.01.2024 08:30-09:00 vierzehntägig 
07.02.2024 08:30-09:00 vierzehntägig 
21.02.2024 08:30-09:00 vierzehntägig 
06.03.2024 08:30-09:00 vierzehntägig 
20.03.2024 08:30-09:00 vierzehntägig
```

Anzeige Adapterversion 1.13.5

```
10.01.2024 08:30-09:00 vierzehntägig 
07.02.2024 08:30-09:00 vierzehntägig 
06.03.2024 08:30-09:00 vierzehntägig
```

Ics-Datei
```
BEGIN:VCALENDAR
VERSION:2.0
CALSCALE:GREGORIAN
PRODID:-//SabreDAV//SabreDAV//EN
X-WR-CALNAME:testkalender
X-APPLE-CALENDAR-COLOR:#6EA68F
REFRESH-INTERVAL;VALUE=DURATION:PT4H
X-PUBLISHED-TTL:PT4H
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20231226T123051Z
DTSTAMP:20231226T123142Z
LAST-MODIFIED:20231226T123142Z
SEQUENCE:2
UID:0c876b6e-67aa-43ca-908a-78998c459c75
DTSTART;TZID=Europe/Berlin:20231227T083000
DTEND;TZID=Europe/Berlin:20231227T090000
STATUS:CONFIRMED
SUMMARY:vierzehntägig
RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=WE
END:VEVENT
END:VCALENDAR
```

**Comment by PapaSchlumpf70** [comment]
Der Fehler besteht leider immer noch. 
V1.14.0 berücksichtigt nur die ersten 5 Tage eines täglichen Serientermins im Google Kalender. Ab dem 6'ten Tag werden diese ignoriert.
Musste wieder auf 1.13.4 zurück.

**Comment by amg666** [comment]
Fehler kann ich bestätigen, habe einen Serientermin (Jeden Montag 18 Uhr) im google Kalender angelegt, der wird nicht angezeigt, wenn ich einen Einzeltermin anlege, wird der angezeigt (ical 1.14.0), 1.13.6 unf 1.13.5 gehen auch nicht, bis V1.13.4 läuft es richtig

**Comment by klein0r** [comment]
Please test with 0.14.1

**Comment by amg666** [comment]
i installed from github, now version 0.14.2, looks good, recurring appointments are correct now

**Comment by liv-in-sky** [comment]
thanx a lot  - funktioniert
