### ISSUE TITLE
Filter für hinzugefügte Kalender

### ISSUE THREAD

**Issue by mifricke** [iobroker-community-adapters/ioBroker.ical#63]
Hi!

Viele von uns nutzen den iCal Adapter sicher auch zum anzeigen öffentlicher Kalender. Da gibt es z.B. Kalender für die Abfallentsorgung.
Es wäre praktisch, wenn man bestimmte Stichworte eingeben könnte, nach denen die Events gefilter werden. Bei der Eingabe des Wortes "Windeltonne", hätte ich so nicht den Abholtermin der für mich nicht relevanten Windeltonne im Kalender. Es gibt bestimmt noch weitere Anwendungsfälle. Wäre ein Filter bzw. eine Blacklist denkbar?

**Comment by twonky4** [comment]
Das kann auch über ein Skript im ioBroker.javascript Adapter gelöst werden:
```javascript
var filter = ['Restmüll'];
var instanceNumber = '0';

function performFilterTable() {
    var count = 0;
    var table = getState('ical.' + instanceNumber + '.data.table').val;
    table = table.filter(word => !filter.includes(word.event));
    for (var i = 0; i < table.length; i++) {
        if(table[i]._class.indexOf('ical_today') != -1) {
            count++;
        }
    }
    setState('ical.' + instanceNumber + '.data.table', table, false);
    setState('ical.' + instanceNumber + '.data.count', count, false);
}
function performFilterHtml() {
    var html = getState('ical.' + instanceNumber + '.data.html').val;
    html = html.split('<br/>');
    var htmlNew = [];

    for (var i = 0; i < html.length; i++) {
        for (var j = 0; j < filter.length; i++) {
            if(html[i].indexOf(filter[j]) == -1) {
                htmlNew.push(html[i]);
                break;
            }
        }
    }

    setState('ical.' + instanceNumber + '.data.html', htmlNew.join('<br/>'), false);
}

on({id: 'ical.' + instanceNumber + '.data.table', ack: true}, performFilterTable);
on({id: 'ical.' + instanceNumber + '.data.html', ack: true}, performFilterHtml);
performFilterTable();
performFilterHtml();
```

**Comment by twonky4** [comment]
@Apollon77: Hier eine Spalte mit Filter einfügen:
![image](https://user-images.githubusercontent.com/3495103/47003311-3f45b080-d12f-11e8-9dbe-ad0deaae1131.png)
Zu diskutieren wären 2 Punke:
* Wie gespaltet man die Eingabe: Eine einfache Komma separierte Liste, ein RegEx oder geht vlt. beides in einem Feld?
* Wie die Filterlogic aussehen soll. Also soll nur in `event` oder auch in `_section` und `location` gesucht werden.

**Comment by twonky4** [comment]
@darkbrain85: Can you test the recent version 1.7.0 here from the repo?

**Comment by mifricke** [comment]
It works perfect! No Problems! 
I have not testet regex, but a Filter with "Windeltonne" as mentioned in my request is working with no problems. 

Thank you very much for this!
