### ISSUE TITLE
Serientermine werden nicht eingelesen

### ISSUE THREAD

**Issue by eric2905** [iobroker-community-adapters/ioBroker.ical#635]
iCal (v1.14.0)
iCloud-Kalender und auch Google Kalender

Sobald es sich um einen Serientermin handelt (z.B. täglich von 0500 - 2200 Uhr), ließt iCal nix mehr ein ... unter data ist alles leer (und daher natürlcih auch keine Events mehr).

**Comment by eric2905** [comment]
Mit der v1.13.6 gibt es diesen Fehler nicht

**Comment by eric2905** [comment]
Ergänzung:
Ganztags-Termine haben diesen Fehler nicht.
Die werden sauber eingelesen und verarbeitet.

**Comment by PapaSchlumpf70** [comment]
Das Problem besteht schon seit 1.13.5
Mit 1.14.0 werden die ersten 5 tage eingelesen und ab dem 6 Tag ignoriert. Musste wieder zur 1.13.4 zurück wechseln.

**Comment by revargne** [comment]
Bei mir tritt das Problem ebenfalls auf. Meine Serientermine existieren schon recht lange, daher werden bei mir in der 1.14.0 alle Termine ignoriert. 
Bin nach dem Tipp aus #627 auch auf die 1.13.4 zurück. Damit werden wieder alle Termine eingelesen.
Ich gehe davon aus, dass beide Issues sich auf das gleiche Problem beziehen.

**Comment by klein0r** [comment]
In 1.13.5 wurde rrule aktualisiert. Scheinbar gibt es damit (mal wieder) Probleme mit einigen Terminen.

https://github.com/iobroker-community-adapters/ioBroker.ical/compare/v1.13.4...v1.13.5

<img width="363" alt="Screenshot 2024-01-18 at 09 09 09" src="https://github.com/iobroker-community-adapters/ioBroker.ical/assets/1959049/55bc8617-c51c-45a3-8442-f0b55a513a16">

Komischerweise gibt es hier nichtmal ein Tag für die 2.8.x versionen. Eventuell zurückgezogen?! Mache mal ein Downgrade. https://github.com/jkbrzt/rrule

**Comment by klein0r** [comment]
Duplicate of #627

**Comment by xmace** [comment]
Bei mir das selbe Problem. Downgrade auf 1.13.4 notwendig.

In meinen Augen ein Major Bug - Bei mir läuft die komplette Heizungssteuerung über Serientermine im Google Kalender.

thx, xmace

**Comment by ChrMaass** [comment]
Selber Fehler bei mir

**Comment by klein0r** [comment]
Please test with 0.14.1

**Comment by ChrMaass** [comment]
Kann es sein das der Fehler wieder da ist? Meine Termine werden wieder nicht angezeigt 🤷🏼‍♂️
