### ISSUE TITLE
1.6.2 broken: Cannot read property 'utcOffset' of null

### ISSUE THREAD

**Issue by Apollon77** [iobroker-community-adapters/ioBroker.ical#66]
@twonky4  can ypu please have a look here: https://forum.iobroker.net/viewtopic.php?p=183691#p183691 ?!

```
ical.0	2018-10-09 22:01:04.848	error	TypeError: Cannot read property 'utcOffset' of null at processData (/opt/iobroker/node_modules/iobroker.ical/main.js:261:54) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.ical/
ical.0	2018-10-09 22:01:04.847	error	uncaught exception: Cannot read property 'utcOffset' of null
```

**Comment by twonky4** [comment]
I'm looking at it already.

**Comment by Apollon77** [comment]
PS: ical lib 0.8.0 ist auf npm ... kannst Du die beim PR gleich mit upgraden?

**Comment by jens-maus** [comment]
@Apollon77 Schon passiert :) (https://github.com/ioBroker/ioBroker.ical/commit/398bfaefd565f46a6d4a25154d7f4f84b54d8ca6)

**Comment by twonky4** [comment]
Do we need a new release?

**Comment by Apollon77** [comment]
I would ask people from forum to test github version, after that yes :-)

**Comment by sigi2345** [comment]
Hallo,

Fehler ist bei mir weg!

`

host.Medion | 2018-10-10 12:45:54.875 | info | instance system.adapter.ical.0 terminated with code 0 (OK)
-- | -- | -- | --
host.Medion | 2018-10-10 12:45:53.903 | info | instance system.adapter.ical.1 terminated with code 0 (OK)
host.Medion | 2018-10-10 12:45:53.882 | info | instance system.adapter.ical.2 terminated with code 0 (OK)

`

**Comment by Apollon77** [comment]
Ich schaue das ich nachher update vorbereiten kann. (Unterwegs) Wenn einer von Euch vorher kann gern PR schicken, dann gehts nachher rasend schnell :-)

**Comment by twonky4** [comment]
PR erstellt

**Comment by Apollon77** [comment]
Cool, Ihr habt mich heute beide male erwischt kurz bevor ich in nem meeting war ;-)

**Comment by MarkSau** [comment]
Hi..
Ich habe 1.6.3 drauf, jedoch ist der genannte Fehler immer noch da...

ical.0 | 2018-10-12 08:50:40.106 | error | at processImmediate [as _immediateCallback] (timers.js:745:5)
-- | -- | -- | --
ical.0 | 2018-10-12 08:50:40.106 | error | at tryOnImmediate (timers.js:768:5)
ical.0 | 2018-10-12 08:50:40.106 | error | at runCallback (timers.js:810:20)
ical.0 | 2018-10-12 08:50:40.106 | error | at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.ical/main.js:221:25)
ical.0 | 2018-10-12 08:50:40.106 | error | at processData (/opt/iobroker/node_modules/iobroker.ical/main.js:276:52)
ical.0 | 2018-10-12 08:50:40.106 | error | TypeError: Cannot read property 'utcOffset' of null
ical.0 | 2018-10-12 08:50:40.106 | error | uncaught exception: Cannot read property 'utcOffset' of null

**Comment by Apollon77** [comment]
Bitte zeige mehr log, auch wo steht das er wirklich die 1.6.3 startet! Im FOrum gab es einen Screenshot wo klar zu sehen war das die 1.6,2 gestartet wurde!

**Comment by twonky4** [comment]
@MarkSau: Wenn es möglich ist auch mit Beispielddaten (Datei oder URL).
@Apollon77: Das ist wirklich Verison 1.6.3. Die Zeilennummern der des Fehlers passen nicht zur 1.6.2

**Comment by twonky4** [comment]
Ich habe mal einen neuen issue #69 aufgemacht.
