### ISSUE TITLE
1.6.3 broken: Cannot read property 'utcOffset' of null

### ISSUE THREAD

**Issue by twonky4** [iobroker-community-adapters/ioBroker.ical#69]
The error continues to appear.

https://forum.iobroker.net/viewtopic.php?p=184317#p184317

Log from @MarkSau:
```
ical.0	2018-10-12 08:50:40.106	error	at tryOnImmediate (timers.js:768:5)
ical.0	2018-10-12 08:50:40.106	error	at runCallback (timers.js:810:20)
ical.0	2018-10-12 08:50:40.106	error	at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.ical/main.js:221:25)
ical.0	2018-10-12 08:50:40.106	error	at processData (/opt/iobroker/node_modules/iobroker.ical/main.js:276:52)
ical.0	2018-10-12 08:50:40.106	error	TypeError: Cannot read property 'utcOffset' of null
ical.0	2018-10-12 08:50:40.106	error	uncaught exception: Cannot read property 'utcOffset' of null
```

Can someone please provide example data?

**Comment by Apollon77** [comment]
I'm not sure about that! I want to see that really 1.6.3 was causing it because there was a forum screenshot showing 1.6.2 still ... so I want to see it (and requested). Before that I do not trust it :-)

**Comment by twonky4** [comment]
utcOffset exists in 1.6.3 in line main.js@L276. In 1.6.2 it is line main.js@L261.

I could reproduce the error with a invalid timezone. I'm very interested for real example data.

**Comment by MarkSau** [comment]
Hi..wie kann ich die URL weitergeben ohne die öffentlich zu machen? Oder/und was braucht Ihr noch?
![image](https://user-images.githubusercontent.com/22911084/46865690-b7a22e00-ce1e-11e8-94dd-5250e75b95fd.png)
![image](https://user-images.githubusercontent.com/22911084/46865880-67779b80-ce1f-11e8-8844-9d861241ea18.png)

**Comment by Apollon77** [comment]
Lad das FIle runter und schicke es als Forum PN oder attache es als ics Datei hier

**Comment by Apollon77** [comment]
@twonky4 check PN im Forum!

**Comment by twonky4** [comment]
As I tought: `TZID:W. Europe Standard Time` this is not a correct TZID. It is the metazone of "Europe/Berlin". Maybe I can use moment.js to get the timezone by metazone if TZID is not correct. I will check
