### ISSUE TITLE
falsch zeiten in ver 1.16.0

### ISSUE THREAD

**Issue by sjfm-design** [iobroker-community-adapters/ioBroker.ical#708]
**Describe the bug**  
eintrag im google kalander 08:00, anzeige im adapter 10:00
siehe beitrag im forum: https://forum.iobroker.net/topic/77778/ical-falsche-zeiten
nach downgrade 1.15.0 zeiten wieder richtig.

**Expected behavior**  
erst dachte ich, fehler durch zeitumstellung, dann der tip im forum auf das letzte update.

**Screenshots & Logfiles**  
https://forum.iobroker.net/topic/77778/ical-falsche-zeiten

**Versions:**  
 - Adapter version: 1.16.0
 - JS-Controller version: 7.0.2
 - Node version: 20.18.0
 - Operating system: Debian aktuell

**Comment by jens-maus** [comment]
Bitte Beispiel ics file liefern zum reproduzieren.

**Comment by sjfm-design** [comment]
wie soll ich das machen? die daten kommen ja direkt vom google kalender...
im ersten beitrag ist das gut nachzuvollziehen/reproduzieren.

**Comment by jens-maus** [comment]
Selbst bei google kann man die kalender sicherlich als ics files herunterladen. Und geht nicht darum das das im Beitrag nachvollziehbar ist, es muss selbst reproduzierbar sein. Mit meinen Kalenderanbindungen ist es das jedoch nicht. Ergo braucht man den Kalender der das auslöst um das Problem zu reproduzieren und dann entsprechend zu reparieren.

**Comment by sjfm-design** [comment]
Bin gerade unterwegs. Schau ich mir nachmittags an...
Werde auch Testtermine wieder eintragen.

**Comment by sjfm-design** [comment]
so, erstes file ist ohne, das zweite mit testeinträgen.,
[simon.mueck@gmail.com.ical.zip](https://github.com/user-attachments/files/17599451/simon.mueck%40gmail.com.ical.zip)
[simon.mueck1@gmail.com.ical.zip](https://github.com/user-attachments/files/17599450/simon.mueck1%40gmail.com.ical.zip)

wieder update auf 1.16 gemacht,
![grafik](https://github.com/user-attachments/assets/1ab7e29f-eef7-4f44-bd98-91f199c733c8)
zurück auf 1.15.0
![grafik](https://github.com/user-attachments/assets/6fd31df3-6e6f-4d59-8745-bf0a67ec8bc2)

**Comment by jens-maus** [comment]
So, bitte mal die 1.16.1 probieren wenn die verfügbar ist und dann hier reporten wenn/falls das problem beseitigt ist/wurde.

**Comment by sjfm-design** [comment]
perfekt! termine passen wieder!
danke für die schnelle lösung...
