### ISSUE TITLE
Problems with google-calendar with "special format"

### ISSUE THREAD

**Issue by Berchemer** [iobroker-community-adapters/ioBroker.ical#74]
Having problems with following event inside a goole-calendar which is automatically filled with events by an app of "Müllentsorger Schönmackers"

```
BEGIN:VEVENT
DTSTART;VALUE=DATE:20181022
DTSTAMP:20181020T054018Z
UID:fed81860717a443d86d57cb02a03a5a1@google.com
CREATED:20171217T113327Z
DESCRIPTION:
LAST-MODIFIED:20171217T113327Z
LOCATION:Zuhause
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Leichtverpackungen
TRANSP:OPAQUE
END:VEVENT
```

Aus dem oben gezeigten Event wird in der Ausgabe vom iCal-Adapter ein Event am 23.10.2018 gemacht. 

In den Einstellungen von ICAL ist nur die führende NULL bei Datumsangaben ausgewählt und ich habe eine 15-Tage-Vorschau ausgewählt. Sonst ist alles an Einstellmöglichkeiten nicht markiert.

Das Seltsame ist, dass der Adapter mit anderen Kalendern klar kommt und dort die richtige Zeit anzuzeigen scheint.
Vielleicht noch zur Ergänzung: Der Google-Kalender wird von einer APP des Müllentsorgers Schönmackers befüllt. Nach der Befüllung des Kalenders mit den Terminen des aktuellen Jahres wird am Kalender von Google manuell nichts mehr verändert.

In der Anlage ist die gesamte Kalender-Datei von Goolge im ics-Format.

[basic.ics.txt](https://github.com/ioBroker/ioBroker.ical/files/2498059/basic.ics.txt)

**Comment by twonky4** [comment]
Ist das Problem mit der Version 1.6.6 behoben?
