### ISSUE TITLE
Anzeige in Spalte Wert 

### ISSUE THREAD

**Issue by pjo12345** [iobroker-community-adapters/ioBroker.ical#77]
In Objekte in der Spalte Wert wird  HTML-Code angezeigt anstatt des Klartextes.
![image](https://user-images.githubusercontent.com/31406990/47623552-4eefcc80-db13-11e8-9c71-bcc471e13694.png)

Vorher:
![image](https://user-images.githubusercontent.com/31406990/47623555-629b3300-db13-11e8-8057-372edf0fb8b5.png)

Oder ist das eine Einstellungssache?

mfg pjo12345

**Comment by Apollon77** [comment]
Absicht in Admin. Html hat die Absicht im Admin teilweise komplett kaputt gemacht und deswegen würde das im Admin geändert.
