### ISSUE TITLE
Problem with an event. 2 days after event ical shows the event again

### ISSUE THREAD

**Issue by Berchemer** [iobroker-community-adapters/ioBroker.ical#78]
Am 03.11.2018 meldet ical mit dem folgenden Eintrag erneut Allerheiligen. Dieses Event ist jedoch nur am 01.11 gewesen und somit abgelaufen.

`BEGIN:VCALENDAR
PRODID:-//Nextcloud calendar v1.6.1
VERSION:2.0
CALSCALE:GREGORIAN
BEGIN:VEVENT
DTSTAMP:20180427T091803Z
UID:809386e8-ab35-48f5-a869-445b50c72a1b
DTSTART;VALUE=DATE:20181101
DESCRIPTION:Allerheiligen - Importiert von Ferienwiki.de
SUMMARY:Allerheiligen
END:VEVENT
END:VCALENDAR`

**Comment by twonky4** [comment]
Ist das Problem mit der Version 1.6.6 behoben?
