### ISSUE TITLE
invalid todo in readme?

### ISSUE THREAD

**Issue by twonky4** [iobroker-community-adapters/ioBroker.ical#79]
The README.md says something about moving recurring events but I didn't found something related in the RFC. Do have anyone more information about that todo?

> ## Todo
> * Known issue: For recurring events it works to delete single events, but it do not work to move them

I googled a couple of minutes and found only one solution to move recurring events by exclude it via `EXDATE` and create a new event. This behaviour is currently supported.

@Apollon77: You added this todo a year ago. Can you remember where it is from?

Side note: While looking in the RFC I noticed `RDATE` and `EXRULE` aren't supported yet by the adapter.

**Comment by Apollon77** [comment]
The todo came from https://github.com/ioBroker/ioBroker.ical/issues/33, so yes can be removed now I think :-)

To the missing stuff: when ical lib supprts it then it may be ok doable

**Comment by Apollon77** [comment]
removed
