### ISSUE TITLE
v1.7.0 deleting Objects after instance restart

### ISSUE THREAD

**Issue by eric2905** [iobroker-community-adapters/ioBroker.ical#85]
Just installed v1.7.0 on a fresh test system (2 iCal instances) and after a restart of the instance, the entire object "ical.x.events.0" will be deleted (see attached video)

Node : 8.12.0
npm : 6.4.1
js-controller : 1.4.2
[ical_1.7.0.mov.zip](https://github.com/ioBroker/ioBroker.ical/files/2612940/ical_1.7.0.mov.zip)

**Comment by Baenker** [comment]
Problem ist bekannt siehe #41

**Comment by Baenker** [comment]
Mag sein. War ja nur der freundliche Hinweis für Dich, dass das Problem bekannt ist und Du nicht alleine bist.

**Comment by eric2905** [comment]
Alles gut - war ja nur ein Hinweis, das man das nicht findet.

**Comment by Baenker** [comment]
Mit der aktuellen Version keine Probleme mehr. Datenpunkte bleiben bestehen.
