### ISSUE TITLE
Colorize option with individual colors for today, tomorrow and the day after tomorrow

### ISSUE THREAD

**Issue by drtp** [iobroker-community-adapters/ioBroker.ical#87]
The colorize option sets the colors for events taking place today, tomorrow and the day after tomorrow in red, orange and yellow, respectively. I would love to see an option to set individual alternatives for these three colors in order to match ical somehow better to my views.

**Comment by twonky4** [comment]
This is currently possible by using css style descripted here: https://github.com/ioBroker/ioBroker.ical#css
