### ISSUE TITLE
Version 1.7.0: Statusausgabeob event true, oder false ist

### ISSUE THREAD

**Issue by quorle** [iobroker-community-adapters/ioBroker.ical#88]
Ich muss wirklich sagen, dass ich meine ganzen Scripte auf basis des alten Adapters geschrieben habe. Hier war es so, dass eine Vorausgabe und Ausgabe am heutigen Tag ausgegeben wurde. Also ob ei Event an dem Tag ist, oder nicht. Dies gibt es ja jetzt nicht mehr. Hier bitte nachbessern und wieder einfügen.

**Comment by twonky4** [comment]
War irgend irgendwas nicht gut beschrieben?

**Comment by quorle** [comment]
Hatte gedacht die Auswertungen eines ereignises auf true/false wurde entfernt. Jedoch wurde dies auf einzelne Tage erweitert. Somit hat man eine weitere großzügigere Vorschau. Finde ich gut. Aber man kommt im ersten Augenblick etwas schlecht zurecht damit. Somit funktioniert alles wieder wunderbar.
Deshalb hab ich es wieder geschlossen

**Comment by twonky4** [comment]
👍
