### ISSUE TITLE
Problem mit Serien Termin und UTC

### ISSUE THREAD

**Issue by wendy2702** [iobroker-community-adapters/ioBroker.ical#90]
Genaue Beschreibung findet sich hier:

https://forum.iobroker.net/viewtopic.php?p=209171#p209124

**Comment by twonky4** [comment]
@wendy2702: Kannst du bestättigen das es mit der aktuellen github Version behoben ist?

**Comment by Apollon77** [comment]
Weil wie im Forum im zweifel User seltener Feedback geben wenn es klappt wie bei Fehlern ... :-) Reopen geht imme :-)

**Comment by wendy2702** [comment]
Hi,

konnte gerade Testen. Funktioniert scheinbar. Der Wocheneintrag wird wieder korrekt eingelesen.

Danke!
