### ISSUE TITLE
iCal weblink keine Daten

### ISSUE THREAD

**Issue by ManuelBu96** [iobroker-community-adapters/ioBroker.ical#91]
Hallo,

ich benutze das Plugin bereits seit einigen Tagen und hatte bisher keine Probleme. Nur leider wird der Kalender nicht mehr gepflegt. Ich habe bereits alles versucht. Adapter neuinstalliert bringt erst Besserung für einen Tag aber dann funktioniert es wieder nicht. Ich habe von gestern abend einmal einen Log angefügt vielleicht kann mir jemand helfen.

Gruß,
Manuel
![2019-01-05_21h23_07](https://user-images.githubusercontent.com/24299595/50739169-c0678d80-11dc-11e9-83a6-83145191269b.png)

**Comment by Apollon77** [comment]
Was heisst "Kalender wird nicht mehr gepflegt"?

Wenn bitte volles Log posten als text von der Platte (/opt/iobroker/log/...

**Comment by ManuelBu96** [comment]
Hallo,

Der Kalender wird nicht mehr gepflegt soll bedeuten das der Adapter keine Daten mehr abholt. Der Weblink der dahinter steht ist eigentlich mit einer gefüllten iCal Datei vorhanden. Diese wird aber leider nicht mehr eingelesen.

Habe die wesentlichen Daten bei Aufruf der iCal Adapter und Abruf des Kalenders eingefügt.
[iobroker.log](https://github.com/ioBroker/ioBroker.ical/files/2732324/iobroker.log)

**Comment by Apollon77** [comment]
Sicher das das File da ist? Ich bekomme ein "Not Found" mit https://www.awigo.de/fileadmin/kalender/AWIGO_Kalender_Rest_Papier_Gelb_Bio_Schadstoffmobil_627719001.ics

**Comment by twonky4** [comment]
Ich sehe das auch so. die URL: https://www.awigo.de/fileadmin/kalender/AWIGO_Kalender_Rest_Papier_Gelb_Bio_Schadstoffmobil_627719001.ics existiert nicht mehr oder ist falsch.

Zur Funktionsweise des Adapters: Er läd bei jedem Start eine URL oder lokale Datei und speichert die aktuellen Termine. Existiert die URL oder Datei nicht mehr, zeigt der Adapter auch keine Termine mehr.

**Comment by ManuelBu96** [comment]
Hallo,

OK da ist mir jetzt wohl ein Fehler unterlaufen beim erstellen des Adapters. Ich habe festgestellt das der Anbieter dafür regelmäßig die ical Datei entfernt. Muss mir da was anderes überlegen. Allerdings hatte ich den Link während meines testen auch immer probiert und da funktionierte er noch und die Daten wurden trotzdem nicht gespeichert.
