### ISSUE TITLE
Jährlich wiederholende Ereignisse werden nicht angezeigt

### ISSUE THREAD

**Issue by pdmetze** [iobroker-community-adapters/ioBroker.ical#98]
ical zeigt bei mir keine sich jährlich wiederholenden Ereignisse an (Anwendungsfall Geburtstage). Täglich/wöchentlich funktioniert.

**Comment by twonky4** [comment]
Kannst du bitte eine bespielt Kalender Datei bereitstellen mit der ich das testen kann?

**Comment by pdmetze** [comment]
Hi twonky, klar, siehe Anhang.
1 Termin "Testgeburtstag" wird jährlich wiederholt, sollte für 07.03.2019 angezeigt werden, tut es aber nicht.
1 Termin "Test Wochenwiederholung" wird wöchentlich wiederholt, wird für 08.03.2019 in ical angezeigt.
[yearly_recurrence.txt](https://github.com/iobroker-community-adapters/ioBroker.ical/files/2938324/yearly_recurrence.txt)

**Comment by twonky4** [comment]
Die Definition des Termins ist nicht gültig:
```
RRULE:FREQ=YEARLY;UNTIL=20190306T230000Z;INTERVAL=1;BYMONTHDAY=7;BYMONTH=3
DTSTART;VALUE=DATE:20190307
DTEND;VALUE=DATE:20190308
```

Der Termin ist definiert mit:
gültig ab 07.03.2019 00:00:00 (lokale Zeit) - 06.03.2019 23:00:00 (UTC)
bis 07.03.2019 00:00:00 (lokale Zeit) - 06.03.2019 23:00:00 (UTC)
Termin Dauer ist 1 Tag.
Immer am im März, am 7. Tag.

Während dieser Zeitspanne soll er immer am 03.07. angezeigt werden.

Da gültig ab und gültig bis genau gleich, der Termin ist also genau 0 Sekunden lang gültig :man_facepalming: 

Anders sieht das bei dem wöchentlichen Termin aus:
```
RRULE:FREQ=WEEKLY;UNTIL=20190829T220000Z;INTERVAL=1;BYDAY=FR;WKST=SU
DTSTART;VALUE=DATE:20190308
DTEND;VALUE=DATE:20190309
```

Der ist definiert mit:
gültig ab 08.03.2019 00:00:00 (lokale Zeit) - 07.03.2019 23:00:00 (UTC)
bis 29.08.2019 00:00:00 (lokale Zeit) - 28.08.2019 22:00:00 (UTC)
Termin Dauer ist 1 Tag.
Immer am Freitag.

Da hier der Gültigkeitszeitraum sind hier 15033600 Sekunden.

Der Adapter zeigt wo die aktuelle Uhrzeit (+Tagesvorschau) innerhalb des gültig ab/bis liegt. Das der jährliche Termin nie gültig ist wird er auch nicht angezeigt.
Mein Vorschlag: Erhöhe das gültig bis einfach um einen Tag.

**Comment by pdmetze** [comment]
Hi, okay ich glaube grob verstanden zu haben. Nun erstelle ich die .ics Datei natürlich nicht selbst, sondern nutze outlook.com mit Freigabe und Abruflink. Daher habe ich natürlich wenig Einfluss darauf, wie die Datei erstellt wird. Offensichtlich erstellt outlook.com die Datei so, wenn man jährlich wiederholende Ereignisse im Kalender hat.

Unabhängig davon ob das jetzt im iCalendar Standard richtig oder falsch ist, fände ich es sinnvoll - wenn möglich - das auch so in ical zu unterstützen und dann eben anzuzeigen, einfach um Kompatibilität auch zu outlook.com herzustellen...
